package com.jingrui.jrap.config.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.OrderBy;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "acc_config")
public class Config extends BaseDTO {

     public static final String FIELD_CONFIG_ID = "configId";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_TRX_CODE = "trxCode";
     public static final String FIELD_DESCIRPTION = "descirption";
     public static final String FIELD_BUSINESS_CODE = "businessCode";
     public static final String FIELD_ACTION_URL = "actionUrl";
     public static final String FIELD_USEAGE = "useage";
     public static final String FIELD_REFER01 = "refer01";
     public static final String FIELD_REFER02 = "refer02";
     public static final String FIELD_REFER03 = "refer03";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Where
     @Id
     @GeneratedValue
     @OrderBy("desc")
     private Long configId;

     @Where
     private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

     @Where
     @Length(max = 60)
     private String trxCode; //交易代码

     @Where
     @Length(max = 200)
     private String descirption; //描述

     @Where
     @Length(max = 200)
     private String businessCode; //业务代码

     @Where
     @Length(max = 200)
     private String actionUrl; //交易地址

     @Where
     @Length(max = 200)
     private String useage; //用途

     @Where
     @Length(max = 200)
     private String refer01; //参考字段01

     @Where
     @Length(max = 200)
     private String refer02; //参考字段02

     @Where
     @Length(max = 200)
     private String refer03; //参考字段03

     @Where
     @Length(max = 1)
     private String enabledFlag; //启用标识

     @Where
     private Long programApplicationId;

     @Where
     private Date programUpdateDate;


     public void setConfigId(Long configId){
         this.configId = configId;
     }

     public Long getConfigId(){
         return configId;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setTrxCode(String trxCode){
         this.trxCode = trxCode;
     }

     public String getTrxCode(){
         return trxCode;
     }

     public void setDescirption(String descirption){
         this.descirption = descirption;
     }

     public String getDescirption(){
         return descirption;
     }

     public void setBusinessCode(String businessCode){
         this.businessCode = businessCode;
     }

     public String getBusinessCode(){
         return businessCode;
     }

     public void setActionUrl(String actionUrl){
         this.actionUrl = actionUrl;
     }

     public String getActionUrl(){
         return actionUrl;
     }

     public void setUseage(String useage){
         this.useage = useage;
     }

     public String getUseage(){
         return useage;
     }

     public void setRefer01(String refer01){
         this.refer01 = refer01;
     }

     public String getRefer01(){
         return refer01;
     }

     public void setRefer02(String refer02){
         this.refer02 = refer02;
     }

     public String getRefer02(){
         return refer02;
     }

     public void setRefer03(String refer03){
         this.refer03 = refer03;
     }

     public String getRefer03(){
         return refer03;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
