package com.jingrui.jrap.settle.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.OrderBy;
import com.jingrui.jrap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "acc_document_detail")
public class DocumentDetail extends BaseDTO {

     public static final String FIELD_DETAIL_ID = "detailId";
     public static final String FIELD_DOCUMENT_ID = "documentId";
     public static final String FIELD_AMOUNT = "amount";
     public static final String FIELD_AUX01 = "aux01";
     public static final String FIELD_AUX02 = "aux02";
     public static final String FIELD_AUX03 = "aux03";
     public static final String FIELD_DIGEST = "digest";


     @Where
     @Id
     @GeneratedValue
     @OrderBy("desc")
     private Long detailId;

     @Where
     @NotNull
     private Long documentId; //结算单ID

     @Where
     private Long amount; //金额

     @Where
     @Length(max = 60)
     private String aux01; //辅助核算01

     @Where
     @Length(max = 60)
     private String aux02; //辅助核算02

     @Where
     @Length(max = 60)
     private String aux03; //辅助核算03

     @Where
     @Length(max = 200)
     private String digest; //摘要


     public void setDetailId(Long detailId){
         this.detailId = detailId;
     }

     public Long getDetailId(){
         return detailId;
     }

     public void setDocumentId(Long documentId){
         this.documentId = documentId;
     }

     public Long getDocumentId(){
         return documentId;
     }

     public void setAmount(Long amount){
         this.amount = amount;
     }

     public Long getAmount(){
         return amount;
     }

     public void setAux01(String aux01){
         this.aux01 = aux01;
     }

     public String getAux01(){
         return aux01;
     }

     public void setAux02(String aux02){
         this.aux02 = aux02;
     }

     public String getAux02(){
         return aux02;
     }

     public void setAux03(String aux03){
         this.aux03 = aux03;
     }

     public String getAux03(){
         return aux03;
     }

     public void setDigest(String digest){
         this.digest = digest;
     }

     public String getDigest(){
         return digest;
     }

     }
