package com.jingrui.jrap.settle.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.OrderBy;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "acc_document")
public class Document extends BaseDTO {

     public static final String FIELD_DOCUMENT_ID = "documentId";
     public static final String FIELD_DOCUMENT_CODE = "documentCode";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_TRANSACTION_ID = "transactionId";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_SETTLE_TYPE = "settleType";
     public static final String FIELD_SETTLE_AMOUNT = "settleAmount";
     public static final String FIELD_SETTLE_DATE = "settleDate";
     public static final String FIELD_SETTLE_CHANNEL = "settleChannel";
     public static final String FIELD_SETTLE_ITEM = "settleItem";
     public static final String FIELD_DIGEST = "digest";
     public static final String FIELD_ACCOUNT_ID = "accountId";
     public static final String FIELD_OPTACCT_ID = "optacctId";
     public static final String FIELD_OPTACCT_NAME = "optacctName";
     public static final String FIELD_OPTACCT_NUMBER = "optacctNumber";
     public static final String FIELD_OPTACCT_BANK = "optacctBank";
     public static final String FIELD_OPTACCT_BANK_PN = "optacctBankPn";
     public static final String FIELD_OPTACCT_BANK_CODE = "optacctBankCode";
     public static final String FIELD_OPTACCT_BANK_CITY = "optacctBankCity";
     public static final String FIELD_SN = "sn";
     public static final String FIELD_AUX01 = "aux01";
     public static final String FIELD_AUX02 = "aux02";
     public static final String FIELD_AUX03 = "aux03";
     public static final String FIELD_AUX04 = "aux04";
     public static final String FIELD_AUX05 = "aux05";
     public static final String FIELD_POST_DATE = "postDate";
     public static final String FIELD_DEAL_DATE = "dealDate";
     public static final String FIELD_FINISH_DATE = "finishDate";


     @Where
     @Id
     @GeneratedValue
     @OrderBy("desc")
     private Long documentId;

     @Where
     @Length(max = 100)
     private String documentCode; //结算单号

     @Where
     private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

     @Where
     private Long transactionId; //结算事务ID

     @Where
     @Length(max = 60)
     private String status; //状态

     @Where
     @Length(max = 60)
     private String settleType; //结算类型

     @Where
     private Long settleAmount; //结算金额

     @Where
     private Date settleDate; //结算日期

     @Where
     @Length(max = 60)
     private String settleChannel; //结算通道

     @Where
     @Length(max = 60)
     private String settleItem; //结算项目

     @Where
     @Length(max = 200)
     private String digest; //摘要

     @Where
     private Long accountId; //本方账户ID

     @Where
     private Long optacctId; //对方账户ID

     @Where
     @Length(max = 200)
     private String optacctName; //对方账户

     @Where
     @Length(max = 60)
     private String optacctNumber; //对方账号

     @Where
     @Length(max = 200)
     private String optacctBank; //对方银行

     @Where
     @Length(max = 60)
     private String optacctBankPn; //对方银行PN

     @Where
     @Length(max = 60)
     private String optacctBankCode; //对方银行编码

     @Where
     @Length(max = 60)
     private String optacctBankCity; //对方银行城市

     @Where
     @Length(max = 60)
     private String sn; //流水号

     @Where
     @Length(max = 60)
     private String aux01; //辅助核算01

     @Where
     @Length(max = 60)
     private String aux02; //辅助核算02

     @Where
     @Length(max = 60)
     private String aux03; //辅助核算03

     @Where
     @Length(max = 60)
     private String aux04; //辅助核算04

     @Where
     @Length(max = 60)
     private String aux05; //辅助核算05

     @Where
     private Date postDate; //过账日期

     @Where
     private Date dealDate; //交易日期

     @Where
     private Date finishDate; //结束日期


     public void setDocumentId(Long documentId){
         this.documentId = documentId;
     }

     public Long getDocumentId(){
         return documentId;
     }

     public void setDocumentCode(String documentCode){
         this.documentCode = documentCode;
     }

     public String getDocumentCode(){
         return documentCode;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setTransactionId(Long transactionId){
         this.transactionId = transactionId;
     }

     public Long getTransactionId(){
         return transactionId;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setSettleType(String settleType){
         this.settleType = settleType;
     }

     public String getSettleType(){
         return settleType;
     }

     public void setSettleAmount(Long settleAmount){
         this.settleAmount = settleAmount;
     }

     public Long getSettleAmount(){
         return settleAmount;
     }

     public void setSettleDate(Date settleDate){
         this.settleDate = settleDate;
     }

     public Date getSettleDate(){
         return settleDate;
     }

     public void setSettleChannel(String settleChannel){
         this.settleChannel = settleChannel;
     }

     public String getSettleChannel(){
         return settleChannel;
     }

     public void setSettleItem(String settleItem){
         this.settleItem = settleItem;
     }

     public String getSettleItem(){
         return settleItem;
     }

     public void setDigest(String digest){
         this.digest = digest;
     }

     public String getDigest(){
         return digest;
     }

     public void setAccountId(Long accountId){
         this.accountId = accountId;
     }

     public Long getAccountId(){
         return accountId;
     }

     public void setOptacctId(Long optacctId){
         this.optacctId = optacctId;
     }

     public Long getOptacctId(){
         return optacctId;
     }

     public void setOptacctName(String optacctName){
         this.optacctName = optacctName;
     }

     public String getOptacctName(){
         return optacctName;
     }

     public void setOptacctNumber(String optacctNumber){
         this.optacctNumber = optacctNumber;
     }

     public String getOptacctNumber(){
         return optacctNumber;
     }

     public void setOptacctBank(String optacctBank){
         this.optacctBank = optacctBank;
     }

     public String getOptacctBank(){
         return optacctBank;
     }

     public void setOptacctBankPn(String optacctBankPn){
         this.optacctBankPn = optacctBankPn;
     }

     public String getOptacctBankPn(){
         return optacctBankPn;
     }

     public void setOptacctBankCode(String optacctBankCode){
         this.optacctBankCode = optacctBankCode;
     }

     public String getOptacctBankCode(){
         return optacctBankCode;
     }

     public void setOptacctBankCity(String optacctBankCity){
         this.optacctBankCity = optacctBankCity;
     }

     public String getOptacctBankCity(){
         return optacctBankCity;
     }

     public void setSn(String sn){
         this.sn = sn;
     }

     public String getSn(){
         return sn;
     }

     public void setAux01(String aux01){
         this.aux01 = aux01;
     }

     public String getAux01(){
         return aux01;
     }

     public void setAux02(String aux02){
         this.aux02 = aux02;
     }

     public String getAux02(){
         return aux02;
     }

     public void setAux03(String aux03){
         this.aux03 = aux03;
     }

     public String getAux03(){
         return aux03;
     }

     public void setAux04(String aux04){
         this.aux04 = aux04;
     }

     public String getAux04(){
         return aux04;
     }

     public void setAux05(String aux05){
         this.aux05 = aux05;
     }

     public String getAux05(){
         return aux05;
     }

     public void setPostDate(Date postDate){
         this.postDate = postDate;
     }

     public Date getPostDate(){
         return postDate;
     }

     public void setDealDate(Date dealDate){
         this.dealDate = dealDate;
     }

     public Date getDealDate(){
         return dealDate;
     }

     public void setFinishDate(Date finishDate){
         this.finishDate = finishDate;
     }

     public Date getFinishDate(){
         return finishDate;
     }

     }
