package com.jingrui.jrap.settle.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.OrderBy;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "acc_transaction")
public class SettleTransaction extends BaseDTO {

     public static final String FIELD_TRANSACTION_ID = "transactionId";
     public static final String FIELD_TRANSACTION_CODE = "transactionCode";
     public static final String FIELD_TRANSACTION_TYPE = "transactionType";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_TRANSACTION_DATE = "transactionDate";
     public static final String FIELD_TRANSACTION_AMOUNT = "transactionAmount";
     public static final String FIELD_TRANSACTION_NUMBER = "transactionNumber";
     public static final String FIELD_PAY_AMOUNT = "payAmount";
     public static final String FIELD_PAY_NUMBER = "payNumber";
     public static final String FIELD_RECEIPT_AMOUNT = "receiptAmount";
     public static final String FIELD_RECEIPT_NUMBER = "receiptNumber";
     public static final String FIELD_DIGEST = "digest";
     public static final String FIELD_SERIAL_NUMBER = "serialNumber";
     public static final String FIELD_EMPLOYEE_ID = "employeeId";
     public static final String FIELD_DEAL_DATE = "dealDate";
     public static final String FIELD_SUCCESS_DATE = "successDate";
     public static final String FIELD_EXCEPTION_DATE = "exceptionDate";
     public static final String FIELD_REVERSE_DATE = "reverseDate";
     public static final String FIELD_AUX01 = "aux01";
     public static final String FIELD_AUX02 = "aux02";
     public static final String FIELD_AUX03 = "aux03";
     public static final String FIELD_AUX04 = "aux04";
     public static final String FIELD_AUX05 = "aux05";


     @Where
     @Id
     @GeneratedValue
     @OrderBy("desc")
     private Long transactionId;

     @Where
     @Length(max = 60)
     private String transactionCode; //事务编号

     @Where
     @Length(max = 60)
     private String transactionType; //事务类型

     @Where
     private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

     @Where
     @Length(max = 60)
     private String status; //事务状态

     @Where
     private Date transactionDate; //事务日期

     @Where
     private Long transactionAmount; //交易金额

     @Where
     private Long transactionNumber; //交易笔数

     @Where
     private Long payAmount; //付款金额

     @Where
     private Long payNumber; //付款笔数

     @Where
     private Long receiptAmount; //收款金额

     @Where
     private Long receiptNumber; //收款笔数

     @Where
     @Length(max = 60)
     private String digest; //摘要

     @Where
     @Length(max = 60)
     private String serialNumber; //流水号

     @Where
     private Long employeeId; //操作员

     @Where
     private Date dealDate; //交易日期

     @Where
     private Date successDate; //成功日期

     @Where
     private Date exceptionDate; //异常日期

     @Where
     private Date reverseDate; //反冲日期

     @Where
     @Length(max = 200)
     private String aux01; //辅助核算01

     @Where
     @Length(max = 200)
     private String aux02; //辅助核算02

     @Where
     @Length(max = 200)
     private String aux03; //辅助核算03

     @Where
     @Length(max = 200)
     private String aux04; //辅助核算04

     @Where
     @Length(max = 200)
     private String aux05; //辅助核算05


     public void setTransactionId(Long transactionId){
         this.transactionId = transactionId;
     }

     public Long getTransactionId(){
         return transactionId;
     }

     public void setTransactionCode(String transactionCode){
         this.transactionCode = transactionCode;
     }

     public String getTransactionCode(){
         return transactionCode;
     }

     public void setTransactionType(String transactionType){
         this.transactionType = transactionType;
     }

     public String getTransactionType(){
         return transactionType;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setTransactionDate(Date transactionDate){
         this.transactionDate = transactionDate;
     }

     public Date getTransactionDate(){
         return transactionDate;
     }

     public void setTransactionAmount(Long transactionAmount){
         this.transactionAmount = transactionAmount;
     }

     public Long getTransactionAmount(){
         return transactionAmount;
     }

     public void setTransactionNumber(Long transactionNumber){
         this.transactionNumber = transactionNumber;
     }

     public Long getTransactionNumber(){
         return transactionNumber;
     }

     public void setPayAmount(Long payAmount){
         this.payAmount = payAmount;
     }

     public Long getPayAmount(){
         return payAmount;
     }

     public void setPayNumber(Long payNumber){
         this.payNumber = payNumber;
     }

     public Long getPayNumber(){
         return payNumber;
     }

     public void setReceiptAmount(Long receiptAmount){
         this.receiptAmount = receiptAmount;
     }

     public Long getReceiptAmount(){
         return receiptAmount;
     }

     public void setReceiptNumber(Long receiptNumber){
         this.receiptNumber = receiptNumber;
     }

     public Long getReceiptNumber(){
         return receiptNumber;
     }

     public void setDigest(String digest){
         this.digest = digest;
     }

     public String getDigest(){
         return digest;
     }

     public void setSerialNumber(String serialNumber){
         this.serialNumber = serialNumber;
     }

     public String getSerialNumber(){
         return serialNumber;
     }

     public void setEmployeeId(Long employeeId){
         this.employeeId = employeeId;
     }

     public Long getEmployeeId(){
         return employeeId;
     }

     public void setDealDate(Date dealDate){
         this.dealDate = dealDate;
     }

     public Date getDealDate(){
         return dealDate;
     }

     public void setSuccessDate(Date successDate){
         this.successDate = successDate;
     }

     public Date getSuccessDate(){
         return successDate;
     }

     public void setExceptionDate(Date exceptionDate){
         this.exceptionDate = exceptionDate;
     }

     public Date getExceptionDate(){
         return exceptionDate;
     }

     public void setReverseDate(Date reverseDate){
         this.reverseDate = reverseDate;
     }

     public Date getReverseDate(){
         return reverseDate;
     }

     public void setAux01(String aux01){
         this.aux01 = aux01;
     }

     public String getAux01(){
         return aux01;
     }

     public void setAux02(String aux02){
         this.aux02 = aux02;
     }

     public String getAux02(){
         return aux02;
     }

     public void setAux03(String aux03){
         this.aux03 = aux03;
     }

     public String getAux03(){
         return aux03;
     }

     public void setAux04(String aux04){
         this.aux04 = aux04;
     }

     public String getAux04(){
         return aux04;
     }

     public void setAux05(String aux05){
         this.aux05 = aux05;
     }

     public String getAux05(){
         return aux05;
     }

     }
