package com.jingrui.jrap.cashflow.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "csh_payment")
public class Payment extends BaseDTO {

     public static final String FIELD_PAYMENT_ID = "paymentId";
     public static final String FIELD_PAYMENT_CODE = "paymentCode";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_DOCUMENT_CATEGORY = "documentCategory";
     public static final String FIELD_DOCUMENT_TYPE = "documentType";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_AMOUNT = "amount";
     public static final String FIELD_AMOUNT_PAID = "amountPaid";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_REQUEST_DATE = "requestDate";
     public static final String FIELD_PAYMENT_DATE = "paymentDate";
     public static final String FIELD_LAST_PAY_DATE = "lastPayDate";
     public static final String FIELD_TRANSACTION_CATEGORY = "transactionCategory";
     public static final String FIELD_PAYMENT_METHOD = "paymentMethod";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_CUSTOMER_ID = "customerId";
     public static final String FIELD_APPROVED_DATE = "approvedDate";
     public static final String FIELD_CLOSED_DATE = "closedDate";
     public static final String FIELD_PRINT_FLAG = "printFlag";
     public static final String FIELD_PRINT_DATE = "printDate";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long paymentId;

     @Length(max = 60)
     private String paymentCode; //付款编号

     private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

     @Length(max = 60)
     private String documentCategory; //单据类别

     @Length(max = 60)
     private String documentType; //单据类型

     @Length(max = 60)
     private String status; //付款状态

     private Long amount; //申请金额

     private Long amountPaid; //已付金额

     @Length(max = 200)
     private String description; //备注说明

     private Date requestDate; //申请日期

     private Date paymentDate; //付款日期

     private Date lastPayDate; //最后付款日期

     @Length(max = 60)
     private String transactionCategory; //事务类别

     @Length(max = 60)
     private String paymentMethod; //付款方式

     private Long orderId; //订单ID

     private Long customerId; //客户ID

     private Date approvedDate; //审批日期

     private Date closedDate; //关闭日期

     @Length(max = 1)
     private String printFlag; //打印标志

     private Date printDate; //打印日期

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setPaymentId(Long paymentId){
         this.paymentId = paymentId;
     }

     public Long getPaymentId(){
         return paymentId;
     }

     public void setPaymentCode(String paymentCode){
         this.paymentCode = paymentCode;
     }

     public String getPaymentCode(){
         return paymentCode;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setDocumentCategory(String documentCategory){
         this.documentCategory = documentCategory;
     }

     public String getDocumentCategory(){
         return documentCategory;
     }

     public void setDocumentType(String documentType){
         this.documentType = documentType;
     }

     public String getDocumentType(){
         return documentType;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setAmount(Long amount){
         this.amount = amount;
     }

     public Long getAmount(){
         return amount;
     }

     public void setAmountPaid(Long amountPaid){
         this.amountPaid = amountPaid;
     }

     public Long getAmountPaid(){
         return amountPaid;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setRequestDate(Date requestDate){
         this.requestDate = requestDate;
     }

     public Date getRequestDate(){
         return requestDate;
     }

     public void setPaymentDate(Date paymentDate){
         this.paymentDate = paymentDate;
     }

     public Date getPaymentDate(){
         return paymentDate;
     }

     public void setLastPayDate(Date lastPayDate){
         this.lastPayDate = lastPayDate;
     }

     public Date getLastPayDate(){
         return lastPayDate;
     }

     public void setTransactionCategory(String transactionCategory){
         this.transactionCategory = transactionCategory;
     }

     public String getTransactionCategory(){
         return transactionCategory;
     }

     public void setPaymentMethod(String paymentMethod){
         this.paymentMethod = paymentMethod;
     }

     public String getPaymentMethod(){
         return paymentMethod;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setCustomerId(Long customerId){
         this.customerId = customerId;
     }

     public Long getCustomerId(){
         return customerId;
     }

     public void setApprovedDate(Date approvedDate){
         this.approvedDate = approvedDate;
     }

     public Date getApprovedDate(){
         return approvedDate;
     }

     public void setClosedDate(Date closedDate){
         this.closedDate = closedDate;
     }

     public Date getClosedDate(){
         return closedDate;
     }

     public void setPrintFlag(String printFlag){
         this.printFlag = printFlag;
     }

     public String getPrintFlag(){
         return printFlag;
     }

     public void setPrintDate(Date printDate){
         this.printDate = printDate;
     }

     public Date getPrintDate(){
         return printDate;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
