package com.jingrui.jrap.cashflow.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "csh_transaction")
public class Transaction extends BaseDTO {

     public static final String FIELD_TRANSACTION_ID = "transactionId";
     public static final String FIELD_TRANSACTION_NUM = "transactionNum";
     public static final String FIELD_TRANSACTION_CATEGORY = "transactionCategory";
     public static final String FIELD_TRANSACTION_TYPE = "transactionType";
     public static final String FIELD_TRANSACTION_DATE = "transactionDate";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_TRANSACTION_AMOUNT = "transactionAmount";
     public static final String FIELD_CASHFLOW_AMOUNT = "cashflowAmount";
     public static final String FIELD_INTERNAL_PERIOD_NUM = "internalPeriodNum";
     public static final String FIELD_PERIOD_NAME = "periodName";
     public static final String FIELD_BANK_ACCOUNT_ID = "bankAccountId";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_CUSTOMER_ID = "customerId";
     public static final String FIELD_OPT_ACCOUNT_ID = "optAccountId";
     public static final String FIELD_OPT_ACCOUNT_NUM = "optAccountNum";
     public static final String FIELD_OPT_ACCOUNT_NAME = "optAccountName";
     public static final String FIELD_OPT_BANK_NAME = "optBankName";
     public static final String FIELD_BANK_SLIP_NUM = "bankSlipNum";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_POSTED_FLAG = "postedFlag";
     public static final String FIELD_WRITEOFF_FLAG = "writeoffFlag";
     public static final String FIELD_WRITEOFF_AMOUNT = "writeoffAmount";
     public static final String FIELD_FULL_WRITEOFF_DATE = "fullWriteoffDate";
     public static final String FIELD_REVERSED_FLAG = "reversedFlag";
     public static final String FIELD_REVERSED_DATE = "reversedDate";
     public static final String FIELD_REVERSED_TRANS_ID = "reversedTransId";
     public static final String FIELD_RETURNED_FLAG = "returnedFlag";
     public static final String FIELD_RETURNED_AMOUNT = "returnedAmount";
     public static final String FIELD_RETURNED_DATE = "returnedDate";
     public static final String FIELD_RETURNED_TRANS_ID = "returnedTransId";
     public static final String FIELD_SOURCE_TYPE = "sourceType";
     public static final String FIELD_SOURCE_ID = "sourceId";
     public static final String FIELD_SOURCE_LINE_ID = "sourceLineId";
     public static final String FIELD_JE_METHOD = "jeMethod";
     public static final String FIELD_JE_FLAG = "jeFlag";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long transactionId;

     private Long transactionNum; //交易编号

     @Length(max = 60)
     private String transactionCategory; //交易类别（BUSINESS-经营类，LOAN_REPAYMENT-银行还款，LOAN_WITHDRAW-银行提款）

     @Length(max = 60)
     private String transactionType; //交易类型（RECEIPT-收款，PAYMENT-付款，ADVANCE_RECEIPT-预收款，预付款-PREPAYMENT，TRANSFER_IN-转入，TRANSFER_OUT-转出）

     private Date transactionDate; //交易日期

     private Long companyId; //公司ID

     private Long transactionAmount; //事务金额

     private Long cashflowAmount; //现金流金额

     private Long internalPeriodNum; //内部期间

     @Length(max = 60)
     private String periodName; //期间

     private Long bankAccountId; //本方账户ID

     private Long orderId; //订单ID

     private Long customerId; //客户ID

     private Long optAccountId; //对方账户ID

     @Length(max = 60)
     private String optAccountNum; //对方账号

     @Length(max = 200)
     private String optAccountName; //对方账户

     @Length(max = 200)
     private String optBankName; //对方开户行

     @Length(max = 200)
     private String bankSlipNum; //银行回单

     @Length(max = 200)
     private String description; //备注

     @Length(max = 1)
     private String postedFlag; //过账标志（N/Y）

     @Length(max = 60)
     private String writeoffFlag; //核销标志（ NOT/未核销 ，PARTIAL/部分核销 ， FULL/全部核销 ）

     private Long writeoffAmount; //核销金额

     private Date fullWriteoffDate; //完全核销日

     @Length(max = 1)
     private String reversedFlag; //反冲标志（ N/未反冲 ，W/被反冲，R/反冲事物 ）

     private Date reversedDate; //反冲日期

     private Long reversedTransId; //反冲事务ID

     @Length(max = 60)
     private String returnedFlag; //退款标志（NOT/未退款 ，PARTIAL/部分退款 ， FULL/全部退款 ， RETURN/退款事务）

     private Long returnedAmount; //已退款金额

     private Date returnedDate; //最新退款日期

     private Long returnedTransId; //被退款事务ID

     @Length(max = 60)
     private String sourceType; //来源类型

     private Long sourceId; //来源ID

     private Long sourceLineId; //来源行ID

     @Length(max = 60)
     private String jeMethod; //凭证生成方式（CLEARING/CONSOLIDATION）

     @Length(max = 1)
     private String jeFlag; //凭证标志

     @Length(max = 1)
     private String enabledFlag; //启用标志

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setTransactionId(Long transactionId){
         this.transactionId = transactionId;
     }

     public Long getTransactionId(){
         return transactionId;
     }

     public void setTransactionNum(Long transactionNum){
         this.transactionNum = transactionNum;
     }

     public Long getTransactionNum(){
         return transactionNum;
     }

     public void setTransactionCategory(String transactionCategory){
         this.transactionCategory = transactionCategory;
     }

     public String getTransactionCategory(){
         return transactionCategory;
     }

     public void setTransactionType(String transactionType){
         this.transactionType = transactionType;
     }

     public String getTransactionType(){
         return transactionType;
     }

     public void setTransactionDate(Date transactionDate){
         this.transactionDate = transactionDate;
     }

     public Date getTransactionDate(){
         return transactionDate;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setTransactionAmount(Long transactionAmount){
         this.transactionAmount = transactionAmount;
     }

     public Long getTransactionAmount(){
         return transactionAmount;
     }

     public void setCashflowAmount(Long cashflowAmount){
         this.cashflowAmount = cashflowAmount;
     }

     public Long getCashflowAmount(){
         return cashflowAmount;
     }

     public void setInternalPeriodNum(Long internalPeriodNum){
         this.internalPeriodNum = internalPeriodNum;
     }

     public Long getInternalPeriodNum(){
         return internalPeriodNum;
     }

     public void setPeriodName(String periodName){
         this.periodName = periodName;
     }

     public String getPeriodName(){
         return periodName;
     }

     public void setBankAccountId(Long bankAccountId){
         this.bankAccountId = bankAccountId;
     }

     public Long getBankAccountId(){
         return bankAccountId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setCustomerId(Long customerId){
         this.customerId = customerId;
     }

     public Long getCustomerId(){
         return customerId;
     }

     public void setOptAccountId(Long optAccountId){
         this.optAccountId = optAccountId;
     }

     public Long getOptAccountId(){
         return optAccountId;
     }

     public void setOptAccountNum(String optAccountNum){
         this.optAccountNum = optAccountNum;
     }

     public String getOptAccountNum(){
         return optAccountNum;
     }

     public void setOptAccountName(String optAccountName){
         this.optAccountName = optAccountName;
     }

     public String getOptAccountName(){
         return optAccountName;
     }

     public void setOptBankName(String optBankName){
         this.optBankName = optBankName;
     }

     public String getOptBankName(){
         return optBankName;
     }

     public void setBankSlipNum(String bankSlipNum){
         this.bankSlipNum = bankSlipNum;
     }

     public String getBankSlipNum(){
         return bankSlipNum;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setPostedFlag(String postedFlag){
         this.postedFlag = postedFlag;
     }

     public String getPostedFlag(){
         return postedFlag;
     }

     public void setWriteoffFlag(String writeoffFlag){
         this.writeoffFlag = writeoffFlag;
     }

     public String getWriteoffFlag(){
         return writeoffFlag;
     }

     public void setWriteoffAmount(Long writeoffAmount){
         this.writeoffAmount = writeoffAmount;
     }

     public Long getWriteoffAmount(){
         return writeoffAmount;
     }

     public void setFullWriteoffDate(Date fullWriteoffDate){
         this.fullWriteoffDate = fullWriteoffDate;
     }

     public Date getFullWriteoffDate(){
         return fullWriteoffDate;
     }

     public void setReversedFlag(String reversedFlag){
         this.reversedFlag = reversedFlag;
     }

     public String getReversedFlag(){
         return reversedFlag;
     }

     public void setReversedDate(Date reversedDate){
         this.reversedDate = reversedDate;
     }

     public Date getReversedDate(){
         return reversedDate;
     }

     public void setReversedTransId(Long reversedTransId){
         this.reversedTransId = reversedTransId;
     }

     public Long getReversedTransId(){
         return reversedTransId;
     }

     public void setReturnedFlag(String returnedFlag){
         this.returnedFlag = returnedFlag;
     }

     public String getReturnedFlag(){
         return returnedFlag;
     }

     public void setReturnedAmount(Long returnedAmount){
         this.returnedAmount = returnedAmount;
     }

     public Long getReturnedAmount(){
         return returnedAmount;
     }

     public void setReturnedDate(Date returnedDate){
         this.returnedDate = returnedDate;
     }

     public Date getReturnedDate(){
         return returnedDate;
     }

     public void setReturnedTransId(Long returnedTransId){
         this.returnedTransId = returnedTransId;
     }

     public Long getReturnedTransId(){
         return returnedTransId;
     }

     public void setSourceType(String sourceType){
         this.sourceType = sourceType;
     }

     public String getSourceType(){
         return sourceType;
     }

     public void setSourceId(Long sourceId){
         this.sourceId = sourceId;
     }

     public Long getSourceId(){
         return sourceId;
     }

     public void setSourceLineId(Long sourceLineId){
         this.sourceLineId = sourceLineId;
     }

     public Long getSourceLineId(){
         return sourceLineId;
     }

     public void setJeMethod(String jeMethod){
         this.jeMethod = jeMethod;
     }

     public String getJeMethod(){
         return jeMethod;
     }

     public void setJeFlag(String jeFlag){
         this.jeFlag = jeFlag;
     }

     public String getJeFlag(){
         return jeFlag;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
