package com.jingrui.jrap.cashflow.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "csh_writeoff")
public class Writeoff extends BaseDTO {

     public static final String FIELD_WRITEOFF_ID = "writeoffId";
     public static final String FIELD_WRITEOFF_TYPE = "writeoffType";
     public static final String FIELD_WRITEOFF_DATE = "writeoffDate";
     public static final String FIELD_INTERNAL_PERIOD_NUM = "internalPeriodNum";
     public static final String FIELD_PERIOD_NAME = "periodName";
     public static final String FIELD_TRANSACTION_ID = "transactionId";
     public static final String FIELD_BILL_AMOUNT = "billAmount";
     public static final String FIELD_REVERSED_FLAG = "reversedFlag";
     public static final String FIELD_REVERSED_WRITEOFF_ID = "reversedWriteoffId";
     public static final String FIELD_REVERSED_DATE = "reversedDate";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_CASHFLOW_ID = "cashflowId";
     public static final String FIELD_TIMES = "times";
     public static final String FIELD_CF_TYPE = "cfType";
     public static final String FIELD_WRITEOFF_AMOUNT = "writeoffAmount";
     public static final String FIELD_WRITEOFF_PRINCIPAL = "writeoffPrincipal";
     public static final String FIELD_WRITEOFF_INTEREST = "writeoffInterest";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_SOURCE_TYPE = "sourceType";
     public static final String FIELD_SOURCE_ID = "sourceId";
     public static final String FIELD_SOURCE_LINE_ID = "sourceLineId";
     public static final String FIELD_JE_MOTHED = "jeMothed";
     public static final String FIELD_JE_FLAG = "jeFlag";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long writeoffId;

     @Length(max = 60)
     private String writeoffType; //核销类型

     private Date writeoffDate; //核销日期

     private Long internalPeriodNum; //内部期间

     @Length(max = 60)
     private String periodName; //期间

     private Long transactionId; //现金事务ID

     private Long billAmount; //账单金额

     @Length(max = 1)
     private String reversedFlag; //反冲标志（N 未反冲/W 被反冲/R 反冲交易）

     private Long reversedWriteoffId; //反冲核销ID

     private Date reversedDate; //反冲日期

     private Long orderId; //订单ID

     private Long cashflowId; //现金流ID

     private Long times; //期数

     @Length(max = 60)
     private String cfType; //现金流类型

     private Long writeoffAmount; //核销金额

     private Long writeoffPrincipal; //核销本金

     private Long writeoffInterest; //核销利息

     @Length(max = 200)
     private String description; //摘要

     @Length(max = 60)
     private String sourceType; //来源类型

     private Long sourceId; //来源ID

     private Long sourceLineId; //来源行ID

     @Length(max = 60)
     private String jeMothed; //凭证生成方式（CLEARING/CONSOLIDATION）

     @Length(max = 1)
     private String jeFlag; //凭证标志

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setWriteoffId(Long writeoffId){
         this.writeoffId = writeoffId;
     }

     public Long getWriteoffId(){
         return writeoffId;
     }

     public void setWriteoffType(String writeoffType){
         this.writeoffType = writeoffType;
     }

     public String getWriteoffType(){
         return writeoffType;
     }

     public void setWriteoffDate(Date writeoffDate){
         this.writeoffDate = writeoffDate;
     }

     public Date getWriteoffDate(){
         return writeoffDate;
     }

     public void setInternalPeriodNum(Long internalPeriodNum){
         this.internalPeriodNum = internalPeriodNum;
     }

     public Long getInternalPeriodNum(){
         return internalPeriodNum;
     }

     public void setPeriodName(String periodName){
         this.periodName = periodName;
     }

     public String getPeriodName(){
         return periodName;
     }

     public void setTransactionId(Long transactionId){
         this.transactionId = transactionId;
     }

     public Long getTransactionId(){
         return transactionId;
     }

     public void setBillAmount(Long billAmount){
         this.billAmount = billAmount;
     }

     public Long getBillAmount(){
         return billAmount;
     }

     public void setReversedFlag(String reversedFlag){
         this.reversedFlag = reversedFlag;
     }

     public String getReversedFlag(){
         return reversedFlag;
     }

     public void setReversedWriteoffId(Long reversedWriteoffId){
         this.reversedWriteoffId = reversedWriteoffId;
     }

     public Long getReversedWriteoffId(){
         return reversedWriteoffId;
     }

     public void setReversedDate(Date reversedDate){
         this.reversedDate = reversedDate;
     }

     public Date getReversedDate(){
         return reversedDate;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setCashflowId(Long cashflowId){
         this.cashflowId = cashflowId;
     }

     public Long getCashflowId(){
         return cashflowId;
     }

     public void setTimes(Long times){
         this.times = times;
     }

     public Long getTimes(){
         return times;
     }

     public void setCfType(String cfType){
         this.cfType = cfType;
     }

     public String getCfType(){
         return cfType;
     }

     public void setWriteoffAmount(Long writeoffAmount){
         this.writeoffAmount = writeoffAmount;
     }

     public Long getWriteoffAmount(){
         return writeoffAmount;
     }

     public void setWriteoffPrincipal(Long writeoffPrincipal){
         this.writeoffPrincipal = writeoffPrincipal;
     }

     public Long getWriteoffPrincipal(){
         return writeoffPrincipal;
     }

     public void setWriteoffInterest(Long writeoffInterest){
         this.writeoffInterest = writeoffInterest;
     }

     public Long getWriteoffInterest(){
         return writeoffInterest;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setSourceType(String sourceType){
         this.sourceType = sourceType;
     }

     public String getSourceType(){
         return sourceType;
     }

     public void setSourceId(Long sourceId){
         this.sourceId = sourceId;
     }

     public Long getSourceId(){
         return sourceId;
     }

     public void setSourceLineId(Long sourceLineId){
         this.sourceLineId = sourceLineId;
     }

     public Long getSourceLineId(){
         return sourceLineId;
     }

     public void setJeMothed(String jeMothed){
         this.jeMothed = jeMothed;
     }

     public String getJeMothed(){
         return jeMothed;
     }

     public void setJeFlag(String jeFlag){
         this.jeFlag = jeFlag;
     }

     public String getJeFlag(){
         return jeFlag;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
