package com.jingrui.jrap.product.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;

import javax.persistence.OrderBy;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "pro_business_type")
public class BusinessType extends BaseDTO {

     public static final String FIELD_BUSINESS_TYPE = "businessType";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_CATEGORY = "category";
     public static final String FIELD_DEAL_TYPE = "dealType";
     public static final String FIELD_DEAL_USAGE = "dealUsage";
     public static final String FIELD_CYCLE = "cycle";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";

     @Id
     @NotEmpty
     @Length(max = 60)
     @OrderBy("ASC")
     @Where
     private String businessType; //主键，供其他表做外键

     @Length(max = 200)
     private String description; //描述

     @Length(max = 60)
     private String category; //种类

     @Length(max = 60)
     private String dealType; //经营类型

     @Length(max = 60)
     private String dealUsage; //经营用途

     @Length(max = 60)
     private String cycle; //周期

     @Length(max = 1)
     private String enabledFlag; //启用标识


     public void setBusinessType(String businessType){
         this.businessType = businessType;
     }

     public String getBusinessType(){
         return businessType;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setCategory(String category){
         this.category = category;
     }

     public String getCategory(){
         return category;
     }

     public void setDealType(String dealType){
         this.dealType = dealType;
     }

     public String getDealType(){
         return dealType;
     }

     public void setDealUsage(String dealUsage){
         this.dealUsage = dealUsage;
     }

     public String getDealUsage(){
         return dealUsage;
     }

     public void setCycle(String cycle){
         this.cycle = cycle;
     }

     public String getCycle(){
         return cycle;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     }
