package com.jingrui.jrap.product.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "pro_cashflow_type")
public class CashflowType extends BaseDTO {

     public static final String FIELD_CF_TYPE = "cfType";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_CF_DIRECTION = "cfDirection";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_SYS_FLAG = "sysFlag";
     public static final String FIELD_WRITE_OFF_ORDER = "writeOffOrder";
     public static final String FIELD_CALC_PENALTY = "calcPenalty";
     public static final String FIELD_BILLING_DESC = "billingDesc";
     public static final String FIELD_VAT_RATE = "vatRate";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @NotEmpty
     @Length(max = 60)
     private String cfType; //主键，供其他表做外键

     @Length(max = 100)
     private String description; //描述

     @Length(max = 60)
     private String cfDirection; //现金流方向

     private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

     @Length(max = 1)
     private String sysFlag; //系统标识

     private Long writeOffOrder; //核销顺序

     @Length(max = 1)
     private String calcPenalty; //计算罚息

     @Length(max = 100)
     private String billingDesc; //开票描述

     private Long vatRate; //税率

     @Length(max = 1)
     private String enabledFlag; //启用标识

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setCfType(String cfType){
         this.cfType = cfType;
     }

     public String getCfType(){
         return cfType;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setCfDirection(String cfDirection){
         this.cfDirection = cfDirection;
     }

     public String getCfDirection(){
         return cfDirection;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setSysFlag(String sysFlag){
         this.sysFlag = sysFlag;
     }

     public String getSysFlag(){
         return sysFlag;
     }

     public void setWriteOffOrder(Long writeOffOrder){
         this.writeOffOrder = writeOffOrder;
     }

     public Long getWriteOffOrder(){
         return writeOffOrder;
     }

     public void setCalcPenalty(String calcPenalty){
         this.calcPenalty = calcPenalty;
     }

     public String getCalcPenalty(){
         return calcPenalty;
     }

     public void setBillingDesc(String billingDesc){
         this.billingDesc = billingDesc;
     }

     public String getBillingDesc(){
         return billingDesc;
     }

     public void setVatRate(Long vatRate){
         this.vatRate = vatRate;
     }

     public Long getVatRate(){
         return vatRate;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
