package com.jingrui.jrap.product.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;

import javax.persistence.OrderBy;
import javax.persistence.Table;

import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "pro_document_category")
public class DocumentCategory extends BaseDTO {

    public static final String FIELD_DOCUMENT_CATEGORY = "documentCategory";
    public static final String FIELD_DECRIPTION = "decription";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";

    @Id
    @NotEmpty
    @Length(max = 60)
    @OrderBy("ASC")
    @Where
    private String documentCategory;

    @Length(max = 200)
    private String decription; //描述

    @Length(max = 1)
    private String enabledFlag; //启用标识

    public void setDocumentCategory(String documentCategory) {
        this.documentCategory = documentCategory;
    }

    public String getDocumentCategory() {
        return documentCategory;
    }

    public void setDecription(String decription) {
        this.decription = decription;
    }

    public String getDecription() {
        return decription;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }
}
