package com.jingrui.jrap.product.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;

import javax.persistence.OrderBy;
import javax.persistence.Table;

import com.jingrui.jrap.system.dto.BaseDTO;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "pro_document_type")
public class DocumentType extends BaseDTO {

    public static final String FIELD_DOCUMENT_TYPE = "documentType";
    public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_DOCUMENT_CATEGORY = "documentCategory";
    public static final String FIELD_BUSINESS_TYPE = "businessType";
    public static final String FIELD_CODING_RULE = "codingRule";
    public static final String FIELD_WORKFLOW_CODE = "workflowCode";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";

    @Id
    @NotEmpty
    @Length(max = 60)
    @OrderBy("ASC")
    @Where
    private String documentType; //主键，供其他表做外键

    @Length(max = 200)
    private String description; //描述

    @Length(max = 60)
    private String documentCategory; //单据类别

    @Length(max = 60)
    @Where
    private String businessType; //业务类型

    @Length(max = 60)
    private String codingRule; //编码规则

    @Length(max = 60)
    private String workflowCode; //工作流编码

    @Length(max = 1)
    private String enabledFlag; //启用标识

    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    public String getDocumentType() {
        return documentType;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setDocumentCategory(String documentCategory) {
        this.documentCategory = documentCategory;
    }

    public String getDocumentCategory() {
        return documentCategory;
    }

    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    public String getBusinessType() {
        return businessType;
    }

    public void setCodingRule(String codingRule) {
        this.codingRule = codingRule;
    }

    public String getCodingRule() {
        return codingRule;
    }

    public void setWorkflowCode(String workflowCode) {
        this.workflowCode = workflowCode;
    }

    public String getWorkflowCode() {
        return workflowCode;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }

}
