package com.jingrui.jrap.product.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "afd_good")
public class Good extends BaseDTO {

     public static final String FIELD_GOOD_ID = "goodId";
     public static final String FIELD_GOOD_NAME = "goodName";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_DOCUMENT_CATEGORY = "documentCategory";
     public static final String FIELD_DOCUMENT_TYPE = "documentType";
     public static final String FIELD_PRODUCT_CODE = "productCode";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_UNIT_PRICE = "unitPrice";
     public static final String FIELD_TOTAL_NUMBER = "totalNumber";
     public static final String FIELD_TOTAL_AMOUNT = "totalAmount";
     public static final String FIELD_SURPLUS_AMOUNT = "surplusAmount";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";
     public static final String FIELD_START_DATE = "startDate";
     public static final String FIELD_END_DATE = "endDate";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long goodId;

     @Length(max = 200)
     private String goodName; //商品名称

     private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

     @NotEmpty
     @Length(max = 60)
     private String documentCategory; //单据类别

     @NotEmpty
     @Length(max = 60)
     private String documentType; //单据类型

     @Length(max = 60)
     private String productCode; //产品编码

     @Length(max = 2147483647)
     private String description; //商品描述

     private Long unitPrice; //商品单价

     private Long totalNumber; //商品数量

     private Long totalAmount; //商品总额度

     private Long surplusAmount; //剩余额度

     @Length(max = 1)
     private String enabledFlag; //启用标识

     private Date startDate; //有效期从

     private Date endDate; //有效期至

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setGoodId(Long goodId){
         this.goodId = goodId;
     }

     public Long getGoodId(){
         return goodId;
     }

     public void setGoodName(String goodName){
         this.goodName = goodName;
     }

     public String getGoodName(){
         return goodName;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setDocumentCategory(String documentCategory){
         this.documentCategory = documentCategory;
     }

     public String getDocumentCategory(){
         return documentCategory;
     }

     public void setDocumentType(String documentType){
         this.documentType = documentType;
     }

     public String getDocumentType(){
         return documentType;
     }

     public void setProductCode(String productCode){
         this.productCode = productCode;
     }

     public String getProductCode(){
         return productCode;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setUnitPrice(Long unitPrice){
         this.unitPrice = unitPrice;
     }

     public Long getUnitPrice(){
         return unitPrice;
     }

     public void setTotalNumber(Long totalNumber){
         this.totalNumber = totalNumber;
     }

     public Long getTotalNumber(){
         return totalNumber;
     }

     public void setTotalAmount(Long totalAmount){
         this.totalAmount = totalAmount;
     }

     public Long getTotalAmount(){
         return totalAmount;
     }

     public void setSurplusAmount(Long surplusAmount){
         this.surplusAmount = surplusAmount;
     }

     public Long getSurplusAmount(){
         return surplusAmount;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setStartDate(Date startDate){
         this.startDate = startDate;
     }

     public Date getStartDate(){
         return startDate;
     }

     public void setEndDate(Date endDate){
         this.endDate = endDate;
     }

     public Date getEndDate(){
         return endDate;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
