package com.jingrui.jrap.product.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import javax.persistence.*;

import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.JoinTable;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;

import com.jingrui.jrap.mybatis.common.query.JoinColumn;
import com.jingrui.jrap.mybatis.common.query.JoinOn;
import com.jingrui.jrap.mybatis.common.query.JoinTable;
import javax.persistence.criteria.JoinType;

import com.jingrui.jrap.system.dto.BaseDTO;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "pro_product")
public class Product extends BaseDTO {
    public static final String FIELD_PRODUCT_CODE = "productCode";
    public static final String FIELD_PRODUCT_NAME = "productName";
    public static final String FIELD_PRODUCT_TYPE = "productType";
    public static final String FIELD_PRODUCT_CLASS = "productClass";
    public static final String FIELD_DECRIPTION = "decription";
    public static final String FIELD_BUSINESS_TYPE = "businessType";
    public static final String FIELD_LINE_CODE = "lineCode";
    public static final String FIELD_MODEL_ID = "modelId";
    public static final String FIELD_MODEL = "model";
    public static final String FIELD_COMPANY_ID = "companyId";
    public static final String FIELD_CALCULATE = "calculate";
    public static final String FIELD_RATE_TYPE = "rateType";
    public static final String FIELD_VERSION = "version";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    public static final String FIELD_START_DATE = "startDate";
    public static final String FIELD_END_DATE = "endDate";

    @Id
    @NotEmpty
    @Length(max = 60)
    @OrderBy("ASC")
    @Where
    private String productCode; //产品编码

    @Length(max = 200)
    @Where
    private String productName; //产品名称

    @Length(max = 60)
    @Where
    private String productType; //产品类型

    @Length(max = 60)
    @Where
    private String productClass; //产品属性

    @Length(max = 200)
    private String decription; //产品描述

    @Length(max = 60)
    @Where
    private String businessType; //业务类型

    @Length(max = 60)
    @Where
    private String lineCode; //产品线

    @Where
    @JoinTable(name = "itemModelJoin", target = ItemModel.class, type = JoinType.LEFT, on = {@JoinOn(joinField = ItemModel.FIELD_MODEL_ID)})
    private Long modelId; //租赁物模型ID

    @Transient
    @JoinColumn(joinName = "itemModelJoin", field = ItemModel.FIELD_MODEL)
    private String model;

    @Where
    private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

    @Length(max = 60)
    private String calculate; //计算器

    @Length(max = 60)
    private String rateType; //利率类型

    @Where
    private int version; //版本

    @Length(max = 1)
    private String enabledFlag; //启用标识

    private Date startDate; //有效期从

    private Date endDate; //有效期至

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getProductCode() {
        return productCode;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }

    public String getProductType() {
        return productType;
    }

    public void setProductClass(String productClass) {
        this.productClass = productClass;
    }

    public String getProductClass() {
        return productClass;
    }

    public void setDecription(String decription) {
        this.decription = decription;
    }

    public String getDecription() {
        return decription;
    }

    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    public String getBusinessType() {
        return businessType;
    }

    public void setLineCode(String lineCode) {
        this.lineCode = lineCode;
    }

    public String getLineCode() {
        return lineCode;
    }

    public void setModelId(Long modelId) {
        this.modelId = modelId;
    }

    public Long getModelId() {
        return modelId;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCalculate(String calculate) {
        this.calculate = calculate;
    }

    public String getCalculate() {
        return calculate;
    }

    public void setRateType(String rateType) {
        this.rateType = rateType;
    }

    public String getRateType() {
        return rateType;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getEndDate() {
        return endDate;
    }

}
