package com.jingrui.jrap.activiti.exception.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.UnsupportedEncodingException;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "act_exception")
public class ActiviException {
    @Id
    @GeneratedValue(generator = BaseDTO.GENERATOR_TYPE)
    private Long id;

    @NotEmpty
    private String procId;

    @JsonIgnore
    private byte[] message;

    @Transient
    private String messStr;

    private Date duedate;

    @Transient
    private String procDefName;

    public ActiviException() {
    }

    public ActiviException(String procId, String messStr, Date duedate) {
        this.procId = procId;
        this.duedate = duedate;
        byte[] mesb = null;
        try {
            mesb = messStr.getBytes("utf-8");
        } catch (UnsupportedEncodingException e1) {
            e1.printStackTrace();
        }
        message = mesb;
    }


    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setProcId(String procId) {
        this.procId = procId;
    }

    public String getProcId() {
        return procId;
    }

    public byte[] getMessage() {
        return message;
    }

    public void setMessage(byte[] message) {
        this.message = message;
    }

    public Date getDuedate() {
        return duedate;
    }

    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }

    public String getProcDefName() {
        return procDefName;
    }

    public void setProcDefName(String procDefName) {
        this.procDefName = procDefName;
    }

    public String getMessStr() {
        if (message != null) {
            try {
                messStr = new String(message, "utf-8");
            } catch (UnsupportedEncodingException e) {
                e.printStackTrace();
            }
        }
        return messStr;
    }

    public void setMessStr(String messStr) {
        this.messStr = messStr;
    }
}
