package com.jingrui.jrap.code.rule.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.*;

import com.jingrui.jrap.core.annotation.Children;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Comparison;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;

import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "sys_code_rules_header")
public class CodeRulesHeader extends BaseDTO {

    public static final String FIELD_HEADER_ID = "headerId";
    public static final String FIELD_RULE_CODE = "ruleCode";
    public static final String FIELD_RULE_NAME = "ruleName";
    public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_ENABLE_FLAG = "enableFlag";

    @Id
    @GeneratedValue
    @Where
    private Long headerId;

    @NotEmpty
    @Length(max = 50)
    @Where
    @OrderBy("ASC")
    private String ruleCode; // 编码规则CODE

    @Length(max = 50)
    @Where
    private String ruleName; // 名称

    @Length(max = 255)
    private String description; // 描述

    @Length(max = 5)
    private String enableFlag; // 启用标志

    @Transient
    @Children
    private List<CodeRulesLine> lines;

    public List<CodeRulesLine> getLines() {
        return lines;
    }

    public void setLines(List<CodeRulesLine> lines) {
        this.lines = lines;
    }

    public void setHeaderId(Long headerId) {
        this.headerId = headerId;
    }

    public Long getHeaderId() {
        return headerId;
    }

    public void setRuleCode(String ruleCode) {
        this.ruleCode = ruleCode;
    }

    public String getRuleCode() {
        return ruleCode;
    }

    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    public String getRuleName() {
        return ruleName;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    public String getEnableFlag() {
        return enableFlag;
    }

}
