import com.google.common.collect.Lists;
import com.jingrui.jrap.db.util.DbType;
import com.jingrui.jrap.flexfield.dto.FlexRuleSet;
import com.jingrui.jrap.mybatis.util.StringUtil;
import com.jingrui.jrap.system.dto.ParameterConfig;
import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.select.Select;
import org.junit.Test;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.nio.ByteBuffer;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
import java.util.Arrays;
import java.util.List;

/**
 * @author njq.niu@jingrui.com
 */
public class TestUtil {

    static final int BUFFER_SIZE = 1024;

    public static void main(String[] args) throws IOException, JSQLParserException {
        String sql = "SELECT hou.unit_id           AS organization_id,\n" +
                "       hou.unit_code         AS organization_code,\n" +
                "       hou.name              AS organization_name,\n" +
                "       hou.parent_id         AS org_id,\n" +
                "       phou.unit_code        AS org_code,\n" +
                "       phou.name             AS org_name,\n" +
                "       fcb.company_id        AS company_id,\n" +
                "       fcb.company_full_name AS companyname,\n" +
                "       hou.description       AS remark\n" +
                "  FROM ((select * from hr_org_unit_b hou LEFT JOIN hr_org_unit_b phou ON((hou.parent_id = phou.unit_id))) LEFT JOIN\n" +
                "        fnd_company_b fcb ON((phou.company_id = fcb.company_id)))\n" +
                " WHERE (hou.unit_type = 'ORGANIZATION')\n";
        Select select = (Select) CCJSqlParserUtil.parse(sql);
        select.getSelectBody();
    }

    @Test
    public void DbTypeTest() {
        String[] dbUrl = {
                "jdbc:mysql://192.168.0.1:3306/yourDBName",
                "jdbc:oracle:thin:@192.168.0.1:1521:yourDBName",
                "jdbc:sqlserver://192.168.0.1:1433;databasename=yourDBName",
                "jdbc:postgresql://127.0.0.1:5432/yourDBName"
        };

        for (String str : dbUrl){
            String [] sub = str.split(":");
            DbType dbType = DbType.getDbType(sub[1]);
            System.out.println(dbType);
        }
    }
    @Test
    public void generateProperty() throws ClassNotFoundException {
        //Class clazz = Class.forName("com.jingrui.jrap.system.dto.ParameterConfig");
        Class clazz = FlexRuleSet.class;
        Field[] fields = clazz.getDeclaredFields();
        for (Field field : fields) {
            if (!Modifier.isStatic(field.getModifiers())) {
                String fieldName = field.getName();
                String propertyName = StringUtil.camelhumpToUnderline(fieldName);
                System.out.println("public static final String FIELD_" + propertyName + " = \"" + fieldName + "\";");
            }

        }
    }


    private void test1() throws IOException {
        File file = new File("d:\\dump.dat");
        FileInputStream in = new FileInputStream(file);
        FileChannel channel = in.getChannel();
        ByteBuffer buff = ByteBuffer.allocate(1024);

        long begin = System.currentTimeMillis();
        while (channel.read(buff) != -1) {
            buff.flip();
            buff.clear();
        }
        long end = System.currentTimeMillis();
        System.out.println("time is:" + (end - begin));
    }

    private void test2() throws IOException {
        File file = new File("d:\\dump.dat");
        FileInputStream in = new FileInputStream(file);
        FileChannel channel = in.getChannel();
        MappedByteBuffer buff = channel.map(FileChannel.MapMode.READ_ONLY, 0, channel.size());

        byte[] b = new byte[1024];
        int len = (int) file.length();

        long begin = System.currentTimeMillis();

        for (int offset = 0; offset < len; offset += 1024) {

            if (len - offset > BUFFER_SIZE) {
                buff.get(b);
            } else {
                buff.get(new byte[len - offset]);
            }
        }

        long end = System.currentTimeMillis();
        System.out.println("time is:" + (end - begin));
    }


    @Test
    public void createPrompt() {
        Class clazz = ParameterConfig.class;
        List<String> xls = getXlsPromptList();

        Arrays.stream(clazz.getDeclaredFields())
                .filter((field) -> !field.getName().contains("_") && !field.getName().equalsIgnoreCase("serialVersionUID"))
                .filter((field) -> !xls.contains(clazz.getSimpleName().toLowerCase() + "." + field.getName().toLowerCase()))
                .forEach((v) -> {
                    System.out.println(clazz.getSimpleName().toLowerCase() + "." + v.getName().toLowerCase());
                    System.out.println(clazz.getSimpleName().toLowerCase() + "." + v.getName().toLowerCase());
                });
    }


    public List<String> getXlsPromptList() {
        String xls = "lov.placeholder\n" +
                "lov.placeholder\n" +
                "lov.dropdown\n" +
                "lov.dropdown\n" +
                "lov.code\n" +
                "lov.code\n" +
                "lov.description\n" +
                "lov.description\n" +
                "lov.height\n" +
                "lov.height\n" +
                "lov.lovid\n" +
                "lov.lovid\n" +
                "lov.lovitems\n" +
                "lov.lovitems\n" +
                "lov.customsql\n" +
                "lov.customsql\n" +
                "lov.sqltype\n" +
                "ov.sqltype\n" +
                "lov.sqlid\n" +
                "lov.sqlid\n" +
                "lov.textfield\n" +
                "lov.textfield\n" +
                "lov.title\n" +
                "lov.title\n" +
                "lov.valuefield\n" +
                "lov.valuefield\n" +
                "lov.width\n" +
                "lov.width\n" +
                "lov.querycolumns\n" +
                "lov.columns\n" +
                "lovitem.display\n" +
                "lovitem.display\n" +
                "lovitem.name\n" +
                "lovitem.name\n" +
                "lovitem.gridfieldwidth\n" +
                "lovitem.gridfieldwidth\n" +
                "lovitem.conditionfield\n" +
                "lovitem.conditionfield\n" +
                "lovitem.newline\n" +
                "lovitem.newline\n" +
                "lovitem.type\n" +
                "lovitem.type\n" +
                "lovitem.opts\n" +
                "lovitem.opts\n" +
                "lovitem.dropdown\n" +
                "lovitem.dropdown\n" +
                "lovitem.gridcolumn\n" +
                "lovitem.gridcolumn\n" +
                "lov.delayload\n" +
                "lov.delayload\n" +
                "lov.needqueryparam\n" +
                "lov.needqueryparam\n" +
                "lovitem.conditionfieldwidth\n" +
                "lovitem.conditionfieldwidth\n" +
                "lovitem.conditionfieldsequence\n" +
                "lovitem.conditionfieldsequence\n" +
                "lovitem.conditionfieldname\n" +
                "lovitem.conditionfieldname\n" +
                "lovitem.conditionfieldselectcode\n" +
                "lovitem.conditionfieldselectcode\n" +
                "lovitem.conditionfieldlovcode\n" +
                "lovitem.conditionfieldlovcode\n" +
                "lovitem.gridfieldsequence\n" +
                "lovitem.gridfieldsequence\n" +
                "lovitem.gridcolumnalign\n" +
                "lovitem.gridcolumnalign\n" +
                "lov.autocompletefield\n" +
                "lov.autocompletefield\n" +
                "lov.canpopup\n" +
                "lov.canpopup\n" +
                "lov.editable\n" +
                "lov.editable\n" +
                "lovitem.field_type\n" +
                "lovitem.field_type\n" +
                "lovitem.ds_type\n" +
                "lovitem.ds_type\n" +
                "lovitem.ds_type.url\n" +
                "lovitem.ds_type.url\n" +
                "lovitem.ds_type.code\n" +
                "lovitem.ds_type.code\n" +
                "user.username\n" +
                "user.username\n" +
                "user.password\n" +
                "user.password\n" +
                "user.email\n" +
                "user.email\n" +
                "user.phone\n" +
                "user.phone\n" +
                "role.rolecode\n" +
                "role.rolecode\n" +
                "role.rolename\n" +
                "role.rolename\n" +
                "role.roledescription\n" +
                "role.roledescription\n" +
                "user.allocationrole\n" +
                "user.allocationrole\n" +
                "code.code\n" +
                "code.code\n" +
                "code.description\n" +
                "code.description\n" +
                "jrap.action\n" +
                "jrap.action\n" +
                "codevalue.value\n" +
                "codevalue.value\n" +
                "codevalue.meaning\n" +
                "codevalue.meaning\n" +
                "codevalue.description\n" +
                "codevalue.description\n" +
                "profile.profilename\n" +
                "profile.profilename\n" +
                "profile.description\n" +
                "profile.description\n" +
                "language.langcode\n" +
                "language.langcode\n" +
                "language.baselang\n" +
                "language.baselang\n" +
                "language.description\n" +
                "language.description\n" +
                "jobdetaildto.jobname\n" +
                "jobdetaildto.jobname\n" +
                "jobdetaildto.jobgroup\n" +
                "jobdetaildto.jobgroup\n" +
                "jobdetaildto.jobclassname\n" +
                "jobdetaildto.jobclassname\n" +
                "jobdetaildto.description\n" +
                "jobdetaildto.description\n" +
                "jobrunninginfodto.previousfiretime\n" +
                "jobrunninginfodto.previousfiretime\n" +
                "jobrunninginfodto.scheduledfiretime\n" +
                "jobrunninginfodto.scheduledfiretime\n" +
                "jobrunninginfodto.nextfiretime\n" +
                "jobrunninginfodto.nextfiretime\n" +
                "jobrunninginfodto.firetime\n" +
                "jobrunninginfodto.firetime\n" +
                "jobrunninginfodto.jobstatus\n" +
                "jobrunninginfodto.jobstatus\n" +
                "jobrunninginfodto.executionsummary\n" +
                "jobrunninginfodto.executionsummary\n" +
                "jrap.pause\n" +
                "jrap.pause\n" +
                "jrap.resume\n" +
                "jrap.resume\n" +
                "job.newcronjob\n" +
                "job.newcronjob\n" +
                "job.newsimplejob\n" +
                "job.newsimplejob\n" +
                "prompt.promptcode\n" +
                "prompt.promptcode\n" +
                "prompt.sourcelang\n" +
                "prompt.sourcelang\n" +
                "prompt.description\n" +
                "prompt.description\n" +
                "function.modulecode\n" +
                "function.modulecode\n" +
                "function.functioncode\n" +
                "funciton.functioncode\n" +
                "function.functionname\n" +
                "function.functionname\n" +
                "function.parentfunctionid\n" +
                "function.parentfunctionid\n" +
                "function.functionicon\n" +
                "function.functionicon\n" +
                "function.functionsequence\n" +
                "function.functionsequence\n" +
                "function.functiondescription\n" +
                "function.functiondescription\n" +
                "function.mainpage\n" +
                "function.mainpage\n" +
                "function.functionresource\n" +
                "function.functionresource\n" +
                "function.resourceallocation\n" +
                "function.resourceallocation\n" +
                "resource.url\n" +
                "resource.url\n" +
                "resource.type\n" +
                "resource.type\n" +
                "resource.name\n" +
                "resource.name\n" +
                "resource.loginrequire\n" +
                "resource.loginrequire\n" +
                "resource.accesscheck\n" +
                "resource.accesscheck\n" +
                "resource.description\n" +
                "resource.description\n" +
                "resource.resourceitem\n" +
                "resource.resourceitem\n" +
                "resource.itemallocation\n" +
                "resource.itemallocation\n" +
                "resourceitem.itemid\n" +
                "resourceitem.itemid\n" +
                "resourceitem.itemname\n" +
                "resourceitem.itemname\n" +
                "resourceitem.description\n" +
                "resourceitem.description\n" +
                "resourceitem.resource\n" +
                "resourceitem.resource\n" +
                "jrap.expand\n" +
                "jrap.expand\n" +
                "jrap.collapse\n" +
                "jrap.collapse\n" +
                "jrap.comment\n" +
                "jrap.comment\n" +
                "messageemailconfig.configcode\n" +
                "messageemailconfig.configcode\n" +
                "messageemailconfig.introduction\n" +
                "messageemailconfig.introduction\n" +
                "messageemailconfig.host\n" +
                "messageemailconfig.host\n" +
                "messageemailconfig.port\n" +
                "messageemailconfig.port\n" +
                "messageemailconfig.trytimes\n" +
                "messageemailconfig.trytimes\n" +
                "messageemailconfig.usewhitelist\n" +
                "messageemailconfig.usewhitelist\n" +
                "messageemailconfig.username\n" +
                "messageemailconfig.username\n" +
                "messageemailconfig.password\n" +
                "messageemailconfig.password\n" +
                "messageemailconfig.accountcode\n" +
                "messageemailconfig.accountcode\n" +
                "messageemailconfig.account\n" +
                "messageemailconfig.account\n" +
                "messageemailconfig.whitelist\n" +
                "messageemailconfig.whitelist\n" +
                "messageemailconfig.address\n" +
                "messageemailconfig.address\n" +
                "messagetemplate.templatecode\n" +
                "messagetemplate.templatecode\n" +
                "messagetemplate.name\n" +
                "messagetemplate.name\n" +
                "messagetemplate.prioritylevel\n" +
                "messagetemplate.prioritylevel\n" +
                "messagetemplate.subject\n" +
                "messagetemplate.subject\n" +
                "messagetemplate.content\n" +
                "messagetemplate.content\n" +
                "message.subject\n" +
                "message.subject\n" +
                "message.content\n" +
                "message.content\n" +
                "message.receivers\n" +
                "message.receivers\n" +
                "user.info\n" +
                "user.info\n" +
                "user.status\n" +
                "user.status\n" +
                "user.updatepassword\n" +
                "user.updatepassword\n" +
                "user.current_password\n" +
                "user.current_password\n" +
                "user.new_password\n" +
                "user.new_password\n" +
                "user.again_new_password\n" +
                "user.again_new_password\n" +
                "preference.timezone\n" +
                "preference.timezone\n" +
                "profilevalue.levelid\n" +
                "profilevalue.levelid\n" +
                "profilevalue.levelvalue\n" +
                "profilevalue.levelvalue\n" +
                "profilevalue.profilevalue\n" +
                "profilevalue.profilevalue\n" +
                "attachcategory.categorytype\n" +
                "attachcategory.categorytype\n" +
                "attachcategory.categorytype.folder\n" +
                "attachcategory.categorytype.folder\n" +
                "attachcategory.categorytype.filefolder\n" +
                "attachcategory.categorytype.filefolder\n" +
                "attachcategory.categoryname\n" +
                "attachcategory.categoryname\n" +
                "attachcategory.categoryname.help\n" +
                "attachcategory.categoryname.help\n" +
                "attachcategory.categorypath\n" +
                "attachcategory.categorypath\n" +
                "attachcategory.categorypath.help\n" +
                "attachcategory.categorypath.help\n" +
                "attachcategory.description\n" +
                "attachcategory.description\n" +
                "attachcategory.allowedfiletype\n" +
                "attachcategory.allowedfiletype\n" +
                "attachcategory.allowedfiletype.help\n" +
                "attachcategory.allowedfiletype.help\n" +
                "attachcategory.allowedfilesize\n" +
                "attachcategory.allowedfilesize\n" +
                "attachcategory.allowedfilesize.help\n" +
                "attachcategory.allowedfilesize.help\n" +
                "attachcategory.sourcetype\n" +
                "attachcategory.sourcetype\n" +
                "attachcategory.sourcetype.help\n" +
                "attachcategory.sourcetype.help\n" +
                "attachcategory.isunique\n" +
                "attachcategory.isunique\n" +
                "attachcategory.statusname\n" +
                "attachcategory.statusname\n" +
                "attachcategory.statusname.normal\n" +
                "attachcategory.statusname.normal\n" +
                "attachcategory.statusname.archived\n" +
                "attachcategory.statusname.archived\n" +
                "attachcategory.archive\n" +
                "attachcategory.archive\n" +
                "sysfile.filename\n" +
                "sysfile.filename\n" +
                "sysfile.filesize\n" +
                "sysfile.filesize\n" +
                "sysfile.uploaddate\n" +
                "sysfile.uploaddate\n" +
                "sysfile.filetype\n" +
                "sysfile.filetype\n" +
                "jrap.view\n" +
                "jrap.view\n" +
                "sysfile.upload\n" +
                "sysfile.upload\n" +
                "jrap.tip.info\n" +
                "jrap.tip.info\n" +
                "jrap.tip.success\n" +
                "jrap.tip.success\n" +
                "function.resourcechoose\n" +
                "function.resourcechoose\n" +
                "jrap.tip.delete_confirm\n" +
                "jrap.tip.delete_confirm\n" +
                "jrap.confirm\n" +
                "jrap.confirm\n" +
                "role.changerole\n" +
                "role.changerole\n" +
                "user.verificode\n" +
                "user.verificode\n" +
                "account.common.logintip\n" +
                "account.common.logintip\n" +
                "jrap.confirm_exit\n" +
                "jrap.confirm_exit\n" +
                "rolefunction.select_role\n" +
                "rolefunction.select_role\n" +
                "jrap.login\n" +
                "jrap.login\n" +
                "jrap.multilanguage_editor\n" +
                "jrap.multilanguage_editor\n" +
                "error.login.verification_code_error\n" +
                "error.login.verification_code_error\n" +
                "error.login.name_password_not_match\n" +
                "error.login.name_password_not_match\n" +
                "job.attributename\n" +
                "job.attributename\n" +
                "job.attributevalue\n" +
                "job.attributevalue\n" +
                "crontriggerdto.cronexpression\n" +
                "crontriggerdto.cronexpression\n" +
                "triggerdto.starttime\n" +
                "triggerdto.starttime\n" +
                "triggerdto.endtime\n" +
                "triggerdto.endtime\n" +
                "error.user.two_password_not_match\n" +
                "error.user.two_password_not_match\n" +
                "error.user.accout_locked\n" +
                "error.user.accout_locked\n" +
                "error.user.account_not_active\n" +
                "error.user.account_not_active\n" +
                "error.user.account_expired\n" +
                "error.user.account_expired\n" +
                "user.startactivedate\n" +
                "user.startactivedate\n" +
                "user.endactivedate\n" +
                "user.endactivedate\n" +
                "error.record_not_exists_or_version_not_match\n" +
                "error.record_not_exists_or_version_not_match\n" +
                "sys.config.configuration\n" +
                "sys.config.configuration\n" +
                "sys.config.style\n" +
                "sys.config.style\n" +
                "sys.config.safety\n" +
                "sys.config.safety\n" +
                "sys.config.other\n" +
                "sys.config.other\n" +
                "sys.config.system_title\n" +
                "sys.config.system_title\n" +
                "sys.config.systemlogo\n" +
                "sys.config.systemlogo\n" +
                "sys.config.favicon\n" +
                "sys.config.favicon\n" +
                "sys.config.captcha\n" +
                "sys.config.captcha\n" +
                "sys.config.default_password\n" +
                "sys.config.default_password\n" +
                "sys.config.systemlogo.desciption\n" +
                "sys.config.systemlogo.desciption\n" +
                "sys.config.favicon.desciption\n" +
                "sys.config.favicon.desciption\n" +
                "jrap.enableflag\n" +
                "jrap.enableflag\n" +
                "role.isexpired\n" +
                "role.isexpired\n" +
                "employee.employeelevelcode\n" +
                "employee.employeelevelcode\n" +
                "preference.locale\n" +
                "preference.locale\n" +
                "preference.timezone.description\n" +
                "preference.timezone.description\n" +
                "preference.locale.description\n" +
                "preference.locale.description\n" +
                "preference.theme\n" +
                "preference.theme\n" +
                "position.name\n" +
                "position.name\n" +
                "position.description\n" +
                "position.description\n" +
                "position.positioncode\n" +
                "position.positioncode\n" +
                "position.parentpositionname\n" +
                "position.parentpositionname\n" +
                "hrorgunit.name\n" +
                "hrorgunit.name\n" +
                "hrorgunit.description\n" +
                "hrorgunit.description\n" +
                "hrorgunit.unitcode\n" +
                "hrorgunit.unitcode\n" +
                "hrorgunit.parentname\n" +
                "hrorgunit.parentname\n" +
                "jrap.tip.noselect\n" +
                "jrap.tip.noselect\n" +
                "employee.employeecode\n" +
                "employee.employeecode\n" +
                "employee.name\n" +
                "employee.name\n" +
                "employee.positionallocation\n" +
                "employee.positionallocation\n" +
                "employee.borndate\n" +
                "employee.borndate\n" +
                "employee.mobile\n" +
                "employee.mobile\n" +
                "employee.joindate\n" +
                "employee.joindate\n" +
                "employee.gender\n" +
                "employee.gender\n" +
                "employee.status\n" +
                "employee.status\n" +
                "employee.enabledflag\n" +
                "employee.enabledflag\n" +
                "employee.certificateid\n" +
                "employee.certificateid\n" +
                "employee.companyinfo\n" +
                "employee.companyinfo\n" +
                "employee.otherinfo\n" +
                "employee.otherinfo\n" +
                "employee.personalinfo\n" +
                "employee.personalinfo\n" +
                "employee.ismainposition\n" +
                "employee.ismainposition\n" +
                "position.selectposition\n" +
                "position.selectposition\n" +
                "hrorgunit.unittreelist\n" +
                "hrorgunit.unittreelist\n" +
                "hrorgunit.unitinfo\n" +
                "hrorgunit.unitinfo\n" +
                "sys.config.password_policy\n" +
                "sys.config.password_policy\n" +
                "sys.config.password_min_length\n" +
                "sys.config.password_min_length\n" +
                "sys.config.password_complexity\n" +
                "sys.config.password_complexity\n" +
                "error.user.update_password\n" +
                "error.user.update_password\n" +
                "error.user.current_password_notempty\n" +
                "error.user.current_password_notempty\n" +
                "error.user.new_password_notempty\n" +
                "error.user.new_password_notempty\n" +
                "error.user.new_password_again\n" +
                "error.user.new_password_again\n" +
                "sys.config.password_invalid_time\n" +
                "sys.config.password_invalid_time\n" +
                "user.passwordlength.insufficient\n" +
                "user.passwordlength.insufficient\n" +
                "user.password.discord\n" +
                "user.password.discord\n" +
                "company.companycode\n" +
                "company.companycode\n" +
                "company.companyshortname\n" +
                "company.companyshortname\n" +
                "company.companyfullname\n" +
                "company.companyfullname\n" +
                "company.companytype\n" +
                "company.companytype\n" +
                "company.address\n" +
                "company.address\n" +
                "company.companylevelid\n" +
                "company.companylevelid\n" +
                "company.positionname\n" +
                "company.positionname\n" +
                "company.parentcompanyname\n" +
                "company.parentcompanyname\n" +
                "company.zipcode\n" +
                "company.zipcode\n" +
                "company.phone\n" +
                "company.phone\n" +
                "company.contactperson\n" +
                "company.contactperson\n" +
                "company.fax\n" +
                "company.fax\n" +
                "sys.config.select_file\n" +
                "sys.config.select_file\n" +
                "sys.config.upload_file\n" +
                "sys.config.upload_file\n" +
                "error.user.email\n" +
                "error.user.email\n" +
                "error.user.phone\n" +
                "error.user.phone\n" +
                "jrap.quicknavigation\n" +
                "jrap.quicknavigation\n" +
                "error.account_no_role\n" +
                "error.account_no_role\n" +
                "sys.config.password_invalid_describe\n" +
                "sys.config.password_invalid_describe\n" +
                "sys.dashboard.dashboardtitle\n" +
                "sys.dashboard.dashboardtitle\n" +
                "sys.dashboard.dashboardcode\n" +
                "sys.dashboard.dashboardcode\n" +
                "sys.dashboard.dashboardmainpage\n" +
                "sys.dashboard.dashboardmainpage\n" +
                "sys.dashboard.dashboarddescription\n" +
                "sys.dashboard.dashboarddescription\n" +
                "job.infodetail.jobinfo\n" +
                "job.infodetail.jobinfo\n" +
                "job.infodetail.notification\n" +
                "job.infodetail.notification\n" +
                "job.infodetail.enable_notification\n" +
                "job.infodetail.enable_notification\n" +
                "job.infodetail.email_address\n" +
                "job.infodetail.email_address\n" +
                "job.jobdetail\n" +
                "job.jobdetail\n" +
                "simpletriggerdto.repeatinterval\n" +
                "simpletriggerdto.repeatinterval\n" +
                "simpletriggerdto.repeatcount\n" +
                "simpletriggerdto.repeatcount\n" +
                "generator.projectpath\n" +
                "generator.projectpath\n" +
                "generator.parentpackagepath\n" +
                "generator.parentpackagepath\n" +
                "generator.packagepath\n" +
                "generator.packagepath\n" +
                "generator.choosetable\n" +
                "generator.choosetable\n" +
                "generator.filetype\n" +
                "generator.filetype\n" +
                "generator.filename\n" +
                "generator.filename\n" +
                "generator.iscreate\n" +
                "generator.iscreate\n" +
                "generator.iscover\n" +
                "generator.iscover\n" +
                "generator.htmlmodel\n" +
                "generator.htmlmodel\n" +
                "generator.submit\n" +
                "generator.submit\n" +
                "generator.needchoosetable\n" +
                "generator.needchoosetable\n" +
                "hrorgunit.companyname\n" +
                "hrorgunit.companyname\n" +
                "jrap.copy\n" +
                "jrap.copy\n" +
                "jrap.tip.selectrow\n" +
                "jrap.tip.selectrow\n" +
                "jrap.tip.selectrows\n" +
                "jrap.tip.selectrows\n" +
                "msg.warning.upload.file.empty\n" +
                "msg.warning.upload.file.empty\n" +
                "msg.warning.upload.sourcetype.empty\n" +
                "msg.warning.upload.sourcetype.empty\n" +
                "msg.warning.upload.folder.notfound\n" +
                "msg.warning.upload.folder.notfound\n" +
                "jrap.type_error\n" +
                "jrap.type_error\n" +
                "jrap.database_error\n" +
                "jrap.database_error\n" +
                "jrap.mesg_unique\n" +
                "jrap.mesg_unique\n" +
                "jrap.download\n" +
                "jrap.download\n" +
                "jrap.mesg_delete\n" +
                "jrap.mesg_delete\n" +
                "message.sendflag\n" +
                "message.sendflag\n" +
                "message.templatetest\n" +
                "message.templatetest\n" +
                "message.customtest\n" +
                "message.customtest\n" +
                "message.rensend\n" +
                "message.rensend\n" +
                "messagetemplate.creationdate\n" +
                "messagetemplate.creationdate\n" +
                "messagetemplate.lastupdatedate\n" +
                "messagetemplate.lastupdatedate\n" +
                "jrap.upload_success\n" +
                "jrap.upload_success\n" +
                "codevalue.orderseq\n" +
                "codevalue.orderseq\n" +
                "sys.login.safety\n" +
                "sys.login.safety\n" +
                "sys.config.rolemerge\n" +
                "sys.config.rolemerge\n" +
                "sys.config.user_role_merge.describe\n" +
                "sys.config.user_role_merge.describe\n" +
                "sys.config.default_target_url\n" +
                "sys.config.default_target_url\n" +
                "sys.config.default_target_url.describe\n" +
                "sys.config.default_target_url.describe\n" +
                "interface.systemname\n" +
                "interface.systemname\n" +
                "interface.interfacetype\n" +
                "interface.interfacetype\n" +
                "interface.systemurl\n" +
                "interface.systemurl\n" +
                "interface.requestmethod\n" +
                "interface.requestmethod\n" +
                "interface.requestformat\n" +
                "interface.requestformat\n" +
                "interface.mapperclass\n" +
                "interface.mapperclass\n" +
                "interface.namespace\n" +
                "interface.namespace\n" +
                "interface.enableflag\n" +
                "interface.enableflag\n" +
                "interface.authflag\n" +
                "interface.authflag\n" +
                "interface.requestcontenttype\n" +
                "interface.requestcontenttype\n" +
                "interface.requestaccept\n" +
                "interface.requestaccept\n" +
                "interface.checkusername\n" +
                "interface.checkusername\n" +
                "interface.checkpassword\n" +
                "interface.checkpassword\n" +
                "interface.soapheader\n" +
                "interface.soapheader\n" +
                "interface.soaptail\n" +
                "interface.soaptail\n" +
                "interface.headeredit\n" +
                "interface.headeredit\n" +
                "interface.lineedit\n" +
                "interface.lineedit\n" +
                "interface.line.interfacecode\n" +
                "interface.line.interfacecode\n" +
                "interface.systemcode\n" +
                "interface.systemcode\n" +
                "interface.line.interfacename\n" +
                "interface.line.interfacename\n" +
                "interface.lind.interfaceurl\n" +
                "interface.lind.interfaceurl\n" +
                "interface.invoke.inbound\n" +
                "interface.invoke.inbound\n" +
                "interface.invoke.outbound\n" +
                "interface.invoke.outbound\n" +
                "interface.invoke.requeststatus\n" +
                "interface.invoke.requeststatus\n" +
                "interface.invoke.requesttime\n" +
                "interface.invoke.requesttime\n" +
                "interface.invoke.requestip\n" +
                "interface.invoke.requestip\n" +
                "interface.invoke.responsetime\n" +
                "interface.invoke.responsetime\n" +
                "interface.invoke.detail\n" +
                "interface.invoke.detail\n" +
                "interface.invoke.requestparameter\n" +
                "interface.invoke.requestparameter\n" +
                "interface.invoke.responsecode\n" +
                "interface.invoke.responsecode\n" +
                "interface.invoke.requestbodyprm\n" +
                "interface.invoke.requestbodyprm\n" +
                "interface.invoke.responsecontent\n" +
                "interface.invoke.responsecontent\n" +
                "interface.invoke.stacktrace\n" +
                "interface.invoke.stacktrace\n" +
                "interface.invoke.userreferer\n" +
                "interface.invoke.userreferer\n" +
                "interface.invoke.useragent\n" +
                "interface.invoke.useragent\n" +
                "interface.invoke.statsenddate\n" +
                "interface.invoke.statsenddate\n" +
                "jrap.error.uniqueexception\n" +
                "jrap.error.uniqueexception\n" +
                "jrap.error.nullexception\n" +
                "jrap.error.nullexception\n" +
                "jrap.exportexcel\n" +
                "jrap.exportexcel\n" +
                "interface.invoke.endsenddate\n" +
                "interface.invoke.endsenddate\n" +
                "jrap.invoke.apiname.interfacetranspond\n" +
                "jrap.invoke.apiname.interfacetranspond\n" +
                "resourcecustomization.sequence\n" +
                "resourcecustomization.sequence\n" +
                "resourcecustomization.personalization\n" +
                "resourcecustomization.personalization\n" +
                "sys.config.resetpassword\n" +
                "sys.config.resetpassword\n" +
                "sys.config.resetpassword.describe\n" +
                "sys.config.resetpassword.describe\n" +
                "employee.createnewuser\n" +
                "employee.createnewuser\n" +
                "lovitem.conditionfieldlabelwidth\n" +
                "lovitem.conditionfieldlabelwidth\n" +
                "lov.tip.querycolumnstip\n" +
                "lov.tip.querycolumnstip\n" +
                "jrap.refresh\n" +
                "jrap.refresh\n" +
                "employee.certificatetype\n" +
                "employee.certificatetype\n" +
                "employee.effectivestartdate\n" +
                "employee.effectivestartdate\n" +
                "employee.effectiveenddate\n" +
                "employee.effectiveenddate\n" +
                "remodel.name\n" +
                "remodel.name\n" +
                "remodel.key\n" +
                "remodel.key\n" +
                "interface.accesstokenurl\n" +
                "interface.accesstokenurl\n" +
                "interface.clientid\n" +
                "interface.clientid\n" +
                "interface.clientsecret\n" +
                "interface.clientsecret\n" +
                "interface.authtype\n" +
                "interface.authtype\n" +
                "interface.oauthscope\n" +
                "interface.oauthscope\n" +
                "interface.granttype\n" +
                "interface.granttype\n" +
                "business.rule.code\n" +
                "business.rule.code\n" +
                "business.rule.description\n" +
                "business.rule.description\n" +
                "oauth2clientdetails.clientid\n" +
                "oauth2clientdetails.clientid\n" +
                "oauth2clientdetails.clientsecret\n" +
                "oauth2clientdetails.clientsecret\n" +
                "oauth2clientdetails.granttypes\n" +
                "oauth2clientdetails.granttypes\n" +
                "oauth2clientdetails.resourceids\n" +
                "oauth2clientdetails.resourceids\n" +
                "oauth2clientdetails.authorities\n" +
                "oauth2clientdetails.authorities\n" +
                "oauth2clientdetails.autoapprove\n" +
                "oauth2clientdetails.autoapprove\n" +
                "oauth2clientdetails.accesstokenvalidity\n" +
                "oauth2clientdetails.accesstokenvalidity\n" +
                "oauth2clientdetails.scope\n" +
                "oauth2clientdetails.scope\n" +
                "oauth2clientdetails.refreshtokenvalidity\n" +
                "oauth2clientdetails.refreshtokenvalidity\n" +
                "oauth2clientdetails.redirecturi\n" +
                "oauth2clientdetails.redirecturi\n" +
                "oauth2clientdetails.additionalinformation\n" +
                "oauth2clientdetails.additionalinformation\n" +
                "hrorgunit.unitcategory\n" +
                "hrorgunit.unitcategory\n" +
                "hrorgunit.unittype\n" +
                "hrorgunit.unittype\n" +
                "code.parentcodeid\n" +
                "code.parentcodeid\n" +
                "codevalue.parentcodevalueid\n" +
                "codevalue.parentcodevalueid\n" +
                "tokenlogs.tokenaccessstatus\n" +
                "tokenlogs.tokenaccessstatus\n" +
                "tokenlogs.userid\n" +
                "tokenlogs.userid\n" +
                "tokenlogs.tokenaccesstime\n" +
                "tokenlogs.tokenaccesstime\n" +
                "tokenlogs.tokenexpirestime\n" +
                "tokenlogs.tokenexpirestime\n" +
                "tokenlogs.tokenaccesstype\n" +
                "tokenlogs.tokenaccesstype\n" +
                "tokenlogs.tokenaccessvalid\n" +
                "tokenlogs.tokenaccessvalid\n" +
                "tokenlogs.tokenaccessinvalid\n" +
                "tokenlogs.tokenaccessinvalid\n" +
                "tokenlogs.tokenaccessaction\n" +
                "tokenlogs.tokenaccessaction\n" +
                "tokenlogs.tokenaccessrevoke\n" +
                "tokenlogs.tokenaccessrevoke\n" +
                "tokenlogs.tokenaccessall\n" +
                "tokenlogs.tokenaccessall\n" +
                "preference.deliverstartdate\n" +
                "preference.deliverstartdate\n" +
                "preference.deliverenddate\n" +
                "preference.deliverenddate\n" +
                "preference.autodeliver\n" +
                "preference.autodeliver\n" +
                "preference.deliverstartdate.description\n" +
                "preference.deliverstartdate.description\n" +
                "preference.deliverenddate.description\n" +
                "preference.deliverenddate.description\n" +
                "preference.autodeliver.description\n" +
                "preference.autodeliver.description\n" +
                "sys.config.prohibit_repeat_login\n" +
                "sys.config.prohibit_repeat_login\n" +
                "sys.config.prohibit_repeat_login.describe\n" +
                "sys.config.prohibit_repeat_login.describe\n" +
                "jrap.repeat_login\n" +
                "jrap.repeat_login\n" +
                "flexmodel.modelcode\n" +
                "flexmodel.modelcode\n" +
                "flexmodel.modelname\n" +
                "flexmodel.modelname\n" +
                "flexmodel.modeltable\n" +
                "flexmodel.modeltable\n" +
                "flexmodelcolumn.columnname\n" +
                "flexmodelcolumn.columnname\n" +
                "flexmodelcolumn.description\n" +
                "flexmodelcolumn.description\n" +
                "flexruleset.rulesetcode\n" +
                "flexruleset.rulesetcode\n" +
                "flexruleset.description\n" +
                "flexruleset.description\n" +
                "flexruleset.modelid\n" +
                "flexruleset.modelid\n" +
                "flexrule.rulecode\n" +
                "flexrule.rulecode\n" +
                "flexrule.description\n" +
                "flexrule.description\n" +
                "flexrulefield.modelcolumnid\n" +
                "flexrulefield.modelcolumnid\n" +
                "flexrulefield.config\n" +
                "flexrulefield.config\n" +
                "flexrulefield.fieldsequence\n" +
                "flexrulefield.fieldsequence\n" +
                "flexrulefield.fieldcolumnnumber\n" +
                "flexrulefield.fieldcolumnnumber\n" +
                "flexrulefield.fieldcolumnwidth\n" +
                "flexrulefield.fieldcolumnwidth\n" +
                "flexrulefield.readableflag\n" +
                "flexrulefield.readableflag\n" +
                "flexrulefield.requiredflag\n" +
                "flexrulefield.requiredflag\n" +
                "flexruledetail.fieldname\n" +
                "flexruledetail.fieldname\n" +
                "flexruledetail.filetype\n" +
                "flexruledetail.filetype\n" +
                "flexruledetail.fieldvalue\n" +
                "flexruledetail.fieldvalue\n" +
                "flex.ruledetail\n" +
                "flex.ruledetail\n" +
                "flex.rulefield\n" +
                "flex.rulefield\n" +
                "flexfield.columnwidth\n" +
                "flexfield.columnwidth\n" +
                "flexfield.labelwidth\n" +
                "flexfield.labelwidth\n" +
                "flexfield.labelname\n" +
                "flexfield.labelname\n" +
                "flex.precision\n" +
                "flex.precision\n" +
                "flex.range\n" +
                "flex.range\n" +
                "flex.hastime\n" +
                "flex.hastime\n" +
                "jrap.upload.file.type.mismatch\n" +
                "jrap.upload.file.type.mismatch\n" +
                "jrap.upload.file.size.limit.exceeded\n" +
                "jrap.upload.file.size.limit.exceeded\n" +
                "jrap.upload.success\n" +
                "jrap.upload.success\n" +
                "jrap.upload.error\n" +
                "jrap.upload.error\n" +
                "msg.warning.dto.attachcategory.sourcetype.repeaterror\n" +
                "msg.warning.dto.attachcategory.sourcetype.repeaterror\n" +
                "msg.error.token_not_exists\n" +
                "msg.error.token_not_exists\n" +
                "msg.error.token_check_failed\n" +
                "msg.error.token_check_failed\n" +
                "msg.warning.download.file.error\n" +
                "msg.warning.download.file.error\n" +
                "wfl.security.error.need_assignee_or_admin\n" +
                "wfl.security.error.need_assignee_or_admin\n" +
                "jrap.back\n" +
                "jrap.back\n" +
                "error.user.password_length_insufficient\n" +
                "error.user.password_length_insufficient\n" +
                "error.user.password_format_error_digits_and_letters\n" +
                "error.user.password_format_error_digits_and_letters\n" +
                "password_format_error_digits_and_case_letters\n" +
                "password_format_error_digits_and_case_letters\n" +
                "error.system.not_allowed_same_with_old_password\n" +
                "error.system.not_allowed_same_with_old_password\n" +
                "userlogin.userid\n" +
                "userlogin.userid\n" +
                "userlogin.logintime\n" +
                "userlogin.logintime\n" +
                "userlogin.ip\n" +
                "userlogin.ip\n" +
                "userlogin.referer\n" +
                "userlogin.referer\n" +
                "userlogin.useragent\n" +
                "userlogin.useragent\n" +
                "userdashboard.userid\n" +
                "userdashboard.userid\n" +
                "userdashboard.dashboardid\n" +
                "userdashboard.dashboardid\n" +
                "userdashboard.dashboardcode\n" +
                "userdashboard.dashboardcode\n" +
                "userdashboard.dashboardtitle\n" +
                "userdashboard.dashboardtitle\n" +
                "userdashboard.dashboardurl\n" +
                "userdashboard.dashboardurl\n" +
                "userdashboard.dashboardsequence\n" +
                "userdashboard.dashboardsequence\n" +
                "syspreferences.preferences\n" +
                "syspreferences.preferences\n" +
                "syspreferences.preferencesvalue\n" +
                "syspreferences.preferencesvalue\n" +
                "syspreferences.userid\n" +
                "syspreferences.userid\n" +
                "sysconfig.configcode\n" +
                "sysconfig.configcode\n" +
                "sysconfig.configvalue\n" +
                "sysconfig.configvalue\n" +
                "sysconfig.category\n" +
                "sysconfig.category\n" +
                "shortcut.userid\n" +
                "shortcut.userid\n" +
                "shortcut.functioncode\n" +
                "shortcut.functioncode\n" +
                "shortcut.functionname\n" +
                "shortcut.functionname\n" +
                "shortcut.url\n" +
                "shortcut.url\n" +
                "shortcut.functionicon\n" +
                "shortcut.functionicon\n" +
                "prompt.lang\n" +
                "prompt.lang\n" +
                "profilevalue.profileid\n" +
                "profilevalue.profileid\n" +
                "profilevalue.levelname\n" +
                "profilevalue.levelname\n" +
                "profile.profilevalues\n" +
                "profile.profilevalues\n" +
                "lovitem.lovid\n" +
                "lovitem.lovid\n" +
                "lovitem.gridfieldname\n" +
                "lovitem.gridfieldname\n" +
                "lovitem.gridfieldalign\n" +
                "lovitem.gridfieldalign\n" +
                "lovitem.autocompletefield\n" +
                "lovitem.autocompletefield\n" +
                "lovitem.isautocomplete\n" +
                "lovitem.isautocomplete\n" +
                "lovitem.gridfield\n" +
                "lovitem.gridfield\n" +
                "lovitem.conditionfieldtype\n" +
                "lovitem.conditionfieldtype\n" +
                "lovitem.conditionfieldtextfield\n" +
                "lovitem.conditionfieldtextfield\n" +
                "lovitem.conditionfieldnewline\n" +
                "lovitem.conditionfieldnewline\n" +
                "lovitem.conditionfieldselecturl\n" +
                "lovitem.conditionfieldselecturl\n" +
                "lovitem.conditionfieldselectvf\n" +
                "lovitem.conditionfieldselectvf\n" +
                "lovitem.conditionfieldselecttf\n" +
                "lovitem.conditionfieldselecttf\n" +
                "lov.customurl\n" +
                "lov.customurl\n" +
                "lov.editableflag\n" +
                "lov.editableflag\n" +
                "dashboard.dashboardcode\n" +
                "dashboard.dashboardcode\n" +
                "dashboard.description\n" +
                "dashboard.description\n" +
                "dashboard.title\n" +
                "dashboard.title\n" +
                "dashboard.resourceid\n" +
                "dashboard.resourceid\n" +
                "dashboard.resourcename\n" +
                "dashboard.resourcename\n" +
                "dashboard.url\n" +
                "dashboard.url\n" +
                "codevalue.codeid\n" +
                "codevalue.codeid\n" +
                "codevalue.tag\n" +
                "codevalue.tag\n" +
                "codevalue.enabledflag\n" +
                "codevalue.enabledflag\n" +
                "codevalue.parentcodevaluemeaning\n" +
                "codevalue.parentcodevaluemeaning\n" +
                "code.codevalues\n" +
                "code.codevalues\n" +
                "code.type\n" +
                "code.type\n" +
                "code.enabledflag\n" +
                "code.enabledflag\n" +
                "code.parentcodedescription\n" +
                "code.parentcodedescription\n" +
                "message.messagetype\n" +
                "message.messagetype\n" +
                "message.messagehost\n" +
                "message.messagehost\n" +
                "message.messagefrom\n" +
                "message.messagefrom\n" +
                "message.prioritylevel\n" +
                "message.prioritylevel\n" +
                "message.messagesource\n" +
                "message.messagesource\n" +
                "message.creationdate\n" +
                "message.creationdate\n" +
                "message.lastupdatedate\n" +
                "message.lastupdatedate\n" +
                "messageaccount.description\n" +
                "messageaccount.description\n" +
                "messageaccount.accounttype\n" +
                "messageaccount.accounttype\n" +
                "messageaccount.accountcode\n" +
                "messageaccount.accountcode\n" +
                "messageaccount.username\n" +
                "messageaccount.username\n" +
                "messageaccount.password\n" +
                "messageaccount.password\n" +
                "messageattachment.fileid\n" +
                "messageattachment.fileid\n" +
                "messageattachment.messageid\n" +
                "messageattachment.messageid\n" +
                "messageemailaccount.configid\n" +
                "messageemailaccount.configid\n" +
                "messageemailaccount.accountcode\n" +
                "messageemailaccount.accountcode\n" +
                "messageemailaccount.username\n" +
                "messageemailaccount.username\n" +
                "messageemailaccount.password\n" +
                "messageemailaccount.password\n" +
                "messageemailaccount.description\n" +
                "messageemailaccount.description\n" +
                "messageemailconfig.description\n" +
                "messageemailconfig.description\n" +
                "messageemailconfig.emailaccounts\n" +
                "messageemailconfig.emailaccounts\n" +
                "messageemailconfig.whitelists\n" +
                "messageemailconfig.whitelists\n" +
                "messageemailwhitelist.description\n" +
                "messageemailwhitelist.description\n" +
                "messageemailwhitelist.address\n" +
                "messageemailwhitelist.address\n" +
                "messageemailwhitelist.configid\n" +
                "messageemailwhitelist.configid\n" +
                "messagereceiver.messageaddress\n" +
                "messagereceiver.messageaddress\n" +
                "messagereceiver.messageid\n" +
                "messagereceiver.messageid\n" +
                "messagereceiver.messagetype\n" +
                "messagereceiver.messagetype\n" +
                "messagetemplate.accountid\n" +
                "messagetemplate.accountid\n" +
                "messagetemplate.description\n" +
                "messagetemplate.description\n" +
                "messagetemplate.templatetype\n" +
                "messagetemplate.templatetype\n" +
                "messagetemplate.meaning\n" +
                "messagetemplate.meaning\n" +
                "messagetransaction.messageid\n" +
                "messagetransaction.messageid\n" +
                "messagetransaction.transactionstatus\n" +
                "messagetransaction.transactionstatus\n" +
                "messagetransaction.transactionmessage\n" +
                "messagetransaction.transactionmessage\n" +
                "hapinterfaceoutbound.interfacename\n" +
                "hapinterfaceoutbound.interfacename\n" +
                "hapinterfaceoutbound.interfaceurl\n" +
                "hapinterfaceoutbound.interfaceurl\n" +
                "hapinterfaceoutbound.requesttime\n" +
                "hapinterfaceoutbound.requesttime\n" +
                "hapinterfaceoutbound.requestparameter\n" +
                "hapinterfaceoutbound.requestparameter\n" +
                "hapinterfaceoutbound.responsecontent\n" +
                "hapinterfaceoutbound.responsecontent\n" +
                "hapinterfaceoutbound.responsecode\n" +
                "hapinterfaceoutbound.responsecode\n" +
                "hapinterfaceoutbound.stacktrace\n" +
                "hapinterfaceoutbound.stacktrace\n" +
                "hapinterfaceoutbound.responsetime\n" +
                "hapinterfaceoutbound.responsetime\n" +
                "hapinterfaceoutbound.requeststatus\n" +
                "hapinterfaceoutbound.requeststatus\n" +
                "hapinterfaceoutbound.page\n" +
                "hapinterfaceoutbound.page\n" +
                "hapinterfaceoutbound.pagesize\n" +
                "hapinterfaceoutbound.pagesize\n" +
                "hapinterfaceoutbound.startdate\n" +
                "hapinterfaceoutbound.startdate\n" +
                "hapinterfaceoutbound.enddate\n" +
                "hapinterfaceoutbound.enddate\n" +
                "hapinterfaceline.headerid\n" +
                "hapinterfaceline.headerid\n" +
                "hapinterfaceline.linecode\n" +
                "hapinterfaceline.linecode\n" +
                "hapinterfaceline.ifturl\n" +
                "hapinterfaceline.ifturl\n" +
                "hapinterfaceline.enableflag\n" +
                "hapinterfaceline.enableflag\n" +
                "hapinterfaceline.linename\n" +
                "hapinterfaceline.linename\n" +
                "hapinterfaceline.linedescription\n" +
                "hapinterfaceline.linedescription\n" +
                "hapinterfaceline.lang\n" +
                "hapinterfaceline.lang\n" +
                "hapinterfaceinbound.interfacename\n" +
                "hapinterfaceinbound.interfacename\n" +
                "hapinterfaceinbound.interfaceurl\n" +
                "hapinterfaceinbound.interfaceurl\n" +
                "hapinterfaceinbound.requesttime\n" +
                "hapinterfaceinbound.requesttime\n" +
                "hapinterfaceinbound.requestheaderparameter\n" +
                "hapinterfaceinbound.requestheaderparameter\n" +
                "hapinterfaceinbound.requestbodyparameter\n" +
                "hapinterfaceinbound.requestbodyparameter\n" +
                "hapinterfaceinbound.responsecontent\n" +
                "hapinterfaceinbound.responsecontent\n" +
                "hapinterfaceinbound.stacktrace\n" +
                "hapinterfaceinbound.stacktrace\n" +
                "hapinterfaceinbound.ip\n" +
                "hapinterfaceinbound.ip\n" +
                "hapinterfaceinbound.referer\n" +
                "hapinterfaceinbound.referer\n" +
                "hapinterfaceinbound.useragent\n" +
                "hapinterfaceinbound.useragent\n" +
                "hapinterfaceinbound.responsetime\n" +
                "hapinterfaceinbound.responsetime\n" +
                "hapinterfaceinbound.requestmethod\n" +
                "hapinterfaceinbound.requestmethod\n" +
                "hapinterfaceinbound.requeststatus\n" +
                "hapinterfaceinbound.requeststatus\n" +
                "hapinterfaceinbound.page\n" +
                "hapinterfaceinbound.page\n" +
                "hapinterfaceinbound.pagesize\n" +
                "hapinterfaceinbound.pagesize\n" +
                "hapinterfaceinbound.startdate\n" +
                "hapinterfaceinbound.startdate\n" +
                "hapinterfaceinbound.enddate\n" +
                "hapinterfaceinbound.enddate\n" +
                "hapinterfaceheader.interfacecode\n" +
                "hapinterfaceheader.interfacecode\n" +
                "hapinterfaceheader.interfacetype\n" +
                "hapinterfaceheader.interfacetype\n" +
                "hapinterfaceheader.bodyheader\n" +
                "hapinterfaceheader.bodyheader\n" +
                "hapinterfaceheader.bodytail\n" +
                "hapinterfaceheader.bodytail\n" +
                "hapinterfaceheader.namespace\n" +
                "hapinterfaceheader.namespace\n" +
                "hapinterfaceheader.domainurl\n" +
                "hapinterfaceheader.domainurl\n" +
                "hapinterfaceheader.requestmethod\n" +
                "hapinterfaceheader.requestmethod\n" +
                "hapinterfaceheader.requestformat\n" +
                "hapinterfaceheader.requestformat\n" +
                "hapinterfaceheader.requestcontenttype\n" +
                "hapinterfaceheader.requestcontenttype\n" +
                "hapinterfaceheader.requestaccept\n" +
                "hapinterfaceheader.requestaccept\n" +
                "hapinterfaceheader.authflag\n" +
                "hapinterfaceheader.authflag\n" +
                "hapinterfaceheader.authusername\n" +
                "hapinterfaceheader.authusername\n" +
                "hapinterfaceheader.authpassword\n" +
                "hapinterfaceheader.authpassword\n" +
                "hapinterfaceheader.enableflag\n" +
                "hapinterfaceheader.enableflag\n" +
                "hapinterfaceheader.authtype\n" +
                "hapinterfaceheader.authtype\n" +
                "hapinterfaceheader.authurl\n" +
                "hapinterfaceheader.authurl\n" +
                "hapinterfaceheader.accesstokenurl\n" +
                "hapinterfaceheader.accesstokenurl\n" +
                "hapinterfaceheader.clientid\n" +
                "hapinterfaceheader.clientid\n" +
                "hapinterfaceheader.clientsecret\n" +
                "hapinterfaceheader.clientsecret\n" +
                "hapinterfaceheader.scope\n" +
                "hapinterfaceheader.scope\n" +
                "hapinterfaceheader.granttype\n" +
                "hapinterfaceheader.granttype\n" +
                "hapinterfaceheader.mapperclass\n" +
                "hapinterfaceheader.mapperclass\n" +
                "hapinterfaceheader.lang\n" +
                "hapinterfaceheader.lang\n" +
                "hapinterfaceheader.name\n" +
                "hapinterfaceheader.name\n" +
                "hapinterfaceheader.description\n" +
                "hapinterfaceheader.description\n" +
                "hapinterfaceheader.systemtype\n" +
                "hapinterfaceheader.systemtype\n" +
                "hapinterfaceheader.soapaction\n" +
                "hapinterfaceheader.soapaction\n" +
                "hapinterfaceheader.lineid\n" +
                "hapinterfaceheader.lineid\n" +
                "hapinterfaceheader.linecode\n" +
                "hapinterfaceheader.linecode\n" +
                "hapinterfaceheader.ifturl\n" +
                "hapinterfaceheader.ifturl\n" +
                "hapinterfaceheader.linelist\n" +
                "hapinterfaceheader.linelist\n" +
                "position.unitid\n" +
                "position.unitid\n" +
                "position.unitname\n" +
                "position.unitname\n" +
                "position.parentpositionid\n" +
                "position.parentpositionid\n" +
                "hrorgunit.parentid\n" +
                "hrorgunit.parentid\n" +
                "hrorgunit.managerposition\n" +
                "hrorgunit.managerposition\n" +
                "hrorgunit.companyid\n" +
                "hrorgunit.companyid\n" +
                "hrorgunit.enabledflag\n" +
                "hrorgunit.enabledflag\n" +
                "hrorgunit.positionname\n" +
                "hrorgunit.positionname\n" +
                "hrorgunit.unitcategoryname\n" +
                "hrorgunit.unitcategoryname\n" +
                "hrorgunit.unittypename\n" +
                "hrorgunit.unittypename\n" +
                "employeeassign.employeeid\n" +
                "employeeassign.employeeid\n" +
                "employeeassign.positionid\n" +
                "employeeassign.positionid\n" +
                "employeeassign.positionname\n" +
                "employeeassign.positionname\n" +
                "employeeassign.unitname\n" +
                "employeeassign.unitname\n" +
                "employeeassign.primarypositionflag\n" +
                "employeeassign.primarypositionflag\n" +
                "employeeassign.enabledflag\n" +
                "employeeassign.enabledflag\n" +
                "employee.email\n" +
                "employee.email\n" +
                "employee.mobil\n" +
                "employee.mobil\n" +
                "employee.statusname\n" +
                "employee.statusname\n" +
                "employee.unitid\n" +
                "employee.unitid\n" +
                "employee.positionid\n" +
                "employee.positionid\n" +
                "employee.unitname\n" +
                "employee.unitname\n" +
                "employee.positionname\n" +
                "employee.positionname\n" +
                "roleresourceitem.rsiid\n" +
                "roleresourceitem.rsiid\n" +
                "roleresourceitem.roleid\n" +
                "roleresourceitem.roleid\n" +
                "rolefunction.functionid\n" +
                "rolefunction.functionid\n" +
                "rolefunction.roleid\n" +
                "rolefunction.roleid\n" +
                "resourceitem.ownerresourceid\n" +
                "resourceitem.ownerresourceid\n" +
                "resourceitem.targetresourceid\n" +
                "resourceitem.targetresourceid\n" +
                "resourceitem.targetresourcename\n" +
                "resourceitem.targetresourcename\n" +
                "resourceitem.itemtype\n" +
                "resourceitem.itemtype\n" +
                "functionresource.functionid\n" +
                "functionresource.functionid\n" +
                "functionresource.resourceid\n" +
                "functionresource.resourceid\n" +
                "function.lang\n" +
                "function.lang\n" +
                "function.parentfunctionname\n" +
                "function.parentfunctionname\n" +
                "function.resourcename\n" +
                "function.resourcename\n" +
                "function.resourceid\n" +
                "function.resourceid\n" +
                "function.resources\n" +
                "function.resources\n" +
                "function.type\n" +
                "function.type\n" +
                "company.parentcompanyid\n" +
                "company.parentcompanyid\n" +
                "company.chiefpositionid\n" +
                "company.chiefpositionid\n" +
                "company.startdateactive\n" +
                "company.startdateactive\n" +
                "company.enddateactive\n" +
                "company.enddateactive\n" +
                "flexruleset.enableflag\n" +
                "flexruleset.enableflag\n" +
                "flexruleset.modelname\n" +
                "flexruleset.modelname\n" +
                "flexrulefield.ruleid\n" +
                "flexrulefield.ruleid\n" +
                "flexrulefield.fieldtype\n" +
                "flexrulefield.fieldtype\n" +
                "flexrulefield.columnname\n" +
                "flexrulefield.columnname\n" +
                "flexruledetail.ruleid\n" +
                "flexruledetail.ruleid\n" +
                "flexruledetail.fieldtype\n" +
                "flexruledetail.fieldtype\n" +
                "flexrule.rulesetid\n" +
                "flexrule.rulesetid\n" +
                "flexrule.enableflag\n" +
                "flexrule.enableflag\n" +
                "flexrule.flexruledetaillist\n" +
                "flexrule.flexruledetaillist\n" +
                "flexmodelcolumn.modelid\n" +
                "flexmodelcolumn.modelid\n" +
                "audit.entityid\n" +
                "audit.entityid\n" +
                "audit.entitycode\n" +
                "audit.entitycode\n" +
                "audit.description\n" +
                "audit.description\n" +
                "audit.auditflag\n" +
                "audit.auditflag\n" +
                "sysfile.filepath\n" +
                "sysfile.filepath\n" +
                "sysfile.filesizedesc\n" +
                "sysfile.filesizedesc\n" +
                "attachment.normal\n" +
                "attachment.normal\n" +
                "attachment.attachmentid\n" +
                "attachment.attachmentid\n" +
                "attachment.categoryid\n" +
                "attachment.categoryid\n" +
                "attachment.name\n" +
                "attachment.name\n" +
                "attachment.sourcetype\n" +
                "attachment.sourcetype\n" +
                "attachment.sourcekey\n" +
                "attachment.sourcekey\n" +
                "attachment.status\n" +
                "attachment.status\n" +
                "attachment.startactivedate\n" +
                "attachment.startactivedate\n" +
                "attachment.endactivedate\n" +
                "attachment.endactivedate\n" +
                "attachcategory.path\n" +
                "attachcategory.path\n" +
                "attachcategory.allowedfilesizedesc\n" +
                "attachcategory.allowedfilesizedesc\n" +
                "attachcategory.leafflag\n" +
                "attachcategory.leafflag\n" +
                "attachcategory.status\n" +
                "attachcategory.status\n" +
                "attachcategory.parentcategoryid\n" +
                "attachcategory.parentcategoryid\n" +
                "userrole.userid\n" +
                "userrole.userid\n" +
                "userrole.roleid\n" +
                "userrole.roleid\n" +
                "userrole.defaultflag\n" +
                "userrole.defaultflag\n" +
                "user.passwordencrypted\n" +
                "user.passwordencrypted\n" +
                "user.usertype\n" +
                "user.usertype\n" +
                "user.lastlogindate\n" +
                "user.lastlogindate\n" +
                "user.lastpasswordupdatedate\n" +
                "user.lastpasswordupdatedate\n" +
                "user.firstlogin\n" +
                "user.firstlogin\n" +
                "user.description\n" +
                "user.description\n" +
                "user.customerid\n" +
                "user.customerid\n" +
                "user.supplierid\n" +
                "user.supplierid\n" +
                "user.employeeid\n" +
                "user.employeeid\n" +
                "user.employeecode\n" +
                "user.employeecode\n" +
                "user.employeename\n" +
                "user.employeename\n" +
                "sendretrieve.userid\n" +
                "sendretrieve.userid\n" +
                "sendretrieve.retrievetype\n" +
                "sendretrieve.retrievetype\n" +
                "sendretrieve.retrievedate\n" +
                "sendretrieve.retrievedate\n" +
                "sendretrieve.email\n" +
                "sendretrieve.email\n" +
                "sendretrieve.phoneno\n" +
                "sendretrieve.phoneno\n" +
                "role.startactivedate\n" +
                "role.startactivedate\n" +
                "role.endactivedate\n" +
                "role.endactivedate\n" +
                "role.enableflag\n" +
                "role.enableflag";


        return Lists.newArrayList(xls.split("\n"));
    }


}
