package com.jingrui.jrap.report.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.OrderBy;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "acc_charge")
public class Charge extends BaseDTO {

     public static final String FIELD_CHARGE_ID = "chargeId";
     public static final String FIELD_RULE_ID = "ruleId";
     public static final String FIELD_TRANSACTION_ID = "transactionId";
     public static final String FIELD_DOCUMENT_ID = "documentId";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_AMOUNT = "amount";
     public static final String FIELD_CHARGE_DATE = "chargeDate";
     public static final String FIELD_DIGEST = "digest";
     public static final String FIELD_DEAL_SN = "dealSn";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Where
     @Id
     @GeneratedValue
     @OrderBy("desc")
     private Long chargeId;

     @Where
     private Long ruleId; //规则

     @Where
     private Long transactionId; //结算事务ID

     @Where
     private Long documentId; //结算单ID

     @Where
     private Long companyId; //商户ID

     @Where
     private Long amount; //金额

     @Where
     private Date chargeDate; //计费日期

     @Where
     @Length(max = 200)
     private String digest; //摘要

     @Where
     @Length(max = 200)
     private String dealSn; //交易唯一码

     @Where
     private Long programApplicationId;

     @Where
     private Date programUpdateDate;


     public void setChargeId(Long chargeId){
         this.chargeId = chargeId;
     }

     public Long getChargeId(){
         return chargeId;
     }

     public void setRuleId(Long ruleId){
         this.ruleId = ruleId;
     }

     public Long getRuleId(){
         return ruleId;
     }

     public void setTransactionId(Long transactionId){
         this.transactionId = transactionId;
     }

     public Long getTransactionId(){
         return transactionId;
     }

     public void setDocumentId(Long documentId){
         this.documentId = documentId;
     }

     public Long getDocumentId(){
         return documentId;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setAmount(Long amount){
         this.amount = amount;
     }

     public Long getAmount(){
         return amount;
     }

     public void setChargeDate(Date chargeDate){
         this.chargeDate = chargeDate;
     }

     public Date getChargeDate(){
         return chargeDate;
     }

     public void setDigest(String digest){
         this.digest = digest;
     }

     public String getDigest(){
         return digest;
     }

     public void setDealSn(String dealSn){
         this.dealSn = dealSn;
     }

     public String getDealSn(){
         return dealSn;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
