/*
 * *
 *  @file com.maddyhome.idea.copyright.pattern.JavaCopyrightVariablesProvider$1@15ac42c9$
 *  @CopyRight (C) 2018 ZheJiangJingRui Co. Ltd.
 *  @brief JingRui Application Platform
 *  @author $name$
 *  @email yulong.yuan@jr-info.cn
 *  @date $date$
 * /
 */

package com.jingrui.jrap.finance.dto;

/**Auto Generated By Jrap Code Generator**/

import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "fin_period_rules")
public class PeriodRules extends BaseDTO {

     public static final String FIELD_SET_CODE = "setCode";
     public static final String FIELD_PERIOD_NUM = "periodNum";
     public static final String FIELD_ADDITIONAL_NAME = "additionalName";
     public static final String FIELD_MONTH_FROM = "monthFrom";
     public static final String FIELD_MONTH_TO = "monthTo";
     public static final String FIELD_DATE_FROM = "dateFrom";
     public static final String FIELD_DATE_TO = "dateTo";
     public static final String FIELD_QUARTER_NUM = "quarterNum";
     public static final String FIELD_ADJUSTMENT_FLAG = "adjustmentFlag";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @NotEmpty
     @Length(max = 60)
     @OrderBy("ASC")
     @Where
     private String setCode; //表ID，主键，供其他表做外键

     @Id
     @Where
     private Long periodNum; //序号

     @Length(max = 30)
     private String additionalName; //期间名

     private Long monthFrom; //月份从

     private Long monthTo; //月份至

     private Long dateFrom; //日期从

     private Long dateTo; //日期至

     private Long quarterNum; //季度

     @Length(max = 1)
     private String adjustmentFlag; //调整标志

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setSetCode(String setCode){
         this.setCode = setCode;
     }

     public String getSetCode(){
         return setCode;
     }

     public void setPeriodNum(Long periodNum){
         this.periodNum = periodNum;
     }

     public Long getPeriodNum(){
         return periodNum;
     }

     public void setAdditionalName(String additionalName){
         this.additionalName = additionalName;
     }

     public String getAdditionalName(){
         return additionalName;
     }

     public void setMonthFrom(Long monthFrom){
         this.monthFrom = monthFrom;
     }

     public Long getMonthFrom(){
         return monthFrom;
     }

     public void setMonthTo(Long monthTo){
         this.monthTo = monthTo;
     }

     public Long getMonthTo(){
         return monthTo;
     }

     public void setDateFrom(Long dateFrom){
         this.dateFrom = dateFrom;
     }

     public Long getDateFrom(){
         return dateFrom;
     }

     public void setDateTo(Long dateTo){
         this.dateTo = dateTo;
     }

     public Long getDateTo(){
         return dateTo;
     }

     public void setQuarterNum(Long quarterNum){
         this.quarterNum = quarterNum;
     }

     public Long getQuarterNum(){
         return quarterNum;
     }

     public void setAdjustmentFlag(String adjustmentFlag){
         this.adjustmentFlag = adjustmentFlag;
     }

     public String getAdjustmentFlag(){
         return adjustmentFlag;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
