/*
 * *
 *  @file com.maddyhome.idea.copyright.pattern.JavaCopyrightVariablesProvider$1@5d8952ce$
 *  @CopyRight (C) 2018 ZheJiangJingRui Co. Ltd.
 *  @brief JingRui Application Platform
 *  @author $name$
 *  @email yulong.yuan@jr-info.cn
 *  @date $date$
 * /
 */

package com.jingrui.jrap.finance.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import com.jingrui.jrap.fnd.dto.Company;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.JoinColumn;
import com.jingrui.jrap.mybatis.common.query.JoinOn;
import com.jingrui.jrap.mybatis.common.query.JoinTable;
import com.jingrui.jrap.mybatis.common.query.Where;
import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.persistence.criteria.JoinType;
import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "fin_period_sets")
public class PeriodSets extends BaseDTO {

    public static final String FIELD_SET_CODE = "setCode";
    public static final String FIELD_COMPANY_ID = "companyId";
    public static final String FIELD_SET_NAME = "setName";
    public static final String FIELD_TOTAL_PERIOD = "totalPeriod";
    public static final String FIELD_ADDITIONAL_FLAG = "additionalFlag";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


    @Id
    @NotEmpty
    @Length(max = 60)
    @OrderBy("ASC")
    @Where
    private String setCode;

    @JoinTable(name = "companyJoin", target = Company.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Company.FIELD_COMPANY_ID)})
    private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

    @Transient
    @JoinColumn(joinName = "companyJoin", field = Company.FIELD_COMPANY_FULL_NAME)
    private String companyFullName; // 商户全称


    @Length(max = 200)
    @Where
    private String setName; //期间集名称

    private Long totalPeriod; //期间总数

    @Length(max = 50)
    private String additionalFlag; //名称附加

    @Length(max = 1)
    private String enabledFlag; //启用标识

    private Long programApplicationId;

    private Date programUpdateDate;

    @Transient
    private Long yearFrom; //年度从

    @Transient
    private Long yearTo; //年度到

    @Transient
    private List<PeriodRules> rulesList;

    public Long getYearFrom() {
        return yearFrom;
    }

    public void setYearFrom(Long yearFrom) {
        this.yearFrom = yearFrom;
    }

    public Long getYearTo() {
        return yearTo;
    }

    public void setYearTo(Long yearTo) {
        this.yearTo = yearTo;
    }

    public List<PeriodRules> getRulesList() {

        return rulesList;
    }

    public void setRulesList(List<PeriodRules> rulesList) {
        this.rulesList = rulesList;
    }

    public String getCompanyFullName() {
        return companyFullName;
    }

    public void setCompanyFullName(String companyFullName) {
        this.companyFullName = companyFullName;
    }

    public void setSetCode(String setCode) {
        this.setCode = setCode;
    }

    public String getSetCode() {
        return setCode;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setSetName(String setName) {
        this.setName = setName;
    }

    public String getSetName() {
        return setName;
    }

    public void setTotalPeriod(Long totalPeriod) {
        this.totalPeriod = totalPeriod;
    }

    public Long getTotalPeriod() {
        return totalPeriod;
    }

    public void setAdditionalFlag(String additionalFlag) {
        this.additionalFlag = additionalFlag;
    }

    public String getAdditionalFlag() {
        return additionalFlag;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }

    public void setProgramApplicationId(Long programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    public Long getProgramApplicationId() {
        return programApplicationId;
    }

    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

}
