package com.jingrui.jrap.flexfield.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.Table;

import com.jingrui.jrap.mybatis.common.query.Where;
import com.jingrui.jrap.system.dto.BaseDTO;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "fnd_flex_rule")
public class FlexRule extends BaseDTO {

    public static final String FIELD_RULE_ID = "ruleId";
    public static final String FIELD_RULE_SET_ID = "ruleSetId";
    public static final String FIELD_RULE_CODE = "ruleCode";
    public static final String FIELD_DESCRIPTION = "description";
    public static final String FIELD_ENABLE_FLAG = "enableFlag";
    public static final String FIELD_FLEX_RULE_DETAIL_LIST = "flexRuleDetailList";


    @Id
    @GeneratedValue
    private Long ruleId;

    @NotNull
    private Long ruleSetId; //规则集id

    @NotEmpty
    @Length(max = 50)
    @Where
    private String ruleCode; //规则code

    @NotEmpty
    @Length(max = 80)
    private String description; //规则描述

    @NotEmpty
    @Length(max = 2)
    private String enableFlag; //是否启用

    @Transient
    private List<FlexRuleDetail> flexRuleDetailList;


    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    public Long getRuleId() {
        return ruleId;
    }

    public void setRuleSetId(Long ruleSetId) {
        this.ruleSetId = ruleSetId;
    }

    public Long getRuleSetId() {
        return ruleSetId;
    }

    public void setRuleCode(String ruleCode) {
        this.ruleCode = StringUtils.trim(ruleCode);
    }

    public String getRuleCode() {
        return ruleCode;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    public String getEnableFlag() {
        return enableFlag;
    }

    public List<FlexRuleDetail> getFlexRuleDetailList() {
        return flexRuleDetailList;
    }

    public void setFlexRuleDetailList(List<FlexRuleDetail> flexRuleDetailList) {
        this.flexRuleDetailList = flexRuleDetailList;
    }
}
