package com.jingrui.jrap.plm.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "plm_retrieve")
public class Retrieve extends BaseDTO {

     public static final String FIELD_RETRIEVE_ID = "retrieveId";
     public static final String FIELD_RETRIEVE_CODE = "retrieveCode";
     public static final String FIELD_DOCUMENT_CATEGORY = "documentCategory";
     public static final String FIELD_DOCUMENT_TYPE = "documentType";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_RETRIEVE_DATE = "retrieveDate";
     public static final String FIELD_AMOUNT = "amount";
     public static final String FIELD_CHARGE_FEE = "chargeFee";
     public static final String FIELD_OIL_FEE = "oilFee";
     public static final String FIELD_DEPOSIT = "deposit";
     public static final String FIELD_CASHFLOW_ID = "cashflowId";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_SUBMIT_DATE = "submitDate";
     public static final String FIELD_APPROVED_DATE = "approvedDate";
     public static final String FIELD_RECEIVE_DATE = "receiveDate";
     public static final String FIELD_RELEASE_DATE = "releaseDate";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long retrieveId;

     @Length(max = 60)
     private String retrieveCode; //拖收编号

     @Length(max = 60)
     private String documentCategory; //单据类别

     @Length(max = 60)
     private String documentType; //单据类型

     private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

     private Long orderId; //订单ID

     @Length(max = 60)
     private String status; //状态

     private Date retrieveDate; //拖收日期

     private Long amount; //总金额

     private Long chargeFee; //拖收费用

     private Long oilFee; //油费

     private Long deposit; //押金

     private Long cashflowId; //现金流ID

     @Length(max = 200)
     private String description; //摘要

     private Date submitDate; //申请日期

     private Date approvedDate; //通过日期

     private Date receiveDate; //收回日期

     private Date releaseDate; //释放日期

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setRetrieveId(Long retrieveId){
         this.retrieveId = retrieveId;
     }

     public Long getRetrieveId(){
         return retrieveId;
     }

     public void setRetrieveCode(String retrieveCode){
         this.retrieveCode = retrieveCode;
     }

     public String getRetrieveCode(){
         return retrieveCode;
     }

     public void setDocumentCategory(String documentCategory){
         this.documentCategory = documentCategory;
     }

     public String getDocumentCategory(){
         return documentCategory;
     }

     public void setDocumentType(String documentType){
         this.documentType = documentType;
     }

     public String getDocumentType(){
         return documentType;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setRetrieveDate(Date retrieveDate){
         this.retrieveDate = retrieveDate;
     }

     public Date getRetrieveDate(){
         return retrieveDate;
     }

     public void setAmount(Long amount){
         this.amount = amount;
     }

     public Long getAmount(){
         return amount;
     }

     public void setChargeFee(Long chargeFee){
         this.chargeFee = chargeFee;
     }

     public Long getChargeFee(){
         return chargeFee;
     }

     public void setOilFee(Long oilFee){
         this.oilFee = oilFee;
     }

     public Long getOilFee(){
         return oilFee;
     }

     public void setDeposit(Long deposit){
         this.deposit = deposit;
     }

     public Long getDeposit(){
         return deposit;
     }

     public void setCashflowId(Long cashflowId){
         this.cashflowId = cashflowId;
     }

     public Long getCashflowId(){
         return cashflowId;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setSubmitDate(Date submitDate){
         this.submitDate = submitDate;
     }

     public Date getSubmitDate(){
         return submitDate;
     }

     public void setApprovedDate(Date approvedDate){
         this.approvedDate = approvedDate;
     }

     public Date getApprovedDate(){
         return approvedDate;
     }

     public void setReceiveDate(Date receiveDate){
         this.receiveDate = receiveDate;
     }

     public Date getReceiveDate(){
         return receiveDate;
     }

     public void setReleaseDate(Date releaseDate){
         this.releaseDate = releaseDate;
     }

     public Date getReleaseDate(){
         return releaseDate;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
