package com.jingrui.jrap.plm.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "plm_settle_detail")
public class SettleDetail extends BaseDTO {

     public static final String FIELD_DETAIL_ID = "detailId";
     public static final String FIELD_SETTLE_ID = "settleId";
     public static final String FIELD_AMOUNT = "amount";
     public static final String FIELD_CF_TYPE = "cfType";
     public static final String FIELD_DIRECTION = "direction";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long detailId;

     private Long settleId; //结清ID

     private Long amount; //金额

     @Length(max = 60)
     private String cfType; //现金流类型

     @Length(max = 60)
     private String direction; //方向

     @Length(max = 200)
     private String description; //摘要

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setDetailId(Long detailId){
         this.detailId = detailId;
     }

     public Long getDetailId(){
         return detailId;
     }

     public void setSettleId(Long settleId){
         this.settleId = settleId;
     }

     public Long getSettleId(){
         return settleId;
     }

     public void setAmount(Long amount){
         this.amount = amount;
     }

     public Long getAmount(){
         return amount;
     }

     public void setCfType(String cfType){
         this.cfType = cfType;
     }

     public String getCfType(){
         return cfType;
     }

     public void setDirection(String direction){
         this.direction = direction;
     }

     public String getDirection(){
         return direction;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
