package com.jingrui.jrap.activiti.demo.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "act_demo_vacation")
public class DemoVacation {
    @Id
    @GeneratedValue
    private Long id;

    private String userCode;

    private Date startDate;

    private Long needDays;

    private String leaveReason;


    @Transient
    private Date endTime_;


    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setNeedDays(Long needDays) {
        this.needDays = needDays;
    }

    public Long getNeedDays() {
        return needDays;
    }

    public void setLeaveReason(String leaveReason) {
        this.leaveReason = leaveReason;
    }

    public String getLeaveReason() {
        return leaveReason;
    }

    public String getUserCode() {
        return userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    public Date getEndTime_() {
        return endTime_;
    }

    public void setEndTime_(Date endTime_) {
        this.endTime_ = endTime_;
    }

}
