package com.jingrui.jrap.item.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import com.jingrui.jrap.hr.dto.Employee;
import com.jingrui.jrap.hr.dto.HrOrgUnit;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.JoinColumn;
import com.jingrui.jrap.mybatis.common.query.JoinOn;
import com.jingrui.jrap.mybatis.common.query.JoinTable;
import com.jingrui.jrap.mybatis.common.query.Where;
import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.persistence.criteria.JoinType;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "afd_item_allocate")
public class ItemAllocate extends BaseDTO {

    public static final String FIELD_ALLOCATE_ID = "allocateId";
    public static final String FIELD_ALLOCATE_CODE = "allocateCode";
    public static final String FIELD_STATUS = "status";
    public static final String FIELD_COMPANY_ID = "companyId";
    public static final String FIELD_ITEM_ID = "itemId";
    public static final String FIELD_FROM_WAREHOUSE_ID = "fromWarehouseId";
    public static final String FIELD_FROM_UNIT_ID = "fromUnitId";
    public static final String FIELD_FROM_EMPLOYEE_ID = "fromEmployeeId";
    public static final String FIELD_FROM_DATE = "fromDate";
    public static final String FIELD_TO_WAREHOUSE_ID = "toWarehouseId";
    public static final String FIELD_TO_UNIT_ID = "toUnitId";
    public static final String FIELD_TO_EMPLOYEE_ID = "toEmployeeId";
    public static final String FIELD_TO_DATE = "toDate";
    public static final String FIELD_REMARK = "remark";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


    @Where
    @Id
    @GeneratedValue
    @OrderBy("desc")
    private Long allocateId;

    @Where
    @Length(max = 60)
    private String allocateCode; //调拨单

    @Where
    @Length(max = 60)
    private String status; //状态

    @Where
    private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

    @Where
    @JoinTable(name = "itemJoin", target = Item.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Item.FIELD_ITEM_ID)})
    private Long itemId; //租赁物ID

    @Transient
    @JoinColumn(joinName = "itemJoin", field = Item.FIELD_ITEM_CODE)
    private String itemCode; // 租赁物code


    @Where
    @JoinTable(name = "fromWareJoin", target = Warehouse.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Warehouse.FIELD_WAREHOUSE_ID)})
    private Long fromWarehouseId; //出库ID

    @Transient
    @JoinColumn(joinName = "fromWareJoin", field = Warehouse.FIELD_WAREHOUSE_NAME)
    private String fromWarehouseName; // 出库名称

    @Where
    @JoinTable(name = "fromUnitJoin", target = HrOrgUnit.class, type = JoinType.LEFT, on = {@JoinOn(joinField = HrOrgUnit.FIELD_UNIT_ID)})
    private Long fromUnitId; //出分公司ID

    @Transient
    @JoinColumn(joinName = "fromUnitJoin", field = HrOrgUnit.FIELD_NAME)
    private String fromUnitName; // 出分公司名称

    @Where
    @JoinTable(name = "fromEmployeeJoin", target = Employee.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Employee.FIELD_EMPLOYEE_ID)})
    private Long fromEmployeeId; //出库人员ID

    @Transient
    @JoinColumn(joinName = "fromEmployeeJoin", field = Employee.FIELD_EMPLOYEE_CODE)
    private String fromeEmployeeCode; // 出库人编号

    @Where
    private Date fromDate; //出库日期

    @Where
    @JoinTable(name = "toWarehouseJoin", target = Warehouse.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Warehouse.FIELD_WAREHOUSE_ID)})
    private Long toWarehouseId; //入库ID

    @Transient
    @JoinColumn(joinName = "toWarehouseJoin", field = Warehouse.FIELD_WAREHOUSE_NAME)
    private String toWarehouseName; // 入库名称

    @Where
    @JoinTable(name = "toUnitJoin", target = HrOrgUnit.class, type = JoinType.LEFT, on = {@JoinOn(joinField = HrOrgUnit.FIELD_UNIT_ID)})
    private Long toUnitId; //入分公司ID

    @Transient
    @JoinColumn(joinName = "toUnitJoin", field = HrOrgUnit.FIELD_NAME)
    private String toUnitName; // 入分公司名称

    @Where
    @JoinTable(name = "toEmployeeJoin", target = Employee.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Employee.FIELD_EMPLOYEE_ID)})
    private Long toEmployeeId; //入库人员ID

    @Transient
    @JoinColumn(joinName = "toEmployeeJoin", field = Employee.FIELD_EMPLOYEE_CODE)
    private String toEmployeeCode; // 出库人编号

    @Where
    private Date toDate; //入库日期

    @Where
    @Length(max = 200)
    private String remark; //备注说明

    @Where
    private Long programApplicationId;

    @Where
    private Date programUpdateDate;

    public String getItemCode() {
        return itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getFromWarehouseName() {
        return fromWarehouseName;
    }

    public void setFromWarehouseName(String fromWarehouseName) {
        this.fromWarehouseName = fromWarehouseName;
    }

    public String getFromUnitName() {
        return fromUnitName;
    }

    public void setFromUnitName(String fromUnitName) {
        this.fromUnitName = fromUnitName;
    }

    public String getFromeEmployeeCode() {
        return fromeEmployeeCode;
    }

    public void setFromeEmployeeCode(String fromeEmployeeCode) {
        this.fromeEmployeeCode = fromeEmployeeCode;
    }

    public String getToWarehouseName() {
        return toWarehouseName;
    }

    public void setToWarehouseName(String toWarehouseName) {
        this.toWarehouseName = toWarehouseName;
    }

    public String getToUnitName() {
        return toUnitName;
    }

    public void setToUnitName(String toUnitName) {
        this.toUnitName = toUnitName;
    }

    public String getToEmployeeCode() {
        return toEmployeeCode;
    }

    public void setToEmployeeCode(String toEmployeeCode) {
        this.toEmployeeCode = toEmployeeCode;
    }

    public void setAllocateId(Long allocateId) {
        this.allocateId = allocateId;
    }

    public Long getAllocateId() {
        return allocateId;
    }

    public void setAllocateCode(String allocateCode) {
        this.allocateCode = allocateCode;
    }

    public String getAllocateCode() {
        return allocateCode;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setFromWarehouseId(Long fromWarehouseId) {
        this.fromWarehouseId = fromWarehouseId;
    }

    public Long getFromWarehouseId() {
        return fromWarehouseId;
    }

    public void setFromUnitId(Long fromUnitId) {
        this.fromUnitId = fromUnitId;
    }

    public Long getFromUnitId() {
        return fromUnitId;
    }

    public void setFromEmployeeId(Long fromEmployeeId) {
        this.fromEmployeeId = fromEmployeeId;
    }

    public Long getFromEmployeeId() {
        return fromEmployeeId;
    }

    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    public Date getFromDate() {
        return fromDate;
    }

    public void setToWarehouseId(Long toWarehouseId) {
        this.toWarehouseId = toWarehouseId;
    }

    public Long getToWarehouseId() {
        return toWarehouseId;
    }

    public void setToUnitId(Long toUnitId) {
        this.toUnitId = toUnitId;
    }

    public Long getToUnitId() {
        return toUnitId;
    }

    public void setToEmployeeId(Long toEmployeeId) {
        this.toEmployeeId = toEmployeeId;
    }

    public Long getToEmployeeId() {
        return toEmployeeId;
    }

    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }

    public Date getToDate() {
        return toDate;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getRemark() {
        return remark;
    }

    public void setProgramApplicationId(Long programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    public Long getProgramApplicationId() {
        return programApplicationId;
    }

    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

}
