package com.jingrui.jrap.item.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "afd_item_evaluate")
public class ItemEvaluate extends BaseDTO {

     public static final String FIELD_EVALUATE_ID = "evaluateId";
     public static final String FIELD_ITEM_ID = "itemId";
     public static final String FIELD_EVALUATE_TYPE = "evaluateType";
     public static final String FIELD_EVALUATION_DATE = "evaluationDate";
     public static final String FIELD_EVALUATOR = "evaluator";
     public static final String FIELD_OUTSIDE_SCORE = "outsideScore";
     public static final String FIELD_INSIDE_SCORE = "insideScore";
     public static final String FIELD_SKELETON_SCORE = "skeletonScore";
     public static final String FIELD_CONFIG_SCORE = "configScore";
     public static final String FIELD_COMPOSITE_SCORE = "compositeScore";
     public static final String FIELD_EVALUATE_PRICE = "evaluatePrice";
     public static final String FIELD_TRADE_PRICE = "tradePrice";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long evaluateId;

     private Long itemId; //抵押物ID

     @Length(max = 60)
     private String evaluateType; //评估类型

     private Date evaluationDate; //评估时间

     @Length(max = 200)
     private String evaluator; //评估人

     private Long outsideScore; //车体外部评分

     private Long insideScore; //车体内部评分

     private Long skeletonScore; //车骨架评分

     private Long configScore; //车配置评分

     private Long compositeScore; //综合评分

     private Long evaluatePrice; //评估价

     private Long tradePrice; //同行交易价

     @Length(max = 2147483647)
     private String remark; //备注说明

     @Length(max = 1)
     private String enabledFlag; //启用标识

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setEvaluateId(Long evaluateId){
         this.evaluateId = evaluateId;
     }

     public Long getEvaluateId(){
         return evaluateId;
     }

     public void setItemId(Long itemId){
         this.itemId = itemId;
     }

     public Long getItemId(){
         return itemId;
     }

     public void setEvaluateType(String evaluateType){
         this.evaluateType = evaluateType;
     }

     public String getEvaluateType(){
         return evaluateType;
     }

     public void setEvaluationDate(Date evaluationDate){
         this.evaluationDate = evaluationDate;
     }

     public Date getEvaluationDate(){
         return evaluationDate;
     }

     public void setEvaluator(String evaluator){
         this.evaluator = evaluator;
     }

     public String getEvaluator(){
         return evaluator;
     }

     public void setOutsideScore(Long outsideScore){
         this.outsideScore = outsideScore;
     }

     public Long getOutsideScore(){
         return outsideScore;
     }

     public void setInsideScore(Long insideScore){
         this.insideScore = insideScore;
     }

     public Long getInsideScore(){
         return insideScore;
     }

     public void setSkeletonScore(Long skeletonScore){
         this.skeletonScore = skeletonScore;
     }

     public Long getSkeletonScore(){
         return skeletonScore;
     }

     public void setConfigScore(Long configScore){
         this.configScore = configScore;
     }

     public Long getConfigScore(){
         return configScore;
     }

     public void setCompositeScore(Long compositeScore){
         this.compositeScore = compositeScore;
     }

     public Long getCompositeScore(){
         return compositeScore;
     }

     public void setEvaluatePrice(Long evaluatePrice){
         this.evaluatePrice = evaluatePrice;
     }

     public Long getEvaluatePrice(){
         return evaluatePrice;
     }

     public void setTradePrice(Long tradePrice){
         this.tradePrice = tradePrice;
     }

     public Long getTradePrice(){
         return tradePrice;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
