package com.jingrui.jrap.item.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import com.jingrui.jrap.hr.dto.Employee;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.JoinColumn;
import com.jingrui.jrap.mybatis.common.query.JoinOn;
import com.jingrui.jrap.mybatis.common.query.JoinTable;
import com.jingrui.jrap.mybatis.common.query.Where;
import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.criteria.JoinType;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "afd_item_stock")
public class ItemStock extends BaseDTO {

    public static final String FIELD_STOCK_ID = "stockId";
    public static final String FIELD_ITEM_ID = "itemId";
    public static final String FIELD_STOCK_TYPE = "stockType";
    public static final String FIELD_STATUS = "status";
    public static final String FIELD_STOCK_DATE = "stockDate";
    public static final String FIELD_STOCKMAN = "stockman";
    public static final String FIELD_EMPLOYEE_ID = "employeeId";
    public static final String FIELD_REMARK = "remark";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";

    @Where
    @Id
    @GeneratedValue
    private Long stockId;

    @Where
    @JoinTable(name = "itemJoin", target = Item.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Item.FIELD_ITEM_ID)})
    private Long itemId; //租赁物ID

    @Transient
    @JoinColumn(joinName = "itemJoin", field = Item.FIELD_ITEM_CODE)
    private String itemCode; // 租赁物code

    @Where
    @Length(max = 60)
    private String stockType; //出入库类型

    @Where
    @Length(max = 60)
    private String status; //状态

    @Where
    private Date stockDate; //出入库日期

    @Where
    @Length(max = 200)
    private String stockman; //仓库人员

    @Where
    @JoinTable(name = "employeeJoin", target = Employee.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Employee.FIELD_EMPLOYEE_ID)})
    private Long employeeId; //员工

    @Transient
    @JoinColumn(joinName = "employeeJoin", field = Employee.FIELD_EMPLOYEE_CODE)
    private String employeeCode; // 员工CODE


    @Where
    @Length(max = 2147483647)
    private String remark; //备注说明

    @Where
    @Length(max = 1)
    private String enabledFlag; //启用标识

    private Long programApplicationId;

    private Date programUpdateDate;

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getItemCode() {
        return itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    public Long getStockId() {
        return stockId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public Long getItemId() {
        return itemId;
    }

    public void setStockType(String stockType) {
        this.stockType = stockType;
    }

    public String getStockType() {
        return stockType;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setStockDate(Date stockDate) {
        this.stockDate = stockDate;
    }

    public Date getStockDate() {
        return stockDate;
    }

    public void setStockman(String stockman) {
        this.stockman = stockman;
    }

    public String getStockman() {
        return stockman;
    }

    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    public Long getEmployeeId() {
        return employeeId;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getRemark() {
        return remark;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }

    public void setProgramApplicationId(Long programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    public Long getProgramApplicationId() {
        return programApplicationId;
    }

    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

}
