package com.jingrui.jrap.item.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import com.jingrui.jrap.hr.dto.HrOrgUnit;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.JoinColumn;
import com.jingrui.jrap.mybatis.common.query.JoinOn;
import com.jingrui.jrap.mybatis.common.query.JoinTable;
import com.jingrui.jrap.mybatis.common.query.Where;
import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.persistence.criteria.JoinType;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "afd_purchase_assign")
public class PurchaseAssign extends BaseDTO {

    public static final String FIELD_ASSIGN_ID = "assignId";
    public static final String FIELD_PURCHASE_ID = "purchaseId";
    public static final String FIELD_DETAIL_ID = "detailId";
    public static final String FIELD_UNIT_ID = "unitId";
    public static final String FIELD_WAREHOUSE_ID = "warehouseId";
    public static final String FIELD_ASSIGN_NUMBER = "assignNumber";
    public static final String FIELD_UNREGISTER_NUM = "unregisterNum";
    public static final String FIELD_ASSIGN_DATE = "assignDate";
    public static final String FIELD_REMARK = "remark";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


    @Where
    @Id
    @GeneratedValue
    @OrderBy("desc")
    private Long assignId;

    @Where
    private Long purchaseId; //采购ID

    @Where
    private Long detailId; //采购明细ID

    @Where
    @JoinTable(name = "unitJoin", target = HrOrgUnit.class, type = JoinType.LEFT, on = {@JoinOn(joinField = HrOrgUnit.FIELD_UNIT_ID)})
    private Long unitId; //分公司

    @Where
    @JoinTable(name = "wareJoin", target = Warehouse.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Warehouse.FIELD_WAREHOUSE_ID)})
    private Long warehouseId; //仓库ID

    @Transient
    @JoinColumn(joinName = "wareJoin", field = Warehouse.FIELD_WAREHOUSE_NAME)
    private String warehouseName; // 仓库名称

    @Where
    private Long assignNumber; //分配数量

    @Where
    private Long unregisterNum; //未登记数量

    @Where
    private Date assignDate; //分配日期

    @Where
    @Length(max = 200)
    private String remark; //备注说明

    @Where
    private Long programApplicationId;

    @Where
    private Date programUpdateDate;

    @Transient
    private String companyFullName; // 商户全称

    @Transient
    @JoinColumn(joinName = "unitJoin", field = HrOrgUnit.FIELD_NAME)
    private String unitName; // 分公司名称

    @Transient
    private String employeeCode; // 采购员名称

    @Transient
    private String customerName; // 供应商名称

    @Transient
    private String model; // 租赁物型号

    @Transient
    private String purchaseCode; //采购单号

    public Long getUnregisterNum() {
        return unregisterNum;
    }

    public void setUnregisterNum(Long unregisterNum) {
        this.unregisterNum = unregisterNum;
    }

    public String getPurchaseCode() {
        return purchaseCode;
    }

    public void setPurchaseCode(String purchaseCode) {
        this.purchaseCode = purchaseCode;
    }

    public String getCompanyFullName() {
        return companyFullName;
    }

    public void setCompanyFullName(String companyFullName) {
        this.companyFullName = companyFullName;
    }

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getWarehouseName() {
        return warehouseName;
    }

    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName;
    }

    public void setAssignId(Long assignId) {
        this.assignId = assignId;
    }

    public Long getAssignId() {
        return assignId;
    }

    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    public Long getPurchaseId() {
        return purchaseId;
    }

    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    public Long getDetailId() {
        return detailId;
    }

    public void setUnitId(Long unitId) {
        this.unitId = unitId;
    }

    public Long getUnitId() {
        return unitId;
    }

    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    public Long getWarehouseId() {
        return warehouseId;
    }

    public void setAssignNumber(Long assignNumber) {
        this.assignNumber = assignNumber;
    }

    public Long getAssignNumber() {
        return assignNumber;
    }

    public void setAssignDate(Date assignDate) {
        this.assignDate = assignDate;
    }

    public Date getAssignDate() {
        return assignDate;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getRemark() {
        return remark;
    }

    public void setProgramApplicationId(Long programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    public Long getProgramApplicationId() {
        return programApplicationId;
    }

    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

}
