package com.jingrui.jrap.item.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import com.jingrui.jrap.customer.dto.Customer;
import com.jingrui.jrap.fnd.dto.Company;
import com.jingrui.jrap.hr.dto.Employee;
import com.jingrui.jrap.hr.dto.HrOrgUnit;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.JoinColumn;
import com.jingrui.jrap.mybatis.common.query.JoinOn;
import com.jingrui.jrap.mybatis.common.query.JoinTable;
import com.jingrui.jrap.mybatis.common.query.Where;
import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.persistence.criteria.JoinType;
import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "afd_purchase")
public class Purchase extends BaseDTO {

    public static final String FIELD_PURCHASE_ID = "purchaseId";
    public static final String FIELD_PURCHASE_CODE = "purchaseCode";
    public static final String FIELD_PURCHASE_DATE = "purchaseDate";
    public static final String FIELD_STATUS = "status";
    public static final String FIELD_COMPANY_ID = "companyId";
    public static final String FIELD_UNIT_ID = "unitId";
    public static final String FIELD_EMPLOYEE_ID = "employeeId";
    public static final String FIELD_VENDOR_ID = "vendorId";
    public static final String FIELD_TOTAL_AMOUNT = "totalAmount";
    public static final String FIELD_TOTAL_NUMBER = "totalNumber";
    public static final String FIELD_REMARK = "remark";
    public static final String FIELD_SUBMIT_DATE = "submitDate";
    public static final String FIELD_APPROVED_DATE = "approvedDate";
    public static final String FIELD_REFUSE_DATE = "refuseDate";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


    @Where
    @Id
    @GeneratedValue
    @OrderBy("desc")
    private Long purchaseId;

    @Where
    @NotEmpty
    @Length(max = 60)
    private String purchaseCode; //采购单号

    @Where
    private Date purchaseDate; //采购日期

    @Where
    @NotEmpty
    @Length(max = 60)
    private String status; //状态

    @Where
    @JoinTable(name = "companyJoin", target = Company.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Company.FIELD_COMPANY_ID)})
    private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

    @Transient
    @JoinColumn(joinName = "companyJoin", field = Company.FIELD_COMPANY_FULL_NAME)
    private String companyFullName; // 商户全称

    @Where
    @JoinTable(name = "unitJoin", target = HrOrgUnit.class, type = JoinType.LEFT, on = {@JoinOn(joinField = HrOrgUnit.FIELD_UNIT_ID)})
    private Long unitId; //分公司

    @Transient
    @JoinColumn(joinName = "unitJoin", field = HrOrgUnit.FIELD_NAME)
    private String name; // 分公司名称

    @Where
    @JoinTable(name = "employeeJoin", target = Employee.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Employee.FIELD_EMPLOYEE_ID)})
    private Long employeeId; //采购员

    @Transient
    @JoinColumn(joinName = "employeeJoin", field = Employee.FIELD_EMPLOYEE_CODE)
    private String employeeCode; // 采购员名称

    @Where
    @JoinTable(name = "customerJoin", target = Customer.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Customer.FIELD_CUSTOMER_ID)})
    private Long vendorId; //供应商ID

    @Transient
    @JoinColumn(joinName = "customerJoin", field = Customer.FIELD_CUSTOMER_NAME)
    private String customerName; // 供应商名称

    @Where
    private Long totalAmount; //采购总额

    @Where
    private Long totalNumber; //采购数量

    @Where
    @Length(max = 200)
    private String remark; //备注

    @Where
    private Date submitDate; //提交日期

    @Where
    private Date approvedDate; //审批通过日期

    @Where
    private Date refuseDate; //审批拒绝日期

    @Where
    private Long programApplicationId;

    @Where
    private Date programUpdateDate;

    @Transient
    private List<PurchaseDetail> purchaseDetails;

    @Transient
    private String remainNumber; // 剩余数量

    public String getRemainNumber() {
        return remainNumber;
    }

    public void setRemainNumber(String remainNumber) {
        this.remainNumber = remainNumber;
    }

    public String getCompanyFullName() {
        return companyFullName;
    }

    public void setCompanyFullName(String companyFullName) {
        this.companyFullName = companyFullName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public List<PurchaseDetail> getPurchaseDetails() {
        return purchaseDetails;
    }

    public void setPurchaseDetails(List<PurchaseDetail> purchaseDetails) {
        this.purchaseDetails = purchaseDetails;
    }

    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    public Long getPurchaseId() {
        return purchaseId;
    }

    public void setPurchaseCode(String purchaseCode) {
        this.purchaseCode = purchaseCode;
    }

    public String getPurchaseCode() {
        return purchaseCode;
    }

    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    public Date getPurchaseDate() {
        return purchaseDate;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setUnitId(Long unitId) {
        this.unitId = unitId;
    }

    public Long getUnitId() {
        return unitId;
    }

    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    public Long getEmployeeId() {
        return employeeId;
    }

    public void setVendorId(Long vendorId) {
        this.vendorId = vendorId;
    }

    public Long getVendorId() {
        return vendorId;
    }

    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    public Long getTotalAmount() {
        return totalAmount;
    }

    public void setTotalNumber(Long totalNumber) {
        this.totalNumber = totalNumber;
    }

    public Long getTotalNumber() {
        return totalNumber;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getRemark() {
        return remark;
    }

    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    public Date getSubmitDate() {
        return submitDate;
    }

    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    public Date getApprovedDate() {
        return approvedDate;
    }

    public void setRefuseDate(Date refuseDate) {
        this.refuseDate = refuseDate;
    }

    public Date getRefuseDate() {
        return refuseDate;
    }

    public void setProgramApplicationId(Long programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    public Long getProgramApplicationId() {
        return programApplicationId;
    }

    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

}
