package com.jingrui.jrap.basic.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.OrderBy;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "acc_account")
public class BasicAccount extends BaseDTO {

     public static final String FIELD_ACCOUNT_ID = "accountId";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_ACCOUNT_NUMBER = "accountNumber";
     public static final String FIELD_ACCOUNT_NAME = "accountName";
     public static final String FIELD_ACCOUNT_TYPE = "accountType";
     public static final String FIELD_ACCOUNT_CLASS = "accountClass";
     public static final String FIELD_ACCOUNT_USAGE = "accountUsage";
     public static final String FIELD_BANK_ID = "bankId";
     public static final String FIELD_OWNER_TYPE = "ownerType";
     public static final String FIELD_OWNER_ID = "ownerId";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Where
     @Id
     @GeneratedValue
     @OrderBy("desc")
     private Long accountId;

     @Where
     private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

     @Where
     @Length(max = 60)
     private String accountNumber; //账号

     @Where
     @Length(max = 200)
     private String accountName; //账户

     @Where
     @Length(max = 60)
     private String accountType; //账户类型

     @Where
     @Length(max = 60)
     private String accountClass; //账户属性

     @Where
     @Length(max = 60)
     private String accountUsage; //账户用途

     @Where
     private Long bankId; //银行表ID

     @Where
     @NotEmpty
     @Length(max = 50)
     private String ownerType; //所有者类型

     @Where
     @NotNull
     private Long ownerId; //所有者ID

     @Where
     @Length(max = 1)
     private String enabledFlag; //启用标识

     @Where
     private Long programApplicationId;

     @Where
     private Date programUpdateDate;


     public void setAccountId(Long accountId){
         this.accountId = accountId;
     }

     public Long getAccountId(){
         return accountId;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setAccountNumber(String accountNumber){
         this.accountNumber = accountNumber;
     }

     public String getAccountNumber(){
         return accountNumber;
     }

     public void setAccountName(String accountName){
         this.accountName = accountName;
     }

     public String getAccountName(){
         return accountName;
     }

     public void setAccountType(String accountType){
         this.accountType = accountType;
     }

     public String getAccountType(){
         return accountType;
     }

     public void setAccountClass(String accountClass){
         this.accountClass = accountClass;
     }

     public String getAccountClass(){
         return accountClass;
     }

     public void setAccountUsage(String accountUsage){
         this.accountUsage = accountUsage;
     }

     public String getAccountUsage(){
         return accountUsage;
     }

     public void setBankId(Long bankId){
         this.bankId = bankId;
     }

     public Long getBankId(){
         return bankId;
     }

     public void setOwnerType(String ownerType){
         this.ownerType = ownerType;
     }

     public String getOwnerType(){
         return ownerType;
     }

     public void setOwnerId(Long ownerId){
         this.ownerId = ownerId;
     }

     public Long getOwnerId(){
         return ownerId;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
