/*
 * *
 *  @file com.maddyhome.idea.copyright.pattern.JavaCopyrightVariablesProvider$1@784ac4bc$
 *  @CopyRight (C) 2018 ZheJiangJingRui Co. Ltd.
 *  @brief JingRui Application Platform
 *  @author $name$
 *  @email yulong.yuan@jr-info.cn
 *  @date $date$
 * /
 */

package com.jingrui.jrap.change.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "con_change_assign")
public class ChangeAssign extends BaseDTO {

  public static final String FIELD_ASSIGN_ID = "assignId";
  public static final String FIELD_CHANGE_ID = "changeId";
  public static final String FIELD_CONTACT_ID = "contactId";
  public static final String FIELD_UNIT_ID = "unitId";
  public static final String FIELD_EMPLOYEE_ID = "employeeId";
  public static final String FIELD_INVALID_DATE = "invalidDate";
  public static final String FIELD_ASSIGN_DATE = "assignDate";
  public static final String FIELD_ASSIGN_NOTE = "assignNote";
  public static final String FIELD_REMARK = "remark";
  public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
  public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


  @Id
  @GeneratedValue
  private Long assignId;

  private Long changeId; //商机ID

  private Long contactId; //商机ID

  private Long unitId; //组织部门HR_ORG_UNIT_B.UNIT_ID

  private Long employeeId; //员工HR_EMPLOYEE T.EMPLOYEE_ID

  private Date invalidDate; //失效时间

  private Date assignDate; //分配时间

  @Length(max = 200)
  private String assignNote; //备注

  @Length(max = 2147483647)
  private String remark; //备注说明

  private Long programApplicationId;

  private Date programUpdateDate;

  public Long getContactId() {
    return contactId;
  }

  public void setContactId(Long contactId) {
    this.contactId = contactId;
  }

  public void setAssignId(Long assignId) {
    this.assignId = assignId;
  }

  public Long getAssignId() {
    return assignId;
  }

  public void setChangeId(Long changeId) {
    this.changeId = changeId;
  }

  public Long getChangeId() {
    return changeId;
  }

  public void setUnitId(Long unitId) {
    this.unitId = unitId;
  }

  public Long getUnitId() {
    return unitId;
  }

  public void setEmployeeId(Long employeeId) {
    this.employeeId = employeeId;
  }

  public Long getEmployeeId() {
    return employeeId;
  }

  public void setInvalidDate(Date invalidDate) {
    this.invalidDate = invalidDate;
  }

  public Date getInvalidDate() {
    return invalidDate;
  }

  public void setAssignDate(Date assignDate) {
    this.assignDate = assignDate;
  }

  public Date getAssignDate() {
    return assignDate;
  }

  public void setAssignNote(String assignNote) {
    this.assignNote = assignNote;
  }

  public String getAssignNote() {
    return assignNote;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public String getRemark() {
    return remark;
  }

  public void setProgramApplicationId(Long programApplicationId) {
    this.programApplicationId = programApplicationId;
  }

  public Long getProgramApplicationId() {
    return programApplicationId;
  }

  public void setProgramUpdateDate(Date programUpdateDate) {
    this.programUpdateDate = programUpdateDate;
  }

  public Date getProgramUpdateDate() {
    return programUpdateDate;
  }

}
