/*
 * *
 *  @file com.maddyhome.idea.copyright.pattern.JavaCopyrightVariablesProvider$1@2a103c64$
 *  @CopyRight (C) 2018 ZheJiangJingRui Co. Ltd.
 *  @brief JingRui Application Platform
 *  @author $name$
 *  @email yulong.yuan@jr-info.cn
 *  @date $date$
 * /
 */

package com.jingrui.jrap.change.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "con_change")
public class Change extends BaseDTO {

  public static final String FIELD_CHANGE_ID = "changeId";
  public static final String FIELD_CHANGE_CODE = "changeCode";
  public static final String FIELD_DOCUMENT_CATEGORY = "documentCategory";
  public static final String FIELD_DOCUMENT_TYPE = "documentType";
  public static final String FIELD_GOOD_ID = "goodId";
  public static final String FIELD_PRODUCT_CODE = "productCode";
  public static final String FIELD_INDICATIVE_AMOUNT = "indicativeAmount";
  public static final String FIELD_STATUS = "status";
  public static final String FIELD_COMPANY_ID = "companyId";
  public static final String FIELD_UNIT_ID = "unitId";
  public static final String FIELD_EMPLOYEE_ID = "employeeId";
  public static final String FIELD_SUBMIT_DATE = "submitDate";
  public static final String FIELD_APPROVED_DATE = "approvedDate";
  public static final String FIELD_REFUSE_DATE = "refuseDate";
  public static final String FIELD_CUSTOMER_ID = "customerId";
  public static final String FIELD_CUSTOMER_NAME = "customerName";
  public static final String FIELD_CELLPHONE = "cellphone";
  public static final String FIELD_CELLPHONE02 = "cellphone02";
  public static final String FIELD_CELLPHONE03 = "cellphone03";
  public static final String FIELD_ID_TYPE = "idType";
  public static final String FIELD_ID_NUMBER = "idNumber";
  public static final String FIELD_CAR_LICENSE = "carLicense";
  public static final String FIELD_CAR_MODEL = "carModel";
  public static final String FIELD_REMARK = "remark";
  public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
  public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


  @Id
  @GeneratedValue
  private Long changeId;

  @Length(max = 60)
  private String changeCode; //销售机会编号

  @NotEmpty
  @Length(max = 60)
  private String documentCategory; //单据类别

  @NotEmpty
  @Length(max = 60)
  private String documentType; //单据类型

  private Long goodId; //商品ID

  @Length(max = 60)
  private String productCode; //产品编码

  private Long indicativeAmount; //意向价格

  @Length(max = 60)
  private String status; //状态

  private Long companyId; //公司ID

  private Long unitId; //机构ID
  private Long modelId;//租赁物ID

  private Long employeeId; //业务员ID

  private Date submitDate; //申请日期

  private Date approvedDate; //通过日期

  private Date refuseDate; //拒绝日期

  private Long customerId; //客户ID

  @Length(max = 200)
  private String customerName; //客户姓名

  @Length(max = 30)
  private String cellphone; //手机号
  @Length(max = 30)
  private String cellphone02; //手机号
  @Length(max = 30)
  private String cellphone03; //手机号

  @Length(max = 60)
  private String idType; //证件类型

  @Length(max = 60)
  private String idNumber; //证件号

  @Length(max = 60)
  private String carLicense; //车牌号

  @Length(max = 200)
  private String carModel; //车型

  @Length(max = 2147483647)
  private String remark; //备注说明

  private Long programApplicationId;

  private Date programUpdateDate;

  public Long getModelId() {
    return modelId;
  }

  public void setModelId(Long modelId) {
    this.modelId = modelId;
  }

  public void setChangeId(Long changeId) {
    this.changeId = changeId;
  }

  public Long getChangeId() {
    return changeId;
  }

  public void setChangeCode(String changeCode) {
    this.changeCode = changeCode;
  }

  public String getChangeCode() {
    return changeCode;
  }

  public void setDocumentCategory(String documentCategory) {
    this.documentCategory = documentCategory;
  }

  public String getDocumentCategory() {
    return documentCategory;
  }

  public void setDocumentType(String documentType) {
    this.documentType = documentType;
  }

  public String getDocumentType() {
    return documentType;
  }

  public void setGoodId(Long goodId) {
    this.goodId = goodId;
  }

  public Long getGoodId() {
    return goodId;
  }

  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }

  public String getProductCode() {
    return productCode;
  }

  public void setIndicativeAmount(Long indicativeAmount) {
    this.indicativeAmount = indicativeAmount;
  }

  public Long getIndicativeAmount() {
    return indicativeAmount;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getStatus() {
    return status;
  }

  public void setCompanyId(Long companyId) {
    this.companyId = companyId;
  }

  public Long getCompanyId() {
    return companyId;
  }

  public void setUnitId(Long unitId) {
    this.unitId = unitId;
  }

  public Long getUnitId() {
    return unitId;
  }

  public void setEmployeeId(Long employeeId) {
    this.employeeId = employeeId;
  }

  public Long getEmployeeId() {
    return employeeId;
  }

  public void setSubmitDate(Date submitDate) {
    this.submitDate = submitDate;
  }

  public Date getSubmitDate() {
    return submitDate;
  }

  public void setApprovedDate(Date approvedDate) {
    this.approvedDate = approvedDate;
  }

  public Date getApprovedDate() {
    return approvedDate;
  }

  public void setRefuseDate(Date refuseDate) {
    this.refuseDate = refuseDate;
  }

  public Date getRefuseDate() {
    return refuseDate;
  }

  public void setCustomerId(Long customerId) {
    this.customerId = customerId;
  }

  public Long getCustomerId() {
    return customerId;
  }

  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  public String getCustomerName() {
    return customerName;
  }

  public void setCellphone(String cellphone) {
    this.cellphone = cellphone;
  }

  public String getCellphone() {
    return cellphone;
  }

  public void setIdType(String idType) {
    this.idType = idType;
  }

  public String getIdType() {
    return idType;
  }

  public void setIdNumber(String idNumber) {
    this.idNumber = idNumber;
  }

  public String getIdNumber() {
    return idNumber;
  }

  public void setCarLicense(String carLicense) {
    this.carLicense = carLicense;
  }

  public String getCarLicense() {
    return carLicense;
  }

  public void setCarModel(String carModel) {
    this.carModel = carModel;
  }

  public String getCarModel() {
    return carModel;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public String getRemark() {
    return remark;
  }

  public static String getFieldChangeId() {
    return FIELD_CHANGE_ID;
  }

  public String getCellphone02() {
    return cellphone02;
  }

  public void setCellphone02(String cellphone02) {
    this.cellphone02 = cellphone02;
  }

  public String getCellphone03() {
    return cellphone03;
  }

  public void setCellphone03(String cellphone03) {
    this.cellphone03 = cellphone03;
  }

  public void setProgramApplicationId(Long programApplicationId) {
    this.programApplicationId = programApplicationId;
  }

  public Long getProgramApplicationId() {
    return programApplicationId;
  }

  public void setProgramUpdateDate(Date programUpdateDate) {
    this.programUpdateDate = programUpdateDate;
  }

  public Date getProgramUpdateDate() {
    return programUpdateDate;
  }

}
