/*
 * *
 *  @file com.maddyhome.idea.copyright.pattern.JavaCopyrightVariablesProvider$1@502f70a$
 *  @CopyRight (C) 2018 ZheJiangJingRui Co. Ltd.
 *  @brief JingRui Application Platform
 *  @author $name$
 *  @email yulong.yuan@jr-info.cn
 *  @date $date$
 * /
 */

package com.jingrui.jrap.change.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable=true)
@Table(name = "con_contact")
public class Contact extends BaseDTO {

     public static final String FIELD_CONTACT_ID = "contactId";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_GOOD_ID = "goodId";
     public static final String FIELD_CUSTOMER_NAME = "customerName";
     public static final String FIELD_CELLPHONE = "cellphone";
     public static final String FIELD_CELLPHONE02 = "cellphone02";
     public static final String FIELD_CELLPHONE03 = "cellphone03";
     public static final String FIELD_ID_TYPE = "idType";
     public static final String FIELD_ID_NUMBER = "idNumber";
     public static final String FIELD_SOURCE_TYPE = "sourceType";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long contactId;

     private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

     @Length(max = 60)
     private String status; //状态

     private Long goodId; //商品ID

     @Length(max = 200)
     private String customerName; //客户姓名

     @Length(max = 30)
     private String cellphone; //手机号

     @Length(max = 30)
     private String cellphone02; //手机号02

     @Length(max = 30)
     private String cellphone03; //手机号03

     @Length(max = 60)
     private String idType; //证件类型

     @Length(max = 60)
     private String idNumber; //证件号

     @NotEmpty
     @Length(max = 60)
     private String sourceType; //来源

     @Length(max = 1)
     private String enabledFlag; //启用标识

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setContactId(Long contactId){
         this.contactId = contactId;
     }

     public Long getContactId(){
         return contactId;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setGoodId(Long goodId){
         this.goodId = goodId;
     }

     public Long getGoodId(){
         return goodId;
     }

     public void setCustomerName(String customerName){
         this.customerName = customerName;
     }

     public String getCustomerName(){
         return customerName;
     }

     public void setCellphone(String cellphone){
         this.cellphone = cellphone;
     }

     public String getCellphone(){
         return cellphone;
     }

     public void setCellphone02(String cellphone02){
         this.cellphone02 = cellphone02;
     }

     public String getCellphone02(){
         return cellphone02;
     }

     public void setCellphone03(String cellphone03){
         this.cellphone03 = cellphone03;
     }

     public String getCellphone03(){
         return cellphone03;
     }

     public void setIdType(String idType){
         this.idType = idType;
     }

     public String getIdType(){
         return idType;
     }

     public void setIdNumber(String idNumber){
         this.idNumber = idNumber;
     }

     public String getIdNumber(){
         return idNumber;
     }

     public void setSourceType(String sourceType){
         this.sourceType = sourceType;
     }

     public String getSourceType(){
         return sourceType;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
