package com.jingrui.jrap.order.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;

import com.jingrui.jrap.system.dto.BaseDTO;

import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "con_cashflow")
public class Cashflow extends BaseDTO {

    public static final String FIELD_CASHFLOW_ID = "cashflowId";
    public static final String FIELD_ORDER_ID = "orderId";
    public static final String FIELD_CF_TYPE = "cfType";
    public static final String FIELD_CF_DIRECTION = "cfDirection";
    public static final String FIELD_CF_STATUS = "cfStatus";
    public static final String FIELD_TIMES = "times";
    public static final String FIELD_CALC_DATE = "calcDate";
    public static final String FIELD_DUE_DATE = "dueDate";
    public static final String FIELD_DUE_AMOUNT = "dueAmount";
    public static final String FIELD_NET_DUE_AMOUNT = "netDueAmount";
    public static final String FIELD_VAT_DUE_AMOUNT = "vatDueAmount";
    public static final String FIELD_PRINCIPAL = "principal";
    public static final String FIELD_NET_PRINCIPAL = "netPrincipal";
    public static final String FIELD_VAT_PRINCIPAL = "vatPrincipal";
    public static final String FIELD_INTEREST = "interest";
    public static final String FIELD_NET_INTEREST = "netInterest";
    public static final String FIELD_VAT_INTEREST = "vatInterest";
    public static final String FIELD_PRINCIPAL_IMPLICIT_RATE = "principalImplicitRate";
    public static final String FIELD_NET_PRINCIPAL_IMPLICIT = "netPrincipalImplicit";
    public static final String FIELD_VAT_PRINCIPAL_IMPLICIT = "vatPrincipalImplicit";
    public static final String FIELD_INTEREST_IMPLICIT_RATE = "interestImplicitRate";
    public static final String FIELD_NET_INTEREST_IMPLICIT = "netInterestImplicit";
    public static final String FIELD_VAT_INTEREST_IMPLICIT = "vatInterestImplicit";
    public static final String FIELD_OUTSTANDING_RENTAL = "outstandingRental";
    public static final String FIELD_OUTSTANDING_PRINCIPAL = "outstandingPrincipal";
    public static final String FIELD_OUTSTANDING_INTEREST = "outstandingInterest";
    public static final String FIELD_INTEREST_PERIOD_DAYS = "interestPeriodDays";
    public static final String FIELD_SOURCE_TYPE = "sourceType";
    public static final String FIELD_SOURCE_ID = "sourceId";
    public static final String FIELD_COLOUR_SCHEME = "colourScheme";
    public static final String FIELD_CALC_LINE_ID = "calcLineId";
    public static final String FIELD_OVERDUE_STATUS = "overdueStatus";
    public static final String FIELD_OVERDUE_DATE = "overdueDate";
    public static final String FIELD_OVERDUE_MAX_DAYS = "overdueMaxDays";
    public static final String FIELD_OVERDUE_AMOUNT = "overdueAmount";
    public static final String FIELD_OVERDUE_PRINCIPAL = "overduePrincipal";
    public static final String FIELD_OVERDUE_INTEREST = "overdueInterest";
    public static final String FIELD_RECEIVED_AMOUNT = "receivedAmount";
    public static final String FIELD_RECEIVED_PRINCIPAL = "receivedPrincipal";
    public static final String FIELD_RECEIVED_INTEREST = "receivedInterest";
    public static final String FIELD_WRITEOFF_FLAG = "writeoffFlag";
    public static final String FIELD_LAST_RECEIVED_DATE = "lastReceivedDate";
    public static final String FIELD_FULL_WRITEOFF_DATE = "fullWriteoffDate";
    public static final String FIELD_PENALTY_PROCESS_STATUS = "penaltyProcessStatus";
    public static final String FIELD_BILLING_STATUS = "billingStatus";
    public static final String FIELD_BILLING_AMOUNT = "billingAmount";
    public static final String FIELD_BILLING_PRINCIPAL = "billingPrincipal";
    public static final String FIELD_BILLING_INTEREST = "billingInterest";
    public static final String FIELD_REMARK = "remark";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


    @Id
    @GeneratedValue
    private Long cashflowId;

    private Long orderId; //订单ID

    @Length(max = 60)
    private String cfType; //现金流类型

    @Length(max = 60)
    private String cfDirection; //现金流方向（INFLOW/OUTFLOW/NONCASH）

    @Length(max = 60)
    private String cfStatus; //现金流状态（BLOCK/冻结 、RELEASE/下达、CANCEL/取消）

    private int times; //期数

    private Date calcDate; //计算日

    private Date dueDate; //支付日/到期日

    private Double dueAmount; //应收金额

    private Double netDueAmount; //不含税应收金额

    private Double vatDueAmount; //增值税额

    private Double principal; //应收本金

    private Double netPrincipal; //不含税本金

    private Double vatPrincipal; //本金增值税额

    private Double interest; //应收利息

    private Double netInterest; //不含税利息

    private Double vatInterest; //利息增值税额

    private Double principalImplicitRate; //实际利率法本金

    private Double netPrincipalImplicit; //实际利率法不含税本金

    private Double vatPrincipalImplicit; //实际利率法本金增值税额

    private Double interestImplicitRate; //实际利率法利息

    private Double netInterestImplicit; //实际利率法不含税利息

    private Double vatInterestImplicit; //实际利率法利息增值税额

    private Double outstandingRental; //当期剩余租金

    private Double outstandingPrincipal; //当期剩余本金

    private Double outstandingInterest; //当期剩余利息

    private Double interestPeriodDays; //计息天数（利息期天数）

    @Length(max = 60)
    private String sourceType; //来源类型（CALCULATOR/计算器ET/结清MANUAL/手工DAY_END/日结）

    private Long sourceId; //来源ID

    @Length(max = 60)
    private String colourScheme; //颜色方案

    private Long calcLineId; //计算器行ID

    @Length(max = 60)
    private String overdueStatus; //逾期状态（N 未逾期、Y 已逾期）

    private Date overdueDate; //逾期计算日

    private int overdueMaxDays; //最大逾期天数

    private Double overdueAmount; //逾期金额

    private Double overduePrincipal; //逾期本金

    private Double overdueInterest; //逾期利息

    private Double receivedAmount; //已收金额

    private Double receivedPrincipal; //已收本金

    private Double receivedInterest; //已收利息

    @Length(max = 60)
    private String writeoffFlag; //核销标志（NOT/PARTIAL/FULL）

    private Date lastReceivedDate; //最后收款日

    private Date fullWriteoffDate; //完全核销日

    @Length(max = 60)
    private String penaltyProcessStatus; //罚金处理状态（NORMAL正常/SUSPEND暂停计算/EXEMPT豁免）

    @Length(max = 60)
    private String billingStatus; //开票状态（NOT/PARTIAL/FULL）

    private Double billingAmount; //开票金额

    private Double billingPrincipal; //本金开票金额

    private Double billingInterest; //利息开票金额

    public void setCashflowId(Long cashflowId) {
        this.cashflowId = cashflowId;
    }

    public Long getCashflowId() {
        return cashflowId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setCfType(String cfType) {
        this.cfType = cfType;
    }

    public String getCfType() {
        return cfType;
    }

    public void setCfDirection(String cfDirection) {
        this.cfDirection = cfDirection;
    }

    public String getCfDirection() {
        return cfDirection;
    }

    public void setCfStatus(String cfStatus) {
        this.cfStatus = cfStatus;
    }

    public String getCfStatus() {
        return cfStatus;
    }

    public void setTimes(int times) {
        this.times = times;
    }

    public int getTimes() {
        return times;
    }

    public void setCalcDate(Date calcDate) {
        this.calcDate = calcDate;
    }

    public Date getCalcDate() {
        return calcDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setDueAmount(Double dueAmount) {
        this.dueAmount = dueAmount;
    }

    public Double getDueAmount() {
        return dueAmount;
    }

    public void setNetDueAmount(Double netDueAmount) {
        this.netDueAmount = netDueAmount;
    }

    public Double getNetDueAmount() {
        return netDueAmount;
    }

    public void setVatDueAmount(Double vatDueAmount) {
        this.vatDueAmount = vatDueAmount;
    }

    public Double getVatDueAmount() {
        return vatDueAmount;
    }

    public void setPrincipal(Double principal) {
        this.principal = principal;
    }

    public Double getPrincipal() {
        return principal;
    }

    public void setNetPrincipal(Double netPrincipal) {
        this.netPrincipal = netPrincipal;
    }

    public Double getNetPrincipal() {
        return netPrincipal;
    }

    public void setVatPrincipal(Double vatPrincipal) {
        this.vatPrincipal = vatPrincipal;
    }

    public Double getVatPrincipal() {
        return vatPrincipal;
    }

    public void setInterest(Double interest) {
        this.interest = interest;
    }

    public Double getInterest() {
        return interest;
    }

    public void setNetInterest(Double netInterest) {
        this.netInterest = netInterest;
    }

    public Double getNetInterest() {
        return netInterest;
    }

    public void setVatInterest(Double vatInterest) {
        this.vatInterest = vatInterest;
    }

    public Double getVatInterest() {
        return vatInterest;
    }

    public void setPrincipalImplicitRate(Double principalImplicitRate) {
        this.principalImplicitRate = principalImplicitRate;
    }

    public Double getPrincipalImplicitRate() {
        return principalImplicitRate;
    }

    public void setNetPrincipalImplicit(Double netPrincipalImplicit) {
        this.netPrincipalImplicit = netPrincipalImplicit;
    }

    public Double getNetPrincipalImplicit() {
        return netPrincipalImplicit;
    }

    public void setVatPrincipalImplicit(Double vatPrincipalImplicit) {
        this.vatPrincipalImplicit = vatPrincipalImplicit;
    }

    public Double getVatPrincipalImplicit() {
        return vatPrincipalImplicit;
    }

    public void setInterestImplicitRate(Double interestImplicitRate) {
        this.interestImplicitRate = interestImplicitRate;
    }

    public Double getInterestImplicitRate() {
        return interestImplicitRate;
    }

    public void setNetInterestImplicit(Double netInterestImplicit) {
        this.netInterestImplicit = netInterestImplicit;
    }

    public Double getNetInterestImplicit() {
        return netInterestImplicit;
    }

    public void setVatInterestImplicit(Double vatInterestImplicit) {
        this.vatInterestImplicit = vatInterestImplicit;
    }

    public Double getVatInterestImplicit() {
        return vatInterestImplicit;
    }

    public void setOutstandingRental(Double outstandingRental) {
        this.outstandingRental = outstandingRental;
    }

    public Double getOutstandingRental() {
        return outstandingRental;
    }

    public void setOutstandingPrincipal(Double outstandingPrincipal) {
        this.outstandingPrincipal = outstandingPrincipal;
    }

    public Double getOutstandingPrincipal() {
        return outstandingPrincipal;
    }

    public void setOutstandingInterest(Double outstandingInterest) {
        this.outstandingInterest = outstandingInterest;
    }

    public Double getOutstandingInterest() {
        return outstandingInterest;
    }

    public void setInterestPeriodDays(Double interestPeriodDays) {
        this.interestPeriodDays = interestPeriodDays;
    }

    public Double getInterestPeriodDays() {
        return interestPeriodDays;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    public Long getSourceId() {
        return sourceId;
    }

    public void setColourScheme(String colourScheme) {
        this.colourScheme = colourScheme;
    }

    public String getColourScheme() {
        return colourScheme;
    }

    public void setCalcLineId(Long calcLineId) {
        this.calcLineId = calcLineId;
    }

    public Long getCalcLineId() {
        return calcLineId;
    }

    public void setOverdueStatus(String overdueStatus) {
        this.overdueStatus = overdueStatus;
    }

    public String getOverdueStatus() {
        return overdueStatus;
    }

    public void setOverdueDate(Date overdueDate) {
        this.overdueDate = overdueDate;
    }

    public Date getOverdueDate() {
        return overdueDate;
    }

    public void setOverdueMaxDays(int overdueMaxDays) {
        this.overdueMaxDays = overdueMaxDays;
    }

    public int getOverdueMaxDays() {
        return overdueMaxDays;
    }

    public void setOverdueAmount(Double overdueAmount) {
        this.overdueAmount = overdueAmount;
    }

    public Double getOverdueAmount() {
        return overdueAmount;
    }

    public void setOverduePrincipal(Double overduePrincipal) {
        this.overduePrincipal = overduePrincipal;
    }

    public Double getOverduePrincipal() {
        return overduePrincipal;
    }

    public void setOverdueInterest(Double overdueInterest) {
        this.overdueInterest = overdueInterest;
    }

    public Double getOverdueInterest() {
        return overdueInterest;
    }

    public void setReceivedAmount(Double receivedAmount) {
        this.receivedAmount = receivedAmount;
    }

    public Double getReceivedAmount() {
        return receivedAmount;
    }

    public void setReceivedPrincipal(Double receivedPrincipal) {
        this.receivedPrincipal = receivedPrincipal;
    }

    public Double getReceivedPrincipal() {
        return receivedPrincipal;
    }

    public void setReceivedInterest(Double receivedInterest) {
        this.receivedInterest = receivedInterest;
    }

    public Double getReceivedInterest() {
        return receivedInterest;
    }

    public void setWriteoffFlag(String writeoffFlag) {
        this.writeoffFlag = writeoffFlag;
    }

    public String getWriteoffFlag() {
        return writeoffFlag;
    }

    public void setLastReceivedDate(Date lastReceivedDate) {
        this.lastReceivedDate = lastReceivedDate;
    }

    public Date getLastReceivedDate() {
        return lastReceivedDate;
    }

    public void setFullWriteoffDate(Date fullWriteoffDate) {
        this.fullWriteoffDate = fullWriteoffDate;
    }

    public Date getFullWriteoffDate() {
        return fullWriteoffDate;
    }

    public void setPenaltyProcessStatus(String penaltyProcessStatus) {
        this.penaltyProcessStatus = penaltyProcessStatus;
    }

    public String getPenaltyProcessStatus() {
        return penaltyProcessStatus;
    }

    public void setBillingStatus(String billingStatus) {
        this.billingStatus = billingStatus;
    }

    public String getBillingStatus() {
        return billingStatus;
    }

    public void setBillingAmount(Double billingAmount) {
        this.billingAmount = billingAmount;
    }

    public Double getBillingAmount() {
        return billingAmount;
    }

    public void setBillingPrincipal(Double billingPrincipal) {
        this.billingPrincipal = billingPrincipal;
    }

    public Double getBillingPrincipal() {
        return billingPrincipal;
    }

    public void setBillingInterest(Double billingInterest) {
        this.billingInterest = billingInterest;
    }

    public Double getBillingInterest() {
        return billingInterest;
    }

}
