package com.jingrui.jrap.order.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "con_cashflow")
public class Cashflow extends BaseDTO {

     public static final String FIELD_CASHFLOW_ID = "cashflowId";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_CF_TYPE = "cfType";
     public static final String FIELD_CF_DIRECTION = "cfDirection";
     public static final String FIELD_CF_STATUS = "cfStatus";
     public static final String FIELD_TIMES = "times";
     public static final String FIELD_CALC_DATE = "calcDate";
     public static final String FIELD_DUE_DATE = "dueDate";
     public static final String FIELD_DUE_AMOUNT = "dueAmount";
     public static final String FIELD_NET_DUE_AMOUNT = "netDueAmount";
     public static final String FIELD_VAT_DUE_AMOUNT = "vatDueAmount";
     public static final String FIELD_PRINCIPAL = "principal";
     public static final String FIELD_NET_PRINCIPAL = "netPrincipal";
     public static final String FIELD_VAT_PRINCIPAL = "vatPrincipal";
     public static final String FIELD_INTEREST = "interest";
     public static final String FIELD_NET_INTEREST = "netInterest";
     public static final String FIELD_VAT_INTEREST = "vatInterest";
     public static final String FIELD_PRINCIPAL_IMPLICIT_RATE = "principalImplicitRate";
     public static final String FIELD_NET_PRINCIPAL_IMPLICIT = "netPrincipalImplicit";
     public static final String FIELD_VAT_PRINCIPAL_IMPLICIT = "vatPrincipalImplicit";
     public static final String FIELD_INTEREST_IMPLICIT_RATE = "interestImplicitRate";
     public static final String FIELD_NET_INTEREST_IMPLICIT = "netInterestImplicit";
     public static final String FIELD_VAT_INTEREST_IMPLICIT = "vatInterestImplicit";
     public static final String FIELD_OUTSTANDING_RENTAL = "outstandingRental";
     public static final String FIELD_OUTSTANDING_PRINCIPAL = "outstandingPrincipal";
     public static final String FIELD_OUTSTANDING_INTEREST = "outstandingInterest";
     public static final String FIELD_INTEREST_PERIOD_DAYS = "interestPeriodDays";
     public static final String FIELD_SOURCE_TYPE = "sourceType";
     public static final String FIELD_SOURCE_ID = "sourceId";
     public static final String FIELD_COLOUR_SCHEME = "colourScheme";
     public static final String FIELD_CALC_LINE_ID = "calcLineId";
     public static final String FIELD_OVERDUE_STATUS = "overdueStatus";
     public static final String FIELD_OVERDUE_DATE = "overdueDate";
     public static final String FIELD_OVERDUE_MAX_DAYS = "overdueMaxDays";
     public static final String FIELD_OVERDUE_AMOUNT = "overdueAmount";
     public static final String FIELD_OVERDUE_PRINCIPAL = "overduePrincipal";
     public static final String FIELD_OVERDUE_INTEREST = "overdueInterest";
     public static final String FIELD_RECEIVED_AMOUNT = "receivedAmount";
     public static final String FIELD_RECEIVED_PRINCIPAL = "receivedPrincipal";
     public static final String FIELD_RECEIVED_INTEREST = "receivedInterest";
     public static final String FIELD_WRITEOFF_FLAG = "writeoffFlag";
     public static final String FIELD_LAST_RECEIVED_DATE = "lastReceivedDate";
     public static final String FIELD_FULL_WRITEOFF_DATE = "fullWriteoffDate";
     public static final String FIELD_PENALTY_PROCESS_STATUS = "penaltyProcessStatus";
     public static final String FIELD_BILLING_STATUS = "billingStatus";
     public static final String FIELD_BILLING_AMOUNT = "billingAmount";
     public static final String FIELD_BILLING_PRINCIPAL = "billingPrincipal";
     public static final String FIELD_BILLING_INTEREST = "billingInterest";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long cashflowId;

     private Long orderId; //订单ID

     @Length(max = 60)
     private String cfType; //现金流类型

     @Length(max = 60)
     private String cfDirection; //现金流方向（INFLOW/OUTFLOW/NONCASH）

     @Length(max = 60)
     private String cfStatus; //现金流状态（BLOCK/冻结 、RELEASE/下达、CANCEL/取消）

     private Long times; //期数

     private Date calcDate; //计算日

     private Date dueDate; //支付日/到期日

     private Long dueAmount; //应收金额

     private Long netDueAmount; //不含税应收金额

     private Long vatDueAmount; //增值税额

     private Long principal; //应收本金

     private Long netPrincipal; //不含税本金

     private Long vatPrincipal; //本金增值税额

     private Long interest; //应收利息

     private Long netInterest; //不含税利息

     private Long vatInterest; //利息增值税额

     private Long principalImplicitRate; //实际利率法本金

     private Long netPrincipalImplicit; //实际利率法不含税本金

     private Long vatPrincipalImplicit; //实际利率法本金增值税额

     private Long interestImplicitRate; //实际利率法利息

     private Long netInterestImplicit; //实际利率法不含税利息

     private Long vatInterestImplicit; //实际利率法利息增值税额

     private Long outstandingRental; //当期剩余租金

     private Long outstandingPrincipal; //当期剩余本金

     private Long outstandingInterest; //当期剩余利息

     private Long interestPeriodDays; //计息天数（利息期天数）

     @Length(max = 60)
     private String sourceType; //来源类型（CALCULATOR/计算器ET/结清MANUAL/手工DAY_END/日结）

     private Long sourceId; //来源ID

     @Length(max = 60)
     private String colourScheme; //颜色方案

     private Long calcLineId; //计算器行ID

     @Length(max = 60)
     private String overdueStatus; //逾期状态（N 未逾期、Y 已逾期）

     private Date overdueDate; //逾期计算日

     private Long overdueMaxDays; //最大逾期天数

     private Long overdueAmount; //逾期金额

     private Long overduePrincipal; //逾期本金

     private Long overdueInterest; //逾期利息

     private Long receivedAmount; //已收金额

     private Long receivedPrincipal; //已收本金

     private Long receivedInterest; //已收利息

     @Length(max = 60)
     private String writeoffFlag; //核销标志（NOT/PARTIAL/FULL）

     private Date lastReceivedDate; //最后收款日

     private Date fullWriteoffDate; //完全核销日

     @Length(max = 60)
     private String penaltyProcessStatus; //罚金处理状态（NORMAL正常/SUSPEND暂停计算/EXEMPT豁免）

     @Length(max = 60)
     private String billingStatus; //开票状态（NOT/PARTIAL/FULL）

     private Long billingAmount; //开票金额

     private Long billingPrincipal; //本金开票金额

     private Long billingInterest; //利息开票金额

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setCashflowId(Long cashflowId){
         this.cashflowId = cashflowId;
     }

     public Long getCashflowId(){
         return cashflowId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setCfType(String cfType){
         this.cfType = cfType;
     }

     public String getCfType(){
         return cfType;
     }

     public void setCfDirection(String cfDirection){
         this.cfDirection = cfDirection;
     }

     public String getCfDirection(){
         return cfDirection;
     }

     public void setCfStatus(String cfStatus){
         this.cfStatus = cfStatus;
     }

     public String getCfStatus(){
         return cfStatus;
     }

     public void setTimes(Long times){
         this.times = times;
     }

     public Long getTimes(){
         return times;
     }

     public void setCalcDate(Date calcDate){
         this.calcDate = calcDate;
     }

     public Date getCalcDate(){
         return calcDate;
     }

     public void setDueDate(Date dueDate){
         this.dueDate = dueDate;
     }

     public Date getDueDate(){
         return dueDate;
     }

     public void setDueAmount(Long dueAmount){
         this.dueAmount = dueAmount;
     }

     public Long getDueAmount(){
         return dueAmount;
     }

     public void setNetDueAmount(Long netDueAmount){
         this.netDueAmount = netDueAmount;
     }

     public Long getNetDueAmount(){
         return netDueAmount;
     }

     public void setVatDueAmount(Long vatDueAmount){
         this.vatDueAmount = vatDueAmount;
     }

     public Long getVatDueAmount(){
         return vatDueAmount;
     }

     public void setPrincipal(Long principal){
         this.principal = principal;
     }

     public Long getPrincipal(){
         return principal;
     }

     public void setNetPrincipal(Long netPrincipal){
         this.netPrincipal = netPrincipal;
     }

     public Long getNetPrincipal(){
         return netPrincipal;
     }

     public void setVatPrincipal(Long vatPrincipal){
         this.vatPrincipal = vatPrincipal;
     }

     public Long getVatPrincipal(){
         return vatPrincipal;
     }

     public void setInterest(Long interest){
         this.interest = interest;
     }

     public Long getInterest(){
         return interest;
     }

     public void setNetInterest(Long netInterest){
         this.netInterest = netInterest;
     }

     public Long getNetInterest(){
         return netInterest;
     }

     public void setVatInterest(Long vatInterest){
         this.vatInterest = vatInterest;
     }

     public Long getVatInterest(){
         return vatInterest;
     }

     public void setPrincipalImplicitRate(Long principalImplicitRate){
         this.principalImplicitRate = principalImplicitRate;
     }

     public Long getPrincipalImplicitRate(){
         return principalImplicitRate;
     }

     public void setNetPrincipalImplicit(Long netPrincipalImplicit){
         this.netPrincipalImplicit = netPrincipalImplicit;
     }

     public Long getNetPrincipalImplicit(){
         return netPrincipalImplicit;
     }

     public void setVatPrincipalImplicit(Long vatPrincipalImplicit){
         this.vatPrincipalImplicit = vatPrincipalImplicit;
     }

     public Long getVatPrincipalImplicit(){
         return vatPrincipalImplicit;
     }

     public void setInterestImplicitRate(Long interestImplicitRate){
         this.interestImplicitRate = interestImplicitRate;
     }

     public Long getInterestImplicitRate(){
         return interestImplicitRate;
     }

     public void setNetInterestImplicit(Long netInterestImplicit){
         this.netInterestImplicit = netInterestImplicit;
     }

     public Long getNetInterestImplicit(){
         return netInterestImplicit;
     }

     public void setVatInterestImplicit(Long vatInterestImplicit){
         this.vatInterestImplicit = vatInterestImplicit;
     }

     public Long getVatInterestImplicit(){
         return vatInterestImplicit;
     }

     public void setOutstandingRental(Long outstandingRental){
         this.outstandingRental = outstandingRental;
     }

     public Long getOutstandingRental(){
         return outstandingRental;
     }

     public void setOutstandingPrincipal(Long outstandingPrincipal){
         this.outstandingPrincipal = outstandingPrincipal;
     }

     public Long getOutstandingPrincipal(){
         return outstandingPrincipal;
     }

     public void setOutstandingInterest(Long outstandingInterest){
         this.outstandingInterest = outstandingInterest;
     }

     public Long getOutstandingInterest(){
         return outstandingInterest;
     }

     public void setInterestPeriodDays(Long interestPeriodDays){
         this.interestPeriodDays = interestPeriodDays;
     }

     public Long getInterestPeriodDays(){
         return interestPeriodDays;
     }

     public void setSourceType(String sourceType){
         this.sourceType = sourceType;
     }

     public String getSourceType(){
         return sourceType;
     }

     public void setSourceId(Long sourceId){
         this.sourceId = sourceId;
     }

     public Long getSourceId(){
         return sourceId;
     }

     public void setColourScheme(String colourScheme){
         this.colourScheme = colourScheme;
     }

     public String getColourScheme(){
         return colourScheme;
     }

     public void setCalcLineId(Long calcLineId){
         this.calcLineId = calcLineId;
     }

     public Long getCalcLineId(){
         return calcLineId;
     }

     public void setOverdueStatus(String overdueStatus){
         this.overdueStatus = overdueStatus;
     }

     public String getOverdueStatus(){
         return overdueStatus;
     }

     public void setOverdueDate(Date overdueDate){
         this.overdueDate = overdueDate;
     }

     public Date getOverdueDate(){
         return overdueDate;
     }

     public void setOverdueMaxDays(Long overdueMaxDays){
         this.overdueMaxDays = overdueMaxDays;
     }

     public Long getOverdueMaxDays(){
         return overdueMaxDays;
     }

     public void setOverdueAmount(Long overdueAmount){
         this.overdueAmount = overdueAmount;
     }

     public Long getOverdueAmount(){
         return overdueAmount;
     }

     public void setOverduePrincipal(Long overduePrincipal){
         this.overduePrincipal = overduePrincipal;
     }

     public Long getOverduePrincipal(){
         return overduePrincipal;
     }

     public void setOverdueInterest(Long overdueInterest){
         this.overdueInterest = overdueInterest;
     }

     public Long getOverdueInterest(){
         return overdueInterest;
     }

     public void setReceivedAmount(Long receivedAmount){
         this.receivedAmount = receivedAmount;
     }

     public Long getReceivedAmount(){
         return receivedAmount;
     }

     public void setReceivedPrincipal(Long receivedPrincipal){
         this.receivedPrincipal = receivedPrincipal;
     }

     public Long getReceivedPrincipal(){
         return receivedPrincipal;
     }

     public void setReceivedInterest(Long receivedInterest){
         this.receivedInterest = receivedInterest;
     }

     public Long getReceivedInterest(){
         return receivedInterest;
     }

     public void setWriteoffFlag(String writeoffFlag){
         this.writeoffFlag = writeoffFlag;
     }

     public String getWriteoffFlag(){
         return writeoffFlag;
     }

     public void setLastReceivedDate(Date lastReceivedDate){
         this.lastReceivedDate = lastReceivedDate;
     }

     public Date getLastReceivedDate(){
         return lastReceivedDate;
     }

     public void setFullWriteoffDate(Date fullWriteoffDate){
         this.fullWriteoffDate = fullWriteoffDate;
     }

     public Date getFullWriteoffDate(){
         return fullWriteoffDate;
     }

     public void setPenaltyProcessStatus(String penaltyProcessStatus){
         this.penaltyProcessStatus = penaltyProcessStatus;
     }

     public String getPenaltyProcessStatus(){
         return penaltyProcessStatus;
     }

     public void setBillingStatus(String billingStatus){
         this.billingStatus = billingStatus;
     }

     public String getBillingStatus(){
         return billingStatus;
     }

     public void setBillingAmount(Long billingAmount){
         this.billingAmount = billingAmount;
     }

     public Long getBillingAmount(){
         return billingAmount;
     }

     public void setBillingPrincipal(Long billingPrincipal){
         this.billingPrincipal = billingPrincipal;
     }

     public Long getBillingPrincipal(){
         return billingPrincipal;
     }

     public void setBillingInterest(Long billingInterest){
         this.billingInterest = billingInterest;
     }

     public Long getBillingInterest(){
         return billingInterest;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
