package com.jingrui.jrap.order.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import javax.persistence.Transient;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.OrderBy;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "con_guarantor")
public class Guarantor extends BaseDTO {

  public static final String FIELD_GUARANTOR_ID = "guarantorId";
  public static final String FIELD_ORDER_ID = "orderId";
  public static final String FIELD_CUSTOMER_ID = "customerId";
  public static final String FIELD_GUARANTOR_SEQUENCE = "guarantorSequence";
  public static final String FIELD_REMARK = "remark";
  public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
  public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


  @Where
  @Id
  @GeneratedValue
  @OrderBy("desc")
  private Long guarantorId;

  @Where
  private Long orderId; //订单ID

  @Where
  private Long customerId; //客户Id

  @Where
  private Long guarantorSequence; //担保序列

  @Where
  @Length(max = 2147483647)
  private String remark; //备注说明
  @Transient
  @Length(max = 30)
  private String idType; //证件类型（身份证、港澳通行证、军官证、其他、护照、台湾同胞通行证）

  @Transient
  @Length(max = 45)
  private String idNo; //证件号码

  @Transient
  @Length(max = 30)
  private String telphone; //主手机号

  @Transient
  @Length(max = 200)
  private String homeAddress; //户籍住址

  @Transient
  @Length(max = 1)
  private String enabledFlag; //是否启用

  @Transient
  @Length(max = 200)
  private String customerName; //名称

  @Where
  private Long programApplicationId;

  @Where
  private Date programUpdateDate;

  public String getIdType() {
    return idType;
  }

  public void setIdType(String idType) {
    this.idType = idType;
  }

  public String getIdNo() {
    return idNo;
  }

  public void setIdNo(String idNo) {
    this.idNo = idNo;
  }

  public String getTelphone() {
    return telphone;
  }

  public void setTelphone(String telphone) {
    this.telphone = telphone;
  }

  public String getHomeAddress() {
    return homeAddress;
  }

  public void setHomeAddress(String homeAddress) {
    this.homeAddress = homeAddress;
  }

  public String getEnabledFlag() {
    return enabledFlag;
  }

  public void setEnabledFlag(String enabledFlag) {
    this.enabledFlag = enabledFlag;
  }

  public String getCustomerName() {
    return customerName;
  }

  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  public void setGuarantorId(Long guarantorId) {
    this.guarantorId = guarantorId;
  }

  public Long getGuarantorId() {
    return guarantorId;
  }

  public void setOrderId(Long orderId) {
    this.orderId = orderId;
  }

  public Long getOrderId() {
    return orderId;
  }

  public void setCustomerId(Long customerId) {
    this.customerId = customerId;
  }

  public Long getCustomerId() {
    return customerId;
  }

  public void setGuarantorSequence(Long guarantorSequence) {
    this.guarantorSequence = guarantorSequence;
  }

  public Long getGuarantorSequence() {
    return guarantorSequence;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public String getRemark() {
    return remark;
  }

  public void setProgramApplicationId(Long programApplicationId) {
    this.programApplicationId = programApplicationId;
  }

  public Long getProgramApplicationId() {
    return programApplicationId;
  }

  public void setProgramUpdateDate(Date programUpdateDate) {
    this.programUpdateDate = programUpdateDate;
  }

  public Date getProgramUpdateDate() {
    return programUpdateDate;
  }

}
