package com.jingrui.jrap.order.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "con_order")
public class Order extends BaseDTO {

     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_ORDER_CODE = "orderCode";
     public static final String FIELD_DOCUMENT_CATEGORY = "documentCategory";
     public static final String FIELD_DOCUMENT_TYPE = "documentType";
     public static final String FIELD_ORDER_STATUS = "orderStatus";
     public static final String FIELD_PRODUCT_CODE = "productCode";
     public static final String FIELD_BUSINESS_TYPE = "businessType";
     public static final String FIELD_CHANGE_ID = "changeId";
     public static final String FIELD_CUSTOMER_ID = "customerId";
     public static final String FIELD_ITEM_ID = "itemId";
     public static final String FIELD_AGENT_ID = "agentId";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_UNIT_ID = "unitId";
     public static final String FIELD_EMPLOYEE_ID = "employeeId";
     public static final String FIELD_RISK_EMPLOYEE_ID = "riskEmployeeId";
     public static final String FIELD_GUIDE_PRICE = "guidePrice";
     public static final String FIELD_EVALUATION_AMOUNT = "evaluationAmount";
     public static final String FIELD_LEASE_AMOUNT = "leaseAmount";
     public static final String FIELD_FINANCE_AMOUNT = "financeAmount";
     public static final String FIELD_CONTRACT_AMOUNT = "contractAmount";
     public static final String FIELD_NET_FINANCE_AMOUNT = "netFinanceAmount";
     public static final String FIELD_VAT_FINANCE_AMOUNT = "vatFinanceAmount";
     public static final String FIELD_DOWN_PAYMENT = "downPayment";
     public static final String FIELD_NET_DOWN_PAYMENT = "netDownPayment";
     public static final String FIELD_VAT_DOWN_PAYMENT = "vatDownPayment";
     public static final String FIELD_FINAL_PAYMENT = "finalPayment";
     public static final String FIELD_RESIDUAL_VALUE = "residualValue";
     public static final String FIELD_VAT_INPUT = "vatInput";
     public static final String FIELD_LEASE_TIMES = "leaseTimes";
     public static final String FIELD_PAY_TYPE = "payType";
     public static final String FIELD_PAY_TIMES = "payTimes";
     public static final String FIELD_ANNUAL_PAY_TIMES = "annualPayTimes";
     public static final String FIELD_LEASE_TERM = "leaseTerm";
     public static final String FIELD_BASE_RATE = "baseRate";
     public static final String FIELD_INT_RATE = "intRate";
     public static final String FIELD_INT_RATE_IMPLICIT = "intRateImplicit";
     public static final String FIELD_INT_RATE_REAL = "intRateReal";
     public static final String FIELD_INT_RATE_TYPE = "intRateType";
     public static final String FIELD_PLATE_PRICE = "platePrice";
     public static final String FIELD_INSURANCE_AMOUNT = "insuranceAmount";
     public static final String FIELD_MORTGAGE_FEE = "mortgageFee";
     public static final String FIELD_CHARGE = "charge";
     public static final String FIELD_GPS_FEE = "gpsFee";
     public static final String FIELD_PARKING_FEE = "parkingFee";
     public static final String FIELD_PROPERTY_FEE = "propertyFee";
     public static final String FIELD_DOCUMENT_FEE = "documentFee";
     public static final String FIELD_PURCHASE_TAX = "purchaseTax";
     public static final String FIELD_NOTARIAL_FEE = "notarialFee";
     public static final String FIELD_CREDIT_FEE = "creditFee";
     public static final String FIELD_LICENSE_FEE = "licenseFee";
     public static final String FIELD_OTHER_FEE_01 = "otherFee01";
     public static final String FIELD_OTHER_FEE_02 = "otherFee02";
     public static final String FIELD_OTHER_FEE_03 = "otherFee03";
     public static final String FIELD_OTHER_FEE_04 = "otherFee04";
     public static final String FIELD_OTHER_FEE_05 = "otherFee05";
     public static final String FIELD_TOTAL_FEE = "totalFee";
     public static final String FIELD_NET_TOTAL_FEE = "netTotalFee";
     public static final String FIELD_VAT_TOTAL_FEE = "vatTotalFee";
     public static final String FIELD_VIOLATION_DEPOSIT = "violationDeposit";
     public static final String FIELD_INSURANCE_DEPOSIT = "insuranceDeposit";
     public static final String FIELD_ANNUAL_SURVEY_DEPOSIT = "annualSurveyDeposit";
     public static final String FIELD_OTHER_DEPOSIT_01 = "otherDeposit01";
     public static final String FIELD_OTHER_DEPOSIT_02 = "otherDeposit02";
     public static final String FIELD_OTHER_DEPOSIT_03 = "otherDeposit03";
     public static final String FIELD_OTHER_DEPOSIT_04 = "otherDeposit04";
     public static final String FIELD_OTHER_DEPOSIT_05 = "otherDeposit05";
     public static final String FIELD_TOTAL_DEPOSIT = "totalDeposit";
     public static final String FIELD_TOTAL_RENTAL = "totalRental";
     public static final String FIELD_NET_TOTAL_RENTAL = "netTotalRental";
     public static final String FIELD_VAT_TOTAL_RENTAL = "vatTotalRental";
     public static final String FIELD_TOTAL_INTEREST = "totalInterest";
     public static final String FIELD_NET_TOTAL_INTEREST = "netTotalInterest";
     public static final String FIELD_VAT_TOTAL_INTEREST = "vatTotalInterest";
     public static final String FIELD_FINANCE_INCOME = "financeIncome";
     public static final String FIELD_NET_FINANCE_INCOME = "netFinanceIncome";
     public static final String FIELD_VAT_FINANCE_INCOME = "vatFinanceIncome";
     public static final String FIELD_RECEIVE_RENTAL = "receiveRental";
     public static final String FIELD_RECEIVE_PRINCIPAL = "receivePrincipal";
     public static final String FIELD_RECEIVE_INTEREST = "receiveInterest";
     public static final String FIELD_DEPOSIT_BALANCE = "depositBalance";
     public static final String FIELD_SUBMIT_DATE = "submitDate";
     public static final String FIELD_APPROVED_DATE = "approvedDate";
     public static final String FIELD_REFUSE_DATE = "refuseDate";
     public static final String FIELD_SIGNING_DATE = "signingDate";
     public static final String FIELD_SIGNED_DATE = "signedDate";
     public static final String FIELD_PAYMENT_DATE = "paymentDate";
     public static final String FIELD_DELIVERY_DATE = "deliveryDate";
     public static final String FIELD_INCEPT_DATE = "inceptDate";
     public static final String FIELD_FINISHED_DATE = "finishedDate";
     public static final String FIELD_START_DATE = "startDate";
     public static final String FIELD_END_DATE = "endDate";
     public static final String FIELD_OVERDUE_FLAG = "overdueFlag";
     public static final String FIELD_TOTAL_OVERDUE = "totalOverdue";
     public static final String FIELD_BILL_STATUS = "billStatus";
     public static final String FIELD_DELIVERY_STATUS = "deliveryStatus";
     public static final String FIELD_INT_RATE_PRECISION = "intRatePrecision";
     public static final String FIELD_IRR = "irr";
     public static final String FIELD_IRR_AFTER_TAX = "irrAfterTax";
     public static final String FIELD_PMT = "pmt";
     public static final String FIELD_PMT_FIRST = "pmtFirst";
     public static final String FIELD_CALC_PROMPT = "calcPrompt";
     public static final String FIELD_CALC_PROMPT_MSG = "calcPromptMsg";
     public static final String FIELD_SOURCE_TYPE = "sourceType";
     public static final String FIELD_SOURCE_ID = "sourceId";
     public static final String FIELD_USER_STATUS_1 = "userStatus1";
     public static final String FIELD_USER_STATUS_2 = "userStatus2";
     public static final String FIELD_DATA_CLASS = "dataClass";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long orderId;

     @NotEmpty
     @Length(max = 60)
     private String orderCode; //订单编号

     @NotEmpty
     @Length(max = 60)
     private String documentCategory; //单据类别

     @NotEmpty
     @Length(max = 60)
     private String documentType; //单据类型

     @NotEmpty
     @Length(max = 60)
     private String orderStatus; //订单状态

     @Length(max = 60)
     private String productCode; //产品编号

     @Length(max = 60)
     private String businessType; //业务类型

     private Long changeId; //商机ID

     private Long customerId; //客户ID

     private Long itemId; //租赁物ID

     private Long agentId; //供应商ID

     private Long companyId; //公司ID

     private Long unitId; //机构ID

     private Long employeeId; //业务员ID

     private Long riskEmployeeId; //风控员ID

     private Long guidePrice; //建议价

     private Long evaluationAmount; //评估价

     private Long leaseAmount; //租赁物价款

     private Long financeAmount; //融资金额

     private Long contractAmount; //合同总额（首付+各项费用+租金+尾款+留购价款)

     private Long netFinanceAmount; //不含税融资额

     private Long vatFinanceAmount; //融资额增值税

     private Long downPayment; //首付款

     private Long netDownPayment; //不含税首付金额

     private Long vatDownPayment; //首付款税额

     private Long finalPayment; //尾款

     private Long residualValue; //留购价款

     private Long vatInput; //进项增值税额

     private Long leaseTimes; //租赁期数

     @Length(max = 1)
     private String payType; //支付类型（1/先付 0/后付）

     private Long payTimes; //支付期数

     private Long annualPayTimes; //支付频率（年）

     private Long leaseTerm; //租赁期限

     private Long baseRate; //基准利率

     private Long intRate; //租赁利率

     private Long intRateImplicit; //租赁利率（实际）

     private Long intRateReal; //税后实际利率

     @Length(max = 60)
     private String intRateType; //利率类型：浮动/FLOATING 固定/FIXED

     private Long platePrice; //牌照费

     private Long insuranceAmount; //保险费

     private Long mortgageFee; //抵押费

     private Long charge; //手续费

     private Long gpsFee; //GPS费

     private Long parkingFee; //停车费

     private Long propertyFee; //产调费

     private Long documentFee; //查档费

     private Long purchaseTax; //购置税

     private Long notarialFee; //公证费

     private Long creditFee; //征信费

     private Long licenseFee; //上牌费

     private Long otherFee01; //其他费用01

     private Long otherFee02; //其他费用02

     private Long otherFee03; //其他费用03

     private Long otherFee04; //其他费用04

     private Long otherFee05; //其他费用05

     private Long totalFee; //总费用

     private Long netTotalFee; //不含税费用金额

     private Long vatTotalFee; //费用增值税额

     private Long violationDeposit; //违章押金

     private Long insuranceDeposit; //保险押金

     private Long annualSurveyDeposit; //年检押金

     private Long otherDeposit01; //其他押金01

     private Long otherDeposit02; //其他押金02

     private Long otherDeposit03; //其他押金03

     private Long otherDeposit04; //其他押金04

     private Long otherDeposit05; //其他押金05

     private Long totalDeposit; //总押金

     private Long totalRental; //总租金

     private Long netTotalRental; //不含税租金

     private Long vatTotalRental; //租金增值税额

     private Long totalInterest; //利息总额

     private Long netTotalInterest; //不含税利息

     private Long vatTotalInterest; //利息增值税额

     private Long financeIncome; //租赁收入

     private Long netFinanceIncome; //不含税租赁收入

     private Long vatFinanceIncome; //租赁收入税额

     private Long receiveRental; //已收租金

     private Long receivePrincipal; //已收本金

     private Long receiveInterest; //已收利息

     private Long depositBalance; //押金余额

     private Date submitDate; //申请日期

     private Date approvedDate; //通过日期

     private Date refuseDate; //拒绝日期

     private Date signingDate; //签约申请日期

     private Date signedDate; //签约日期

     private Date paymentDate; //放款日期

     private Date deliveryDate; //提车日期

     private Date inceptDate; //起租日期

     private Date finishedDate; //过户日期

     private Date startDate; //开始日期

     private Date endDate; //结束日期

     @Length(max = 1)
     private String overdueFlag; //逾期状态

     private Long totalOverdue; //逾期天数合计

     @Length(max = 60)
     private String billStatus; //开票状态（NOT/PARTIAL/FULL）

     @Length(max = 1)
     private String deliveryStatus; //提前状态

     private Long intRatePrecision; //利率精度

     private Long irr; //内部收益率

     private Long irrAfterTax; //税后内部收益率

     private Long pmt; //等额本息租金

     private Long pmtFirst; //等额本息租金（首期）

     @Length(max = 100)
     private String calcPrompt; //租金计算结果提示

     @Length(max = 500)
     private String calcPromptMsg; //租金计算结果提示信息

     @Length(max = 60)
     private String sourceType; //订单来源

     private Long sourceId; //源ID

     @Length(max = 60)
     private String userStatus1; //订单状态01

     @Length(max = 60)
     private String userStatus2; //订单状态01

     @Length(max = 60)
     private String dataClass; //数据种类（NORMAL/HISTORY/CHANGE）

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setOrderCode(String orderCode){
         this.orderCode = orderCode;
     }

     public String getOrderCode(){
         return orderCode;
     }

     public void setDocumentCategory(String documentCategory){
         this.documentCategory = documentCategory;
     }

     public String getDocumentCategory(){
         return documentCategory;
     }

     public void setDocumentType(String documentType){
         this.documentType = documentType;
     }

     public String getDocumentType(){
         return documentType;
     }

     public void setOrderStatus(String orderStatus){
         this.orderStatus = orderStatus;
     }

     public String getOrderStatus(){
         return orderStatus;
     }

     public void setProductCode(String productCode){
         this.productCode = productCode;
     }

     public String getProductCode(){
         return productCode;
     }

     public void setBusinessType(String businessType){
         this.businessType = businessType;
     }

     public String getBusinessType(){
         return businessType;
     }

     public void setChangeId(Long changeId){
         this.changeId = changeId;
     }

     public Long getChangeId(){
         return changeId;
     }

     public void setCustomerId(Long customerId){
         this.customerId = customerId;
     }

     public Long getCustomerId(){
         return customerId;
     }

     public void setItemId(Long itemId){
         this.itemId = itemId;
     }

     public Long getItemId(){
         return itemId;
     }

     public void setAgentId(Long agentId){
         this.agentId = agentId;
     }

     public Long getAgentId(){
         return agentId;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setUnitId(Long unitId){
         this.unitId = unitId;
     }

     public Long getUnitId(){
         return unitId;
     }

     public void setEmployeeId(Long employeeId){
         this.employeeId = employeeId;
     }

     public Long getEmployeeId(){
         return employeeId;
     }

     public void setRiskEmployeeId(Long riskEmployeeId){
         this.riskEmployeeId = riskEmployeeId;
     }

     public Long getRiskEmployeeId(){
         return riskEmployeeId;
     }

     public void setGuidePrice(Long guidePrice){
         this.guidePrice = guidePrice;
     }

     public Long getGuidePrice(){
         return guidePrice;
     }

     public void setEvaluationAmount(Long evaluationAmount){
         this.evaluationAmount = evaluationAmount;
     }

     public Long getEvaluationAmount(){
         return evaluationAmount;
     }

     public void setLeaseAmount(Long leaseAmount){
         this.leaseAmount = leaseAmount;
     }

     public Long getLeaseAmount(){
         return leaseAmount;
     }

     public void setFinanceAmount(Long financeAmount){
         this.financeAmount = financeAmount;
     }

     public Long getFinanceAmount(){
         return financeAmount;
     }

     public void setContractAmount(Long contractAmount){
         this.contractAmount = contractAmount;
     }

     public Long getContractAmount(){
         return contractAmount;
     }

     public void setNetFinanceAmount(Long netFinanceAmount){
         this.netFinanceAmount = netFinanceAmount;
     }

     public Long getNetFinanceAmount(){
         return netFinanceAmount;
     }

     public void setVatFinanceAmount(Long vatFinanceAmount){
         this.vatFinanceAmount = vatFinanceAmount;
     }

     public Long getVatFinanceAmount(){
         return vatFinanceAmount;
     }

     public void setDownPayment(Long downPayment){
         this.downPayment = downPayment;
     }

     public Long getDownPayment(){
         return downPayment;
     }

     public void setNetDownPayment(Long netDownPayment){
         this.netDownPayment = netDownPayment;
     }

     public Long getNetDownPayment(){
         return netDownPayment;
     }

     public void setVatDownPayment(Long vatDownPayment){
         this.vatDownPayment = vatDownPayment;
     }

     public Long getVatDownPayment(){
         return vatDownPayment;
     }

     public void setFinalPayment(Long finalPayment){
         this.finalPayment = finalPayment;
     }

     public Long getFinalPayment(){
         return finalPayment;
     }

     public void setResidualValue(Long residualValue){
         this.residualValue = residualValue;
     }

     public Long getResidualValue(){
         return residualValue;
     }

     public void setVatInput(Long vatInput){
         this.vatInput = vatInput;
     }

     public Long getVatInput(){
         return vatInput;
     }

     public void setLeaseTimes(Long leaseTimes){
         this.leaseTimes = leaseTimes;
     }

     public Long getLeaseTimes(){
         return leaseTimes;
     }

     public void setPayType(String payType){
         this.payType = payType;
     }

     public String getPayType(){
         return payType;
     }

     public void setPayTimes(Long payTimes){
         this.payTimes = payTimes;
     }

     public Long getPayTimes(){
         return payTimes;
     }

     public void setAnnualPayTimes(Long annualPayTimes){
         this.annualPayTimes = annualPayTimes;
     }

     public Long getAnnualPayTimes(){
         return annualPayTimes;
     }

     public void setLeaseTerm(Long leaseTerm){
         this.leaseTerm = leaseTerm;
     }

     public Long getLeaseTerm(){
         return leaseTerm;
     }

     public void setBaseRate(Long baseRate){
         this.baseRate = baseRate;
     }

     public Long getBaseRate(){
         return baseRate;
     }

     public void setIntRate(Long intRate){
         this.intRate = intRate;
     }

     public Long getIntRate(){
         return intRate;
     }

     public void setIntRateImplicit(Long intRateImplicit){
         this.intRateImplicit = intRateImplicit;
     }

     public Long getIntRateImplicit(){
         return intRateImplicit;
     }

     public void setIntRateReal(Long intRateReal){
         this.intRateReal = intRateReal;
     }

     public Long getIntRateReal(){
         return intRateReal;
     }

     public void setIntRateType(String intRateType){
         this.intRateType = intRateType;
     }

     public String getIntRateType(){
         return intRateType;
     }

     public void setPlatePrice(Long platePrice){
         this.platePrice = platePrice;
     }

     public Long getPlatePrice(){
         return platePrice;
     }

     public void setInsuranceAmount(Long insuranceAmount){
         this.insuranceAmount = insuranceAmount;
     }

     public Long getInsuranceAmount(){
         return insuranceAmount;
     }

     public void setMortgageFee(Long mortgageFee){
         this.mortgageFee = mortgageFee;
     }

     public Long getMortgageFee(){
         return mortgageFee;
     }

     public void setCharge(Long charge){
         this.charge = charge;
     }

     public Long getCharge(){
         return charge;
     }

     public void setGpsFee(Long gpsFee){
         this.gpsFee = gpsFee;
     }

     public Long getGpsFee(){
         return gpsFee;
     }

     public void setParkingFee(Long parkingFee){
         this.parkingFee = parkingFee;
     }

     public Long getParkingFee(){
         return parkingFee;
     }

     public void setPropertyFee(Long propertyFee){
         this.propertyFee = propertyFee;
     }

     public Long getPropertyFee(){
         return propertyFee;
     }

     public void setDocumentFee(Long documentFee){
         this.documentFee = documentFee;
     }

     public Long getDocumentFee(){
         return documentFee;
     }

     public void setPurchaseTax(Long purchaseTax){
         this.purchaseTax = purchaseTax;
     }

     public Long getPurchaseTax(){
         return purchaseTax;
     }

     public void setNotarialFee(Long notarialFee){
         this.notarialFee = notarialFee;
     }

     public Long getNotarialFee(){
         return notarialFee;
     }

     public void setCreditFee(Long creditFee){
         this.creditFee = creditFee;
     }

     public Long getCreditFee(){
         return creditFee;
     }

     public void setLicenseFee(Long licenseFee){
         this.licenseFee = licenseFee;
     }

     public Long getLicenseFee(){
         return licenseFee;
     }

     public void setOtherFee01(Long otherFee01){
         this.otherFee01 = otherFee01;
     }

     public Long getOtherFee01(){
         return otherFee01;
     }

     public void setOtherFee02(Long otherFee02){
         this.otherFee02 = otherFee02;
     }

     public Long getOtherFee02(){
         return otherFee02;
     }

     public void setOtherFee03(Long otherFee03){
         this.otherFee03 = otherFee03;
     }

     public Long getOtherFee03(){
         return otherFee03;
     }

     public void setOtherFee04(Long otherFee04){
         this.otherFee04 = otherFee04;
     }

     public Long getOtherFee04(){
         return otherFee04;
     }

     public void setOtherFee05(Long otherFee05){
         this.otherFee05 = otherFee05;
     }

     public Long getOtherFee05(){
         return otherFee05;
     }

     public void setTotalFee(Long totalFee){
         this.totalFee = totalFee;
     }

     public Long getTotalFee(){
         return totalFee;
     }

     public void setNetTotalFee(Long netTotalFee){
         this.netTotalFee = netTotalFee;
     }

     public Long getNetTotalFee(){
         return netTotalFee;
     }

     public void setVatTotalFee(Long vatTotalFee){
         this.vatTotalFee = vatTotalFee;
     }

     public Long getVatTotalFee(){
         return vatTotalFee;
     }

     public void setViolationDeposit(Long violationDeposit){
         this.violationDeposit = violationDeposit;
     }

     public Long getViolationDeposit(){
         return violationDeposit;
     }

     public void setInsuranceDeposit(Long insuranceDeposit){
         this.insuranceDeposit = insuranceDeposit;
     }

     public Long getInsuranceDeposit(){
         return insuranceDeposit;
     }

     public void setAnnualSurveyDeposit(Long annualSurveyDeposit){
         this.annualSurveyDeposit = annualSurveyDeposit;
     }

     public Long getAnnualSurveyDeposit(){
         return annualSurveyDeposit;
     }

     public void setOtherDeposit01(Long otherDeposit01){
         this.otherDeposit01 = otherDeposit01;
     }

     public Long getOtherDeposit01(){
         return otherDeposit01;
     }

     public void setOtherDeposit02(Long otherDeposit02){
         this.otherDeposit02 = otherDeposit02;
     }

     public Long getOtherDeposit02(){
         return otherDeposit02;
     }

     public void setOtherDeposit03(Long otherDeposit03){
         this.otherDeposit03 = otherDeposit03;
     }

     public Long getOtherDeposit03(){
         return otherDeposit03;
     }

     public void setOtherDeposit04(Long otherDeposit04){
         this.otherDeposit04 = otherDeposit04;
     }

     public Long getOtherDeposit04(){
         return otherDeposit04;
     }

     public void setOtherDeposit05(Long otherDeposit05){
         this.otherDeposit05 = otherDeposit05;
     }

     public Long getOtherDeposit05(){
         return otherDeposit05;
     }

     public void setTotalDeposit(Long totalDeposit){
         this.totalDeposit = totalDeposit;
     }

     public Long getTotalDeposit(){
         return totalDeposit;
     }

     public void setTotalRental(Long totalRental){
         this.totalRental = totalRental;
     }

     public Long getTotalRental(){
         return totalRental;
     }

     public void setNetTotalRental(Long netTotalRental){
         this.netTotalRental = netTotalRental;
     }

     public Long getNetTotalRental(){
         return netTotalRental;
     }

     public void setVatTotalRental(Long vatTotalRental){
         this.vatTotalRental = vatTotalRental;
     }

     public Long getVatTotalRental(){
         return vatTotalRental;
     }

     public void setTotalInterest(Long totalInterest){
         this.totalInterest = totalInterest;
     }

     public Long getTotalInterest(){
         return totalInterest;
     }

     public void setNetTotalInterest(Long netTotalInterest){
         this.netTotalInterest = netTotalInterest;
     }

     public Long getNetTotalInterest(){
         return netTotalInterest;
     }

     public void setVatTotalInterest(Long vatTotalInterest){
         this.vatTotalInterest = vatTotalInterest;
     }

     public Long getVatTotalInterest(){
         return vatTotalInterest;
     }

     public void setFinanceIncome(Long financeIncome){
         this.financeIncome = financeIncome;
     }

     public Long getFinanceIncome(){
         return financeIncome;
     }

     public void setNetFinanceIncome(Long netFinanceIncome){
         this.netFinanceIncome = netFinanceIncome;
     }

     public Long getNetFinanceIncome(){
         return netFinanceIncome;
     }

     public void setVatFinanceIncome(Long vatFinanceIncome){
         this.vatFinanceIncome = vatFinanceIncome;
     }

     public Long getVatFinanceIncome(){
         return vatFinanceIncome;
     }

     public void setReceiveRental(Long receiveRental){
         this.receiveRental = receiveRental;
     }

     public Long getReceiveRental(){
         return receiveRental;
     }

     public void setReceivePrincipal(Long receivePrincipal){
         this.receivePrincipal = receivePrincipal;
     }

     public Long getReceivePrincipal(){
         return receivePrincipal;
     }

     public void setReceiveInterest(Long receiveInterest){
         this.receiveInterest = receiveInterest;
     }

     public Long getReceiveInterest(){
         return receiveInterest;
     }

     public void setDepositBalance(Long depositBalance){
         this.depositBalance = depositBalance;
     }

     public Long getDepositBalance(){
         return depositBalance;
     }

     public void setSubmitDate(Date submitDate){
         this.submitDate = submitDate;
     }

     public Date getSubmitDate(){
         return submitDate;
     }

     public void setApprovedDate(Date approvedDate){
         this.approvedDate = approvedDate;
     }

     public Date getApprovedDate(){
         return approvedDate;
     }

     public void setRefuseDate(Date refuseDate){
         this.refuseDate = refuseDate;
     }

     public Date getRefuseDate(){
         return refuseDate;
     }

     public void setSigningDate(Date signingDate){
         this.signingDate = signingDate;
     }

     public Date getSigningDate(){
         return signingDate;
     }

     public void setSignedDate(Date signedDate){
         this.signedDate = signedDate;
     }

     public Date getSignedDate(){
         return signedDate;
     }

     public void setPaymentDate(Date paymentDate){
         this.paymentDate = paymentDate;
     }

     public Date getPaymentDate(){
         return paymentDate;
     }

     public void setDeliveryDate(Date deliveryDate){
         this.deliveryDate = deliveryDate;
     }

     public Date getDeliveryDate(){
         return deliveryDate;
     }

     public void setInceptDate(Date inceptDate){
         this.inceptDate = inceptDate;
     }

     public Date getInceptDate(){
         return inceptDate;
     }

     public void setFinishedDate(Date finishedDate){
         this.finishedDate = finishedDate;
     }

     public Date getFinishedDate(){
         return finishedDate;
     }

     public void setStartDate(Date startDate){
         this.startDate = startDate;
     }

     public Date getStartDate(){
         return startDate;
     }

     public void setEndDate(Date endDate){
         this.endDate = endDate;
     }

     public Date getEndDate(){
         return endDate;
     }

     public void setOverdueFlag(String overdueFlag){
         this.overdueFlag = overdueFlag;
     }

     public String getOverdueFlag(){
         return overdueFlag;
     }

     public void setTotalOverdue(Long totalOverdue){
         this.totalOverdue = totalOverdue;
     }

     public Long getTotalOverdue(){
         return totalOverdue;
     }

     public void setBillStatus(String billStatus){
         this.billStatus = billStatus;
     }

     public String getBillStatus(){
         return billStatus;
     }

     public void setDeliveryStatus(String deliveryStatus){
         this.deliveryStatus = deliveryStatus;
     }

     public String getDeliveryStatus(){
         return deliveryStatus;
     }

     public void setIntRatePrecision(Long intRatePrecision){
         this.intRatePrecision = intRatePrecision;
     }

     public Long getIntRatePrecision(){
         return intRatePrecision;
     }

     public void setIrr(Long irr){
         this.irr = irr;
     }

     public Long getIrr(){
         return irr;
     }

     public void setIrrAfterTax(Long irrAfterTax){
         this.irrAfterTax = irrAfterTax;
     }

     public Long getIrrAfterTax(){
         return irrAfterTax;
     }

     public void setPmt(Long pmt){
         this.pmt = pmt;
     }

     public Long getPmt(){
         return pmt;
     }

     public void setPmtFirst(Long pmtFirst){
         this.pmtFirst = pmtFirst;
     }

     public Long getPmtFirst(){
         return pmtFirst;
     }

     public void setCalcPrompt(String calcPrompt){
         this.calcPrompt = calcPrompt;
     }

     public String getCalcPrompt(){
         return calcPrompt;
     }

     public void setCalcPromptMsg(String calcPromptMsg){
         this.calcPromptMsg = calcPromptMsg;
     }

     public String getCalcPromptMsg(){
         return calcPromptMsg;
     }

     public void setSourceType(String sourceType){
         this.sourceType = sourceType;
     }

     public String getSourceType(){
         return sourceType;
     }

     public void setSourceId(Long sourceId){
         this.sourceId = sourceId;
     }

     public Long getSourceId(){
         return sourceId;
     }

     public void setUserStatus1(String userStatus1){
         this.userStatus1 = userStatus1;
     }

     public String getUserStatus1(){
         return userStatus1;
     }

     public void setUserStatus2(String userStatus2){
         this.userStatus2 = userStatus2;
     }

     public String getUserStatus2(){
         return userStatus2;
     }

     public void setDataClass(String dataClass){
         this.dataClass = dataClass;
     }

     public String getDataClass(){
         return dataClass;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
