package com.jingrui.jrap.order.dto;

/**Auto Generated By Jrap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.jingrui.jrap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "con_order_cycle")
public class OrderCycle extends BaseDTO {

     public static final String FIELD_CYCLE_ID = "cycleId";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_STATUS_DATE = "statusDate";
     public static final String FIELD_CHANGER = "changer";
     public static final String FIELD_PARENT_CYCLE_ID = "parentCycleId";
     public static final String FIELD_CONTENT = "content";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long cycleId;

     private Long orderId; //订单ID

     @Length(max = 60)
     private String status; //订单状态

     private Date statusDate; //状态时间

     private Long changer; //修改人

     private Long parentCycleId; //上一节点ID

     @Length(max = 200)
     private String content; //备注

     @Length(max = 2147483647)
     private String remark; //备注说明

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setCycleId(Long cycleId){
         this.cycleId = cycleId;
     }

     public Long getCycleId(){
         return cycleId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setStatusDate(Date statusDate){
         this.statusDate = statusDate;
     }

     public Date getStatusDate(){
         return statusDate;
     }

     public void setChanger(Long changer){
         this.changer = changer;
     }

     public Long getChanger(){
         return changer;
     }

     public void setParentCycleId(Long parentCycleId){
         this.parentCycleId = parentCycleId;
     }

     public Long getParentCycleId(){
         return parentCycleId;
     }

     public void setContent(String content){
         this.content = content;
     }

     public String getContent(){
         return content;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
