/*
 * *
 *  @file com.maddyhome.idea.copyright.pattern.JavaCopyrightVariablesProvider$1@37337cec$
 *  @CopyRight (C) 2018 ZheJiangJingRui Co. Ltd.
 *  @brief JingRui Application Platform
 *  @author $name$
 *  @email yulong.yuan@jr-info.cn
 *  @date $date$
 * /
 */

package com.jingrui.jrap.fnd.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import com.jingrui.jrap.core.BaseConstants;
import com.jingrui.jrap.core.annotation.MultiLanguageField;
import com.jingrui.jrap.hr.dto.Position;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Comparison;
import com.jingrui.jrap.mybatis.common.query.JoinCode;
import com.jingrui.jrap.mybatis.common.query.JoinColumn;
import com.jingrui.jrap.mybatis.common.query.JoinOn;
import com.jingrui.jrap.mybatis.common.query.Where;
import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.persistence.criteria.JoinType;
import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "fnd_company_limit")
public class CompanyLimit extends BaseDTO {

    public static final String FIELD_LIMIT_ID = "limitId";
    public static final String FIELD_LIMIT_TYPE = "limitType";
    public static final String FIELD_COMPANY_ID = "companyId";
    public static final String FIELD_LIMIT_COMPANY_ID = "limitCompanyId";
    public static final String FIELD_LIMIT_DATE = "limitDate";
    public static final String FIELD_GOOD_ID = "goodId";
    public static final String FIELD_ORDER_ID = "orderId";
    public static final String FIELD_LIMIT_AMOUNT = "limitAmount";
    public static final String FIELD_BALANCE = "balance";
    public static final String FIELD_LIMIT_NOTE = "limitNote";
    public static final String FIELD_ENABLED_FLAG = "enabledFlag";
    public static final String FIELD_START_DATE = "startDate";
    public static final String FIELD_END_DATE = "endDate";
    public static final String FIELD_REMARK = "remark";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


    @Id
    @GeneratedValue
    private Long limitId;

    @Length(max = 60)
    private String limitType; //授信类型

    private Long companyId; //商户ID

    private Long limitCompanyId; //资方ID

    private Date limitDate; //授信日期

    private Long goodId; //商品ID

    private Long orderId; //订单ID

    private Long limitAmount; //授信额度

    private Long balance; //可用额度

    @Length(max = 200)
    private String limitNote; //备注

    @Length(max = 1)
    private String enabledFlag; //启用标识

    private Date startDate; //有效期从

    private Date endDate; //有效期至

    @Length(max = 2147483647)
    private String remark; //备注说明

    private Long programApplicationId;

    private Date programUpdateDate;

    @Transient
    private String companyCode;

    @Transient
    private String companyType;

    @Transient
    private String companyTypeName;

    @Transient
    private String address;

    @Transient
    private Long companyLevelId;

    @Transient
    private String companyLevelName;

    @Transient
    private Long parentCompanyId;

    @Transient
    private Long chiefPositionId;

    @Transient
    private Date startDateActive;

    @Transient
    private Date endDateActive;

    @Transient
    private String companyShortName;

    @Transient
    private String companyFullName;

    @Transient
    private String zipcode;

    @Transient
    private String fax;

    @Transient
    private String phone;

    @Transient
    private String contactPerson;

    @Transient
    private String parentCompanyName;

    @Transient
    private String positionName;

    @Transient
    private String status;  //商户状态

    @Transient
    private String companyClass; // 商户属性

    @Transient
    private List<Long> companyIds;//

    @Transient
    private List<CompanyLimit> companyLimits; //资方信息

    public List<CompanyLimit> getCompanyLimits() {
        return companyLimits;
    }

    public void setCompanyLimits(List<CompanyLimit> companyLimits) {
        this.companyLimits = companyLimits;
    }

    public String getCompanyCode() {
        return companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    public String getCompanyType() {
        return companyType;
    }

    public void setCompanyType(String companyType) {
        this.companyType = companyType;
    }

    public String getCompanyTypeName() {
        return companyTypeName;
    }

    public void setCompanyTypeName(String companyTypeName) {
        this.companyTypeName = companyTypeName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Long getCompanyLevelId() {
        return companyLevelId;
    }

    public void setCompanyLevelId(Long companyLevelId) {
        this.companyLevelId = companyLevelId;
    }

    public String getCompanyLevelName() {
        return companyLevelName;
    }

    public void setCompanyLevelName(String companyLevelName) {
        this.companyLevelName = companyLevelName;
    }

    public Long getParentCompanyId() {
        return parentCompanyId;
    }

    public void setParentCompanyId(Long parentCompanyId) {
        this.parentCompanyId = parentCompanyId;
    }

    public Long getChiefPositionId() {
        return chiefPositionId;
    }

    public void setChiefPositionId(Long chiefPositionId) {
        this.chiefPositionId = chiefPositionId;
    }

    public Date getStartDateActive() {
        return startDateActive;
    }

    public void setStartDateActive(Date startDateActive) {
        this.startDateActive = startDateActive;
    }

    public Date getEndDateActive() {
        return endDateActive;
    }

    public void setEndDateActive(Date endDateActive) {
        this.endDateActive = endDateActive;
    }

    public String getCompanyShortName() {
        return companyShortName;
    }

    public void setCompanyShortName(String companyShortName) {
        this.companyShortName = companyShortName;
    }

    public String getCompanyFullName() {
        return companyFullName;
    }

    public void setCompanyFullName(String companyFullName) {
        this.companyFullName = companyFullName;
    }

    public String getZipcode() {
        return zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getContactPerson() {
        return contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    public String getParentCompanyName() {
        return parentCompanyName;
    }

    public void setParentCompanyName(String parentCompanyName) {
        this.parentCompanyName = parentCompanyName;
    }

    public String getPositionName() {
        return positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCompanyClass() {
        return companyClass;
    }

    public void setCompanyClass(String companyClass) {
        this.companyClass = companyClass;
    }

    public List<Long> getCompanyIds() {
        return companyIds;
    }

    public void setCompanyIds(List<Long> companyIds) {
        this.companyIds = companyIds;
    }

    public void setLimitId(Long limitId) {
        this.limitId = limitId;
    }

    public Long getLimitId() {
        return limitId;
    }

    public void setLimitType(String limitType) {
        this.limitType = limitType;
    }

    public String getLimitType() {
        return limitType;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setLimitCompanyId(Long limitCompanyId) {
        this.limitCompanyId = limitCompanyId;
    }

    public Long getLimitCompanyId() {
        return limitCompanyId;
    }

    public void setLimitDate(Date limitDate) {
        this.limitDate = limitDate;
    }

    public Date getLimitDate() {
        return limitDate;
    }

    public void setGoodId(Long goodId) {
        this.goodId = goodId;
    }

    public Long getGoodId() {
        return goodId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setLimitAmount(Long limitAmount) {
        this.limitAmount = limitAmount;
    }

    public Long getLimitAmount() {
        return limitAmount;
    }

    public void setBalance(Long balance) {
        this.balance = balance;
    }

    public Long getBalance() {
        return balance;
    }

    public void setLimitNote(String limitNote) {
        this.limitNote = limitNote;
    }

    public String getLimitNote() {
        return limitNote;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getRemark() {
        return remark;
    }

    public void setProgramApplicationId(Long programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    public Long getProgramApplicationId() {
        return programApplicationId;
    }

    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

}
