/*
 * *
 *  @file com.maddyhome.idea.copyright.pattern.JavaCopyrightVariablesProvider$1@704b3526$
 *  @CopyRight (C) 2018 ZheJiangJingRui Co. Ltd.
 *  @brief JingRui Application Platform
 *  @author $name$
 *  @email yulong.yuan@jr-info.cn
 *  @date $date$
 * /
 */

package com.jingrui.jrap.fnd.dto;

/**Auto Generated By Jrap Code Generator**/

import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.Where;
import com.jingrui.jrap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "fnd_limit_change")
public class LimitChange extends BaseDTO {

     public static final String FIELD_CHANGE_ID = "changeId";
     public static final String FIELD_LIMIT_TYPE = "limitType";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_LIMIT_COMPANY_ID = "limitCompanyId";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_GOOD_ID = "goodId";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_LIMIT_AMOUNT = "limitAmount";
     public static final String FIELD_SUBMIT_DATE = "submitDate";
     public static final String FIELD_APPROVED_DATE = "approvedDate";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


     @Id
     @GeneratedValue
     private Long changeId;

     @Length(max = 60)
     private String limitType; //授信类型

     private Long companyId; //公司FND_COMPANY_B.COMPANY_ID

     private Long limitCompanyId; //资方ID

     @Length(max = 60)
     private String status; //申请状态

     private Long goodId; //商品ID

     private Long orderId; //订单ID

     private Long limitAmount; //授信额度

     private Date submitDate; //提交日期

     private Date approvedDate; //审批日期

     private Long programApplicationId;

     private Date programUpdateDate;


     public void setChangeId(Long changeId){
         this.changeId = changeId;
     }

     public Long getChangeId(){
         return changeId;
     }

     public void setLimitType(String limitType){
         this.limitType = limitType;
     }

     public String getLimitType(){
         return limitType;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setLimitCompanyId(Long limitCompanyId){
         this.limitCompanyId = limitCompanyId;
     }

     public Long getLimitCompanyId(){
         return limitCompanyId;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setGoodId(Long goodId){
         this.goodId = goodId;
     }

     public Long getGoodId(){
         return goodId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setLimitAmount(Long limitAmount){
         this.limitAmount = limitAmount;
     }

     public Long getLimitAmount(){
         return limitAmount;
     }

     public void setSubmitDate(Date submitDate){
         this.submitDate = submitDate;
     }

     public Date getSubmitDate(){
         return submitDate;
     }

     public void setApprovedDate(Date approvedDate){
         this.approvedDate = approvedDate;
     }

     public Date getApprovedDate(){
         return approvedDate;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
