package com.jingrui.jrap.fnd.dto;

/**
 * Auto Generated By Jrap Code Generator
 **/

import javax.persistence.*;
import javax.persistence.criteria.JoinType;

import com.jingrui.jrap.account.dto.Role;
import com.jingrui.jrap.account.dto.User;
import com.jingrui.jrap.hr.dto.HrOrgUnit;
import com.jingrui.jrap.mybatis.annotation.ExtensionAttribute;
import com.jingrui.jrap.mybatis.common.query.JoinColumn;
import com.jingrui.jrap.mybatis.common.query.JoinOn;
import com.jingrui.jrap.mybatis.common.query.JoinTable;
import com.jingrui.jrap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Length;
import com.jingrui.jrap.system.dto.BaseDTO;

import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "fnd_notice")
public class Notice extends BaseDTO {

    public static final String FIELD_NOTICE_ID = "noticeId";
    public static final String FIELD_NOTICE_TYPE = "noticeType";
    public static final String FIELD_STATUS = "status";
    public static final String FIELD_COMPANY_ID = "companyId";
    public static final String FIELD_ROLE_ID = "roleId";
    public static final String FIELD_USER_ID = "userId";
    public static final String FIELD_NOTICE_DATE = "noticeDate";
    public static final String FIELD_NOTICE_TITLE = "noticeTitle";
    public static final String FIELD_CONTENT = "content";
    public static final String FIELD_START_DATE = "startDate";
    public static final String FIELD_END_DATE = "endDate";
    public static final String FIELD_AUTHOR = "author";
    public static final String FIELD_NOTICE_DIGEST = "noticeDigest";
    public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
    public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";


    @Where
    @Id
    @GeneratedValue
    @OrderBy("desc")
    private Long noticeId;

    @Where
    @Length(max = 60)
    private String noticeType;

    @Where
    @Length(max = 30)
    private String status;

    @Where
    @JoinTable(name = "companyJoin", target = Company.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Company.FIELD_COMPANY_ID)})
    private Long companyId;

    @Transient
    @JoinColumn(joinName = "companyJoin", field = Company.FIELD_COMPANY_FULL_NAME)
    private String companyFullName; // 商户全称

    @Where
    @JoinTable(name = "roleJoin", target = Role.class, type = JoinType.LEFT, on = {@JoinOn(joinField = Role.FIELD_ROLE_ID)})
    private Long roleId;

    @Transient
    @JoinColumn(joinName = "roleJoin", field = Role.FIELD_ROLE_NAME)
    private String roleName; // 角色名

    @Where
    @JoinTable(name = "userJoin", target = User.class, type = JoinType.LEFT, on = {@JoinOn(joinField = User.FIELD_USER_ID)})
    private Long userId;

    @Transient
    @JoinColumn(joinName = "userJoin", field = User.FIELD_USER_NAME)
    private String userName; // 用户名

    @Where
    private Date noticeDate;

    @Where
    @Length(max = 200)
    private String noticeTitle;

    @Where
    @Length(max = 65535)
    private String content;

    @Where
    private Date startDate;

    @Where
    private Date endDate;

    @Where
    private Long author;

    @Where
    @Length(max = 200)
    private String noticeDigest;

    @Where
    private Long programApplicationId;

    @Where
    private Date programUpdateDate;

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getNoticeDigest() {
        return noticeDigest;
    }

    public void setNoticeDigest(String noticeDigest) {
        this.noticeDigest = noticeDigest;
    }

    public String getCompanyFullName() {
        return companyFullName;
    }

    public void setCompanyFullName(String companyFullName) {
        this.companyFullName = companyFullName;
    }


    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public void setNoticeId(Long noticeId) {
        this.noticeId = noticeId;
    }

    public Long getNoticeId() {
        return noticeId;
    }

    public void setNoticeType(String noticeType) {
        this.noticeType = noticeType;
    }

    public String getNoticeType() {
        return noticeType;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setNoticeDate(Date noticeDate) {
        this.noticeDate = noticeDate;
    }

    public Date getNoticeDate() {
        return noticeDate;
    }

    public void setNoticeTitle(String noticeTitle) {
        this.noticeTitle = noticeTitle;
    }

    public String getNoticeTitle() {
        return noticeTitle;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContent() {
        return content;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setAuthor(Long author) {
        this.author = author;
    }

    public Long getAuthor() {
        return author;
    }

    public void setProgramApplicationId(Long programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    public Long getProgramApplicationId() {
        return programApplicationId;
    }

    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

}
